### ISSUE TITLE
[Bug]: io.base download_sample_data_files not updated in conda version 3.5 

### ISSUE THREAD

**Issue by ShihengDuan** [PCMDI/pcmdi_metrics#1114]
### What happened?

I'm following the Demo0 but it shows ```pcmdi_metrics.io.base``` doesn't have module ```download_sample_data_files```. I have to git clone the repo and pip install to solve this problem. 

Then at ```from download_sample_data import generate_parameter_files``` I have a similar problem that ``` No module named 'download_sample_data'```. It works when I put my notebook under the Demo path. I believe this is not related to the PMP version. 

### Environment

When I use conda install, it shows version 3.5 when I check with ```conda list pcmdi_metrics```. But it shows 3.4.1 with ```pip show pcmdi_metrics```, and in the notebook it shows 3.3.1. After I used ```pip install .```, it shows the correct version with ```pip show pcmdi_metrics```. 
```
(pcmdi) duan0000@perlmutter:login16:/pscratch/sd/d/duan0000/neuralgcm/results> pip show pcmdi_metrics
Name: pcmdi_metrics
Version: 3.4.1
Summary: model metrics tools
Home-page: http://github.com/PCMDI/pcmdi_metrics
Author: PCMDI
Author-email: 
License: 
Location: /global/u2/d/duan0000/.conda/envs/pcmdi/lib/python3.10/site-packages
Requires: 
Required-by: 

(pcmdi) duan0000@perlmutter:login16:/pscratch/sd/d/duan0000/neuralgcm/results> pip show pcmdi_metrics
Name: pcmdi_metrics
Version: 3.5
Summary: model metrics tools
Home-page: http://github.com/PCMDI/pcmdi_metrics
Author: PCMDI
Author-email: 
License: 
Location: /global/u2/d/duan0000/.conda/envs/pcmdi/lib/python3.10/site-packages
Requires: 
Required-by: 
```

**Comment by lee1043** [comment]
@ShihengDuan thank you for the report! @acordonez and I will take this a look.

**Comment by lee1043** [comment]
@ShihengDuan I couldn't reproduce this error. Could you retry after reinstalling the PMP and if the issue is still persistence?

**Comment by acordonez** [comment]
Discussed offline, issue resolved on user's end.
