### ISSUE TITLE
[Feature]: Reduce number of plots from modes of variability

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#1120]
### Is your feature request related to a problem?

Suggested by @zhangshixuan1987 at https://github.com/PCMDI/pcmdi_metrics/pull/1112#issuecomment-2328128362 and discussed in https://github.com/PCMDI/pcmdi_metrics/pull/1112#issuecomment-2328424624. 

### Describe the solution you'd like

Maybe `plot` option can be elaborated to `plot_eof`, `plot_additional_eofs`, and `plot_cbf`?

**Comment by zhangshixuan1987** [comment]
Hi Jiwoo,

I think a clearer group of the output figures can be enough to address the confusions. Here is my idea:

  1.  Take SAM, PSA1 and PSA2 as examples,  they were first three modes of EOF analysis from either sea level pressure or 500hPa geopotential height.
  2.  In theory, we expect that the first, second and third EOFs are corresponding to SAM, PSA1 and PSA2, respectively. Therefore, to my understanding, we can group the output figures into three groups:
     *   “Mode pattern”:  save the expected EOF pattern (theoretical), i.e. EOF1 from reference and model as they are supposed to be the SAM.
     *   “Best Matching EOF pattern”: i.e. the EOF patterns that can best match  expected EOF pattern (theoretical) for SAM, PSA1 or PSA2.
     *   “EOF Pool”: the first three leadings EOFs in reference and model as additional information

I am just sharing the thoughts from me as a references for you, and my group maybe not optimal.

However, split plot option to plot_eof, plot_additional_eofs, and plot_cbf also sounds good to me as it ineed allows users to decide if they want the addental figures.
Thank you!

With best wishes,

Shixuan



Shixuan Zhang| Pacific Northwest National Laboratory
Earth Scientist, Atmospheric, Climate, & Earth Sciences Division
p. 509.375.3926
www.pnnl.gov<https://www.pnnl.gov/science/staff/staff_info.asp?staff_num=9376>


From: Jiwoo Lee ***@***.***>
Date: Tuesday, September 10, 2024 at 15:23
To: PCMDI/pcmdi_metrics ***@***.***>
Cc: Zhang, Shixuan ***@***.***>, Mention ***@***.***>
Subject: [PCMDI/pcmdi_metrics] [Feature]: Reduce number of plots from modes of variability (Issue #1120)
Check twice before you click! This email originated from outside PNNL.

Is your feature request related to a problem?

Suggested by @zhangshixuan1987<https://github.com/zhangshixuan1987> at #1112 (comment)<https://github.com/PCMDI/pcmdi_metrics/pull/1112#issuecomment-2328128362> and discussed in #1112 (comment)<https://github.com/PCMDI/pcmdi_metrics/pull/1112#issuecomment-2328424624>.

Describe the solution you'd like

Maybe plot option can be elaborated to plot_eof, plot_additional_eofs, and plot_cbf?

Describe alternatives you've considered

No response

Additional context

No response

**Comment by lee1043** [comment]
I have added two figures (examples shown as below), which summarize the mode and compare to the reference dataset. While it is not reducing number of plots (actually add 2 more..), @kristinchang3 and I can make this multi-panel figure accessible from the PMP html viewer, so users are not necessarily finding needed figure through multiple plots unless they need to look in details.  

### Result from the CBF methodology:

![PDO_ts_EOF1_monthly_cmip5_ACCESS1-0_historical_r1i1p1_mo_atm_1900-1905_cbf_compare_obs](https://github.com/user-attachments/assets/32c1688d-dfee-479f-84ac-93d12cbaedc8)

### Result from the traditional EOF methodology:

![PDO_ts_EOF1_monthly_cmip5_ACCESS1-0_historical_r1i1p1_mo_atm_1900-1905_eof1_compare_obs](https://github.com/user-attachments/assets/59449854-90ba-45df-a1fd-2e5aede09022)

**Comment by lee1043** [comment]
@zhangshixuan1987 any feedback would be appreciated. Please also feel free to reopen this issue or open a new issue if needed.

**Comment by lee1043** [comment]
> @lee1043: Hi Jiwoo, I apologize for the overlooking of this github message. The figure looks good to me, I will adjust my workflow to include this view method for the mode varibility.

No problem, thank you!
