### ISSUE TITLE
[Feature]: Removal of CDAT, cdms, cdutil, etc. 

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#1163]
Remove dependency to CDAT libraries. 

Note: This task is aligned with E3SM Unified Env version update. See https://github.com/E3SM-Project/e3sm-unified/pull/118

**Comment by lee1043** [comment]
During the mean time, numpy version restriction caused by cdms was resolved by @xylar. The patched cdms can be installed via the following way:

https://github.com/E3SM-Project/e3sm-unified/pull/118#issuecomment-2442825954

We can make the removal as two steps:
1) update numpy to newer version to ensure no breaking
2) remove cdat dependencies

Note: remaining cdat components are in:
- ENSO
- Monsoon Wang
- precip distribution

**Comment by xylar** [comment]
Make sure to test cdms2 and numpy >=2.0, because it's definitely possible that my patching hasn't caught all the incompatibilities.  Please ping me as you notice numpy issues and/or create an issue: https://github.com/conda-forge/cdms2-feedstock/issues
