### ISSUE TITLE
[Bug]: AttributeError: module 'pcmdi_metrics' has no attribute 'version'

### ISSUE THREAD

**Issue by acordonez** [PCMDI/pcmdi_metrics#1191]
### What happened?

When I install the PMP from the main branch in my local repository, I get the following error running metrics that use the generateProvenance() function:
```
Traceback (most recent call last):
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/bin/variability_across_timescales_PS_driver.py", line 64, in <module>
    precip_variability_across_timescale(
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py", line 165, in precip_variability_across_timescale
    JSON.write(
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/io/base.py", line 392, in write
    out_dict = OrderedDict({"provenance": generateProvenance()})
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/io/base.py", line 192, in generateProvenance
    prov["packages"]["PMP"] = pcmdi_metrics.version.__git_tag_describe__
AttributeError: module 'pcmdi_metrics' has no attribute 'version'. Did you mean: '_version'?
```

### What did you expect to happen? Are there are possible answers you came across?

There should not be any error here. It appears that the way the version is found needs to be changed in getProvenance().

### Minimal Complete Verifiable Example (MVCE)

```python
#Pip install the PMP from main (or 3.7+ tag) and activate environment
#Go to doc/jupyter/Demo
#In command line, run one of the metrics examples:
variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py
```

### Relevant log output

```python
>>variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py
demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/
pr_day_GISS-E2-H_historical_r6i1p1_*.nc
[2000, 2005]
730 365
2
demo_output_tmp/precip_variability/GISS-E2-H_orig2/
demo_output_tmp/precip_variability/GISS-E2-H_orig2/
demo_output_tmp/precip_variability/GISS-E2-H_orig2/
['demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc']
GISS-E2-H.r6i1p1
['demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc']
GISS-E2-H.r6i1p1 365_day
2000 2005
Complete regridding from (2190, 90, 144) to (2190, 90, 180)
/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py:341: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  climtime = pd.period_range(
Complete calculating climatology and anomaly for calendar of 365_day
Complete power spectra (segment:  730  nps: 5.0 )
Complete domain and frequency average of spectral power
Complete power spectra (segment:  730  nps: 5.0 )
Complete domain and frequency average of spectral power
Traceback (most recent call last):
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/bin/variability_across_timescales_PS_driver.py", line 64, in <module>
    precip_variability_across_timescale(
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py", line 165, in precip_variability_across_timescale
    JSON.write(
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/io/base.py", line 392, in write
    out_dict = OrderedDict({"provenance": generateProvenance()})
  File "/global/homes/a/aordonez/miniconda3/envs/pmp_version/lib/python3.10/site-packages/pcmdi_metrics/io/base.py", line 192, in generateProvenance
    prov["packages"]["PMP"] = pcmdi_metrics.version.__git_tag_describe__
AttributeError: module 'pcmdi_metrics' has no attribute 'version'. Did you mean: '_version'?
```

### Anything else we need to know?

One fix I have tried that solved this for me is to change generateProvenance L192 to the following:
`prov["packages"]["PMP"] = pcmdi_metrics._version.__version__`

### Environment

<details>
<summary> Click here to expand</summary>

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
algopy                    0.6.1              pyhd8ed1ab_0    conda-forge
anyio                     4.6.2.post1        pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310ha75aee5_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.8.0               hb88c0a9_10    conda-forge
aws-c-cal                 0.8.0                hecf86a2_2    conda-forge
aws-c-common              0.10.3               hb9d3cd8_0    conda-forge
aws-c-compression         0.3.0                hf42f96a_2    conda-forge
aws-c-event-stream        0.5.0                h1ffe551_7    conda-forge
aws-c-http                0.9.1                hab05fe4_2    conda-forge
aws-c-io                  0.15.2               hdeadb07_2    conda-forge
aws-c-mqtt                0.11.0               h7bd072d_8    conda-forge
aws-c-s3                  0.7.1                h3a84f74_3    conda-forge
aws-c-sdkutils            0.2.1                hf42f96a_1    conda-forge
aws-checksums             0.2.2                hf42f96a_1    conda-forge
aws-crt-cpp               0.29.4               h21d7256_1    conda-forge
aws-sdk-cpp               1.11.449             h1a02111_2    conda-forge
azure-core-cpp            1.14.0               h5cfcd09_0    conda-forge
azure-identity-cpp        1.10.0               h113e628_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h3cf044e_1    conda-forge
azure-storage-common-cpp  12.8.0               h736e048_1    conda-forge
azure-storage-files-datalake-cpp 12.12.0              ha633028_1    conda-forge
babel                     2.16.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.2.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
bokeh                     3.6.1              pyhd8ed1ab_0    conda-forge
branca                    0.7.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
brotli-python             1.1.0           py310hf71b8c6_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.3               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cartopy                   0.24.0          py310h5eaa309_0    conda-forge
cdat_info                 8.2.1              pyhd8ed1ab_2    conda-forge
cdms2                     3.1.5           py310h4f3777b_25    conda-forge
cdp                       1.7.0              pyhd8ed1ab_1    conda-forge
cdtime                    3.1.4           py310h7a088e3_13    conda-forge
cdutil                    8.2.1              pyhd8ed1ab_4    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cf_xarray                 0.10.0             pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py310h8deb56e_0    conda-forge
cftime                    1.6.4           py310hf462985_1    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_1    conda-forge
colorcet                  3.1.0              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.1           py310h3788b33_0    conda-forge
curl                      8.10.1               hbbe4b11_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   1.0.0           py310ha75aee5_1    conda-forge
dask                      2024.8.2           pyhd8ed1ab_0    conda-forge
dask-core                 2024.8.2           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.13             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.8           py310hf71b8c6_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distarray                 2.12.2             pyh050c7b8_4    conda-forge
distributed               2024.8.2           pyhd8ed1ab_0    conda-forge
enso_metrics              1.1.2           py310hff52083_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
eofs                      2.0.0              pyhff2d567_0    conda-forge
esmf                      8.7.0           nompi_h6063b07_0    conda-forge
esmpy                     8.7.0              pyhecae5ae_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
folium                    0.18.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.55.0          py310h89163eb_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freeglut                  3.2.2                ha6d2627_3    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
fsspec                    2024.10.0          pyhff2d567_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
g2clib                    1.9.0                ha770c72_1    conda-forge
genutil                   8.2.1           py310h21aefe9_5    conda-forge
geopandas                 1.0.1              pyhd8ed1ab_1    conda-forge
geopandas-base            1.0.1              pyha770c72_1    conda-forge
geos                      3.13.0               h5888daf_0    conda-forge
geotiff                   1.7.3                h77b800c_3    conda-forge
gflags                    2.2.2             h5888daf_1005    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.4          nompi_h2d575fe_103    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.7              pyh29332c3_1    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.29.0             pyh707e725_0    conda-forge
ipython_genutils          0.2.0              pyhd8ed1ab_1    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jasper                    4.2.4                h536e39c_0    conda-forge
jedi                      0.19.2             pyhff2d567_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json-c                    0.18                 h6688a6e_0    conda-forge
json5                     0.9.28             pyhff2d567_0    conda-forge
jsonpointer               3.0.0           py310hff52083_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.3.1              pyhff2d567_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py310h3788b33_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lazy-object-proxy         1.10.0          py310h2372a71_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libarrow                  18.0.0          h90946fb_7_cuda    conda-forge
libarrow-acero            18.0.0          h530483c_7_cuda    conda-forge
libarrow-dataset          18.0.0          h530483c_7_cuda    conda-forge
libarrow-substrait        18.0.0          hb57c354_7_cuda    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcdms                   3.1.2              had6e27f_130    conda-forge
libcf                     1.0.3           py310h1588dd5_117    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libdrm                    2.4.123              hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libegl                    1.7.0                ha4b6fd6_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgdal-core              3.9.3                hef9eae6_3    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgl                     1.7.0                ha4b6fd6_2    conda-forge
libglu                    9.0.3                h03adeef_0    conda-forge
libglvnd                  1.7.0                ha4b6fd6_2    conda-forge
libglx                    1.7.0                ha4b6fd6_2    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgoogle-cloud           2.31.0               h804f50b_0    conda-forge
libgoogle-cloud-storage   2.31.0               h0121fbd_0    conda-forge
libgrpc                   1.67.1               hc2c308b_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hf539b9f_1021    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnetcdf                 4.9.2           nompi_h2564987_115    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libparquet                18.0.0          hdbc8f64_7_cuda    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libprotobuf               5.28.2               h5b01275_0    conda-forge
libre2-11                 2024.07.02           hbbce691_1    conda-forge
librttopo                 1.1.0               h97f6797_17    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libspatialite             5.1.0               h1b4f908_11    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libthrift                 0.21.0               h0e7cc3e_0    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libudunits2               2.2.28               h40f5838_3    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.5               hb346dea_0    conda-forge
libzip                    1.11.2               h6991a6a_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
llvmlite                  0.43.0          py310h1a6248f_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3           py310hb259640_1    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mapclassify               2.8.1              pyhd8ed1ab_0    conda-forge
markupsafe                3.0.2           py310h89163eb_0    conda-forge
matplotlib-base           3.9.2           py310h68603db_2    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
msgpack-python            1.1.0           py310h3788b33_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nb_conda                  2.2.1                    unix_7    conda-forge
nb_conda_kernels          2.5.1              pyh707e725_2    conda-forge
nbclassic                 1.1.0              pyhd8ed1ab_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
nc-time-axis              1.4.1              pyhd8ed1ab_0    conda-forge
nceplibs-g2c              1.9.0                ha39ef1c_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.1           nompi_ha5d1325_107    conda-forge
netcdf4                   1.7.2           nompi_py310h5146f0f_100    conda-forge
networkx                  3.4                pyhd8ed1ab_0    conda-forge
notebook                  6.5.7              pyha770c72_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numba                     0.60.0          py310h5dc88bb_0    conda-forge
numdifftools              0.9.41             pyhd8ed1ab_0    conda-forge
numpy                     1.23.5          py310h53a5b5f_0    conda-forge
openblas                  0.3.28          pthreads_h6ec200e_1    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
orc                       2.0.3                he039a57_0    conda-forge
output_viewer             1.3.3              pyhd8ed1ab_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.2               pyhff2d567_1    conda-forge
pandas                    2.2.3           py310h5eaa309_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
patsy                     1.0.1              pyhff2d567_0    conda-forge
pcmdi_metrics             3.7                pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0          py310hfeaa1f3_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pooch                     1.8.2              pyhd8ed1ab_0    conda-forge
proj                      9.5.0                h12925eb_0    conda-forge
prometheus_client         0.21.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
psutil                    6.1.0           py310ha75aee5_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   18.0.0          py310hff52083_1    conda-forge
pyarrow-core              18.0.0          py310h23ac199_1_cuda    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyogrio                   0.10.0          py310h63d473e_0    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyproj                    3.7.0           py310h2e9f774_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.15         h4a871b0_2_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    5_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py310ha75aee5_1    conda-forge
pyzmq                     26.2.0          py310h71f11fc_3    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
rasterio                  1.4.2           py310hf6c6cbe_0    conda-forge
re2                       2024.07.02           h77b4e00_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
regionmask                0.12.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.21.0          py310h505e2c1_0    conda-forge
s2n                       1.5.9                h0fd0ee4_0    conda-forge
scikit-learn              1.5.2           py310h27f47ee_1    conda-forge
scipy                     1.14.1          py310hfcf56fc_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
send2trash                1.8.3              pyh0d859eb_0    conda-forge
setuptools                75.5.0             pyhff2d567_0    conda-forge
shapely                   2.0.6           py310had3dfd6_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7              pyhd8ed1ab_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sparse                    0.15.4             pyh267e887_1    conda-forge
sqlite                    3.47.0               h9eae976_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.4          py310hf462985_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1             pyh0d859eb_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.1.0              pyhff2d567_0    conda-forge
toolz                     1.0.0              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py310ha75aee5_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20241003     pyhff2d567_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
udunits2                  2.2.28               h40f5838_3    conda-forge
unicodedata2              15.1.0          py310ha75aee5_1    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.45.0             pyhd8ed1ab_0    conda-forge
xarray                    2024.7.0           pyhd8ed1ab_0    conda-forge
xcdat                     0.7.2              pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.5                h988505b_2    conda-forge
xesmf                     0.8.8              pyhd8ed1ab_0    conda-forge
xgcm                      0.8.1              pyhd8ed1ab_0    conda-forge
xmltodict                 0.14.2             pyhd8ed1ab_0    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.1                hb9d3cd8_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxxf86vm           1.1.5                hb9d3cd8_4    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xyzservices               2024.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.5                h3b0a872_7    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.21.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0          py310ha39cb0e_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

</details>

**Comment by lee1043** [comment]
@acordonez thank you for reporting. This looks like it was caused by one of recent changes I made at https://github.com/PCMDI/pcmdi_metrics/commit/fadc800aaafc51244d5f60f06beb486f69a0e0e9. Let me open a PR to handle this issue.
