### ISSUE TITLE
[Bug]: Potential bug in enso_driver.py 

### ISSUE THREAD

**Issue by zhangshixuan1987** [PCMDI/pcmdi_metrics#1220]
### What happened?

Hi @lee1043 : 

I am working on merging the update of PCMDI to the e3sm zppy-pcmdi workflow, and I found that there is possibly a bug in the following lines of enso_driver.py: 
- https://github.com/PCMDI/pcmdi_metrics/blob/025d2f019edf960c7709641c298d0d213da27c05/pcmdi_metrics/enso/enso_driver.py#L633C1-L634C1

Specifically, the enso diagnostics only defined for the following groups:
- ["graphics", "diagnostic_results", "metrics_results"]
There is no 'diagnostics' defined, which is complained by PCMDI on my side and caused failure of the ENSO diagnostics 

In addition, I have one comment here for the pcmdi package related to enso diagnostics:

- the cmds2 was still used in 'enso_driver.py', but I saw that the "xcdat" (xarray) was used to replace the cdms2 in other modules such as "mean_climate_driver.py". I think that it could be better to update the 'enso_driver.py' as well to replace "cmds2" with "xcdat" (xarray) as the former is not supported anymore (I heard from Jill) 
 

### Environment

<details>
<summary>Click to expand</summary>

- **Python version**: e.g., Python 3.9.7
- **Operating system**: e.g., Ubuntu 20.04
- **Dependencies**: List relevant dependencies and their versions, e.g., `numpy 1.23.1`, `xarray 0.21.1`

</details>

**Comment by lee1043** [comment]
> I am working on merging the update of PCMDI to the e3sm zppy-pcmdi workflow, and I found that there is possibly a bug in the following lines of enso_driver.py:
> 
>     * https://github.com/PCMDI/pcmdi_metrics/blob/025d2f019edf960c7709641c298d0d213da27c05/pcmdi_metrics/enso/enso_driver.py#L633C1-L634C1
> 
> 
> Specifically, the enso diagnostics only defined for the following groups:
> 
>     * ["graphics", "diagnostic_results", "metrics_results"]
>       There is no 'diagnostics' defined, which is complained by PCMDI on my side and caused failure of the ENSO diagnostics

Thank you finding this out! Let me fix it immediately. 

 
> In addition, I have one comment here for the pcmdi package related to enso diagnostics:
> 
>     * the cmds2 was still used in 'enso_driver.py', but I saw that the "xcdat" (xarray) was used to replace the cdms2 in other modules such as "mean_climate_driver.py". I think that it could be better to update the 'enso_driver.py' as well to replace "cmds2" with "xcdat" (xarray) as the former is not supported anymore (I heard from Jill)

That is a great comment and we are actually working on it at the moment. I heard that the e3sm unified env team decided to keep cdms2 little bit longer so we still have some time to fix it, but let me see if I can expedite the conversion.

**Comment by lee1043** [comment]
@zhangshixuan1987 thank you the opening this issue! I updated the code in the main branch. Could you please retry with the latest code in the main branch to see if that resolves the issue?

**Comment by zhangshixuan1987** [comment]
@lee1043 : Thank you! I will try the update and let you know!
