### ISSUE TITLE
Fix issue with double period in output (interpolated) filenames

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#200]
Fix issue with double period in output (interpolated) filenames:
```
public1:/home/p1d/141231_metrics/test> ls -al metrics_output_path/Interpolation_Output/sampletest/
total 14400
drwxr-xr-x 2 p1d b   6144 Dec 31 22:55 ./
drwxr-xr-x 3 p1d b   2048 Dec 31 22:54 ../
-rw-r--r-- 1 p1d b 504336 Dec 31 22:55 GFDL-CM4.historical.r1i1p1.mo..pr.ver-1.01-12.interpolated.linear.2.5x2.5.AC.nc
-rw-r--r-- 1 p1d b 504328 Dec 31 22:55 GFDL-CM4.historical.r1i1p1.mo..psl.ver-1.01-12.interpolated.linear.2.5x2.5.AC.nc
```

**Comment by durack1** [comment]
@doutriaux1 this issue is related to the ```%(table_realm)``` variable not being defined and therefore returning a blank in the file (leading to double delimiters)..

Should ```%(table_realm)``` actually be ```%(table)```? I wonder if we should define what variables are what somewhere - probably in the parameter file:

So this should include:
model_version
table_realm/table
variable
level
period
regridMethod
targetGridName
ext

**Comment by durack1** [comment]
This issue was due to a bad parameter file (and wrongly defined table info).. @doutriaux1 before closing this should my comments above (RE: better documenting param file) be dealt with somewhere? Or should we create a new issue which includes template parameter file tweaks along with tweaks to the wiki?

**Comment by doutriaux1** [comment]
@durack1 you're right we should document this. In the paramter files we provide would be a good start point. But it probably also needs to be documented somewhere more "official". Like in the actual documentation.

**Comment by durack1** [comment]
@doutriaux1 ok well to start I think we need to agree on which existing parameter file becomes our go to default (from which all others are based).. I spent a fair bit of time cleaning up  pcmdi_metrics/doc/parameter_files/pcmdi_input_parameters_test.py which now includes a whole whack of verbose descriptions.. Maybe that also needs some of your custom keys stuff? And then of course listing the variables (model_version, variable.. as listed above https://github.com/PCMDI/pcmdi_metrics/issues/200#issuecomment-69061025)

**Comment by doutriaux1** [comment]
@durack1 nope this one has pretty much nothing in it...

A more complete is at:
https://github.com/PCMDI/pcmdi_metrics/blob/master/test/pcmdi/basic_test_parameters_file.py

but some param tweakfor sftlf handling are also found  in:
https://github.com/PCMDI/pcmdi_metrics/blob/master/test/pcmdi/gensftlf_test.py

**Comment by durack1** [comment]
@doutriaux1 ok I think these two need to be merged, so that we have a single demo param file that contains all the options..

**Comment by durack1** [comment]
@doutriaux1 I'll finalise this tomorrow so we can finish and retag v1.0.0.. Can you tell me where all the input variables (the software knows about) can be found in a list?
