### ISSUE TITLE
Portrait plot tweaks

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#201]
Currently the portrait plot script is hunting around for json files that contain either multiple model results (CMIP5 examples) or potentially results from just one model (GFDL example) this is leading to a plot which repeats variables over and over again (see attachment):
![test_portrait-4seas](https://cloud.githubusercontent.com/assets/3229632/5622378/79521f34-94f7-11e4-8eb7-337d0bf45f00.png)

We need to tweak this to be a little more intelligent, so our example/demo files for GFDL (and others) are more useable and yield useful results..

**Comment by durack1** [comment]
@doutriaux1 here it is https://github.com/durack1/pcmdi_metrics/tree/issue201_durack1_PortraitPlotTemplateTweaks/src/python/pcmdi/scripts/GFDL

@gleckler1 probably has some comments to make too..

**Comment by doutriaux1** [comment]
Yes the script was mostly made for the unit test.

I will create a function that "loads" multiple json files and return the correct array/settings for portrait plots.

**Comment by durack1** [comment]
@doutriaux1 as we haven't sorted out *sos* (which is related to https://github.com/PCMDI/pcmdi_metrics/issues/162) we'll also need to deal with cases where the CMIP5 results exist, but there is no equivalent for the model being compared (in this case from GFDL)

**Comment by doutriaux1** [comment]
missing are not a problem, the issue here is to not create duplicates. Where will need decision making is cases where model are given for the same var twice (i.e json files for historical and control mixed together), then need to make a decision:
* use the last one
* use the first one
* duplicate and find/decide on some field to append on model name (or vars?)

etc...

**Comment by durack1** [comment]
@gleckler1 will need to chip into this discussion I think..

**Comment by durack1** [comment]
As part of this issue/PR I also have some updated GFDL parameter (and createXmlsAndNcs.py) files to update.. @gleckler1 and @doutriaux1 when the portrait tweaks are finalised, I'll update all these files in one PR..

**Comment by durack1** [comment]
@doutriaux1 I'll add in the updated create*.py and the param file (will rename to gfdl_*) to the repo, and add the *.png demo files to setup.py and close this tomorrow.
