### ISSUE TITLE
Pairs keyword/value

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#205]
As you know, at IPSL we aim at using the results of the metrics by storing all those in a MongoDB database. The interest of this strategy is that we will automatically store the results of all the simulations ran at IPSL (right after the computation of the post-treatments of the simulations, i.e. the creation of the annual cycles files). The CMIP5 metric results will be stored in the same collection so we can cross the results. Finally, with the visualization tool developed by Patrick (the Metrics Garden), we will be able to build a portrait plot with a selection of metrics, for a selection of simulations that we will pick up by searching for given values of a set of keywords.
At the moment, we have a reformatting script that takes the MP output json files, extracts the list of keywords we want and associates the values of those keywords for each metric result. One reason to do this is that the correspondance keyword <-> value is not always present in the json dictionary ; sometimes we find directly the value without the keyword.
Ex:
            "source": "CERES",
            "Cplv5G001": {
                "global": {
Instead of:
            "source": "CERES",
            "SimName":"Cplv5G001": {
                "RegionalMasking":"global": {
This is maybe not a big deal but completing this correspondance would surely help using the output of the MP directly, at least on our point of view. This allows a better use of the functionalities of a MongoDB database for sure.
Looking for your opinion!

**Comment by durack1** [comment]
@doutriaux1 is this due to a bug that may have already been fixed?

**Comment by jservonnat** [comment]
Actually I realize that the way I wrote the json tree is wrong. It would rather be something like:
"source": {
                 "CERES" : {
                                     "SimName": { "Cplv5G001": {
     "RegionalMasking":"global": {

**Comment by durack1** [comment]
@jservonnat we're starting to clean things up for the 1.1 release.. Is this still relevant, or should it be closed?

**Comment by durack1** [comment]
@jservonnat we're starting to clean things up for the 1.1 release.. If this is still relevant, please reopen..

**Comment by jservonnat** [comment]
@durack1 no that's fine ;)
