### ISSUE TITLE
Masks : global, land, ocean… sea ice ?

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#206]
A question about the land-ocean mask : at the moment, there is a separation between land and ocean surfaces. Does the ocean mask incorporates sea ice ? In both cases (yes or no), what led you to this choice ? This is a call for an open discussion and I imagine that we are facing both scientific (what can we consider as the ocean) and practical reasons (mask varies from one model to the next)…

**Comment by durack1** [comment]
@jservonnat the land/ocean mix is oblivious to sea ice - that is land is persistent throughout each timestep (and so is the ocean field). These are fixed (fx) fields, which are not time varying.

@gleckler1 can comment more about this..

**Comment by gleckler1** [comment]
Good question.   As durack1 mentioned, applying the time-invariant land/sea mask is an important first step, which enables us to partition between land-only and ocean-only statistics.   For most of the ocean-only statistics we are currently testing we will be masking equatorward of any sea-ice, say at 50S or 50N.  This is pretty standard for avoiding the complexities associated with sea-ice.   There will come a time when we need to treat the sea-ice, but that is not now with our mean state statistics.   pg

**Comment by jservonnat** [comment]
It makes sense indeed. Ok for me!

**Comment by durack1** [comment]
@jservonnat we're doing a cleanup so closing this - reopen if there's something to be done here..
