### ISSUE TITLE
add flag for on/off pcmdi metrics

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#219]
thanks @jservonnat

**Comment by jservonnat** [comment]
Just to provide a little bit more information on this issue: the idea is that we want to run custom metrics on given variables, without re-running the standard pcmdi metrics.
The solution is thus to add an attribute in the parameter file to control the calculation of:
- the pcmdi metrics only
- the custom metrics only
- or both

**Comment by doutriaux1** [comment]
wel lif you don't define custom_metric then it won't compute it, so there's no need to define a flag for this ;)

**Comment by jservonnat** [comment]
@doutriaux1 I've worked on this point and found a solution, created a branch and merged it to my master (jservonnat/PCMDI_metrics_IPSL). How do I send you a PR?

**Comment by durack1** [comment]
@jservonnat does the info available at https://github.com/PCMDI/pcmdi_metrics/wiki/Tip-for-Developers help you out here?

**Comment by jservonnat** [comment]
@durack1 Actually it did help for 95% of the procedure but I'm now stucked at the point where I would like to submit a pull request to the PCMDI devel branch. I've checked on my github webpage but didn't find the way to submit the PR to the PCMDI.
So apparently the last step is to "send the PCMDI repo administrator the fork and branch information you would like to merge" :). I guess our very own @doutriaux1 is the one!
Here is my branch:
https://github.com/jservonnat/PCMDI_metrics_IPSL/tree/issue219_flag_control_compute_custom_only
@doutriaux1, let me know if I'm on the good path or not.

**Comment by durack1** [comment]
@jservonnat did you fork the PCMDI/pcmdi_metrics repo originally? If so they should be linked and you can just select the PCMDI/pcmdi_metrics master to issue the pull request against..

https://github.com/jservonnat/PCMDI_metrics_IPSL/compare

Does that help?

**Comment by jservonnat** [comment]
@doutriaux1 forked the PCMDI/wgne_wgcm_metrics repo to set me up. But the PCMDI/pcmdi_metrics master does not appear in the list... Could it be linked with my status? I think I'm just contributer and not developer...

**Comment by durack1** [comment]
@jservonnat how many files have you changed? Unless @doutriaux1 has a better suggestion, you could just fork the pcmdi_metrics repo again and then add in your changes to that..

**Comment by doutriaux1** [comment]
it should'nt matter. The fact is yes you cannot merge yourself but you can submit the PR

**Comment by doutriaux1** [comment]
github "just knows" the repo name changed

**Comment by durack1** [comment]
@jservonnat can you see this?
https://github.com/PCMDI/pcmdi_metrics/compare/jservonnat:master...master

**Comment by jservonnat** [comment]
Guys, I think I get it!
The problem was that I was working from my own version of the sources, called PCMDI_metrics_IPSL (that was my origin). I made an other local repo from jservonnat/pcmdi_metrics and apparently I was able to submit the PR.
If yes, that's a big step :)!
