### ISSUE TITLE
make compute metrics dictionary so you can have one per variable

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#220]
thanks @jservonnat

**Comment by jservonnat** [comment]
@doutriaux1 Linked with #219?

**Comment by doutriaux1** [comment]
no it's a different thing, as explained in #219, if no custom is defined it's not computed so we don't need a flag

**Comment by durack1** [comment]
Ok so I'm starting to understand this a little better - the aim here is to have multiple custom metrics - and the dictionary is the way to pass these to the package?

**Comment by doutriaux1** [comment]
@jservonnat let's talk about this, if you look at the example parameter file I show how to fill the custom_metrics with many custom metrics.
In the above example (to be placed in parameter file for example)
the function "my_custom" receives "var",obs,mod
and then send them back to my_min and my_max
If it easily conceivable that "my_custom" looks at the value of "var" and THEN decides which functions to call. I will push a PR with the updated example to reflect this.
```
def mymax(slab,nm):
  return {"custom_%s_max" % nm:float(slab.max())}

def mymin(slab,nm):
  return {"custom_%s_min" % nm:float(slab.min())}

def my_custom(var,dm,do):
  out = {}
  for f in [mymax,mymin]:
    out.update(f(dm,"model"))
    out.update(f(dm,"ref"))
  out["some_custom"]=1.5
  return out
compute_custom_metrics = my_custom
```

**Comment by jservonnat** [comment]
@doutriaux1 Sounds interesting. I'll put it on test and get back to you soon.

**Comment by doutriaux1** [comment]
@jservonnat the PR is at
https://github.com/PCMDI/pcmdi_metrics/pull/243
