### ISSUE TITLE
add dict for metrics description

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#221]
at bottom of json file
thanks @Jservonnat
@gleckler1 no worries it will be at the end

**Comment by jservonnat** [comment]
Here is a list of attributes that I used to add in my 'IPSL_extended' list of keywords (for the metrics themselves):
- MetricName: the complete name of the metric (to be discussed... RootMeanSquareErrorLatitudeLongitude is indeed univocal, but maybe RMSE_XY is explicit enough?)
- DataType: 'ann', 'djf',...
- Region: a meaningful character chain to describe the region ('SHEX','GLB',...)
- GeographicalBounds: ex: '-180.00E_180.00E_30.00S_30.00N'
- Variable
- MetricReferencePaper : reference paper associated with the metric
- MetricContactExpert : email address of a contact 
- pValue
- 95signifThreshold: the value of the statistic that corresponds to the 95% significance threshold
- MetricFreeSpace: a free space to add whatever information we need ; ex : 'PCMDI Metrics', 'IPSL Metrics'...
- Result

**Comment by gleckler1** [comment]
Trying to sneak this under in under the rug...

**Comment by doutriaux1** [comment]
hoping that Thursday's the day, we should have of RC1 on wed evening
