### ISSUE TITLE
dump stlf"ed" data

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#223]
@gleckler1 request we would like to save climatologies used once masked.

**Comment by doutriaux1** [comment]
@gleckler1 thank you for pushing this, it revealed a big error in the way sftlf are autogenerated! So this will fix tht as well.
Now turns out what you're asking for is already "sort of" implemented. The filename_output_template right now is supposed to contain a "%(region)" keyword that is used to dump various region into separate files.
Are you ok with keeping this? Or would you prefer to save ALL possible region masks into ONE single file?
You're call, just let me know. 
For now I'll assume we keep the code "as is" and will send a PR that fixes the autogen (new issue #224 ) if you're ok with code a sis just close this issue otherwise comment in here
Thanks again.

**Comment by gleckler1** [comment]
Global, land, ocean results look plausible.
Creating three separate climatologies, but no masking in any of them...

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 need to confirm this one was resolved

**Comment by gleckler1** [comment]
@doutriaux1 Just confirmed results for land and ocean model data.   Not yet outputting interpolated obs, but thats another issue....
