### ISSUE TITLE
Pass the complete variable name to compute_metrics (ua-XXX)

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#229]
In case we want to use the variable name within a custom compute_metrics function, it would be useful if 'var' was the same as the variable name provided in the parameter file.
The variable name in the output json file name is var-level, when it is var_level in the parameter file.
Would it be beneficial to have the same naming convention everywhere? (i.e. choose between var-level and var_level)

**Comment by durack1** [comment]
Thanks for these specifics @jservonnat - these kind of tweaks are exactly the kind of granular feedback that we really appreciate.. Keep it coming!

**Comment by jservonnat** [comment]
My pleasure @durack1 ;)!
