### ISSUE TITLE
Standardise "NaN" or "null" results to be consistent in json outputs

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#230]
Standardise ```NaN``` or ```null``` results to be consistent in json files (numpy quirks are leading to nan values creeping in - this will need to be systematically tested as the numpy version is incremented.

@jservonnat is there anything else relevant that needs noting in this issue?

**Comment by doutriaux1** [comment]
there are actually 2 totally different animals NaN is "Not A number" i.e something went bad. null is None means no result, which usually means either an error occured or the metrics has not been run. I think it's an important difference.

**Comment by durack1** [comment]
@doutriaux1 is there anything to do here, or you closing? I think `NaN` or even `null` results highlight problems in the processing pipeline.. And therefore we should create a dedicated issue if these appear again, thoughts?

**Comment by doutriaux1** [comment]
hum... you're probably right, it could also be due to model input errors. Plus I stand by my previous comment, "NaN" means something went bad, whereas null usually means no result. Let's close
