### ISSUE TITLE
Add the possibility to provide a custom dictionary of observations?

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#232]
The metrics package is already very handy in integrating custom metrics directly from the driver. It would be great if we could also include a custom obs dictionary to complete the list of variables.
For example, I've had requests to compute metrics on LAI, and biogeochemistry fields (chlorophyll and things like that).
It's easily done by adding a couple of lines to the driver:
![capture d ecran 2015-01-28 a 15 35 05](https://cloud.githubusercontent.com/assets/7254214/5939313/ddaf4aa2-a702-11e4-9d44-67e611a0c3d9.png)
Any thoughts?

**Comment by durack1** [comment]
It's likely this relates to #87 and updating the observation dictionary (and database) with timeseries..

**Comment by doutriaux1** [comment]
@jservonnat let's talk about this, if you look at the example parameter file I show how to fill the custom_metrics with many custom metrics.
In the above example (to be placed in parameter file for example)
the function "my_custom" receives "var",obs,mod
and then send them back to my_min and my_max
If it easily conceivable that "my_custom" looks at the value of "var" and THEN decides which functions to call. I will push a PR with the updated example to reflect this.
```
def mymax(slab,nm):
  return {"custom_%s_max" % nm:float(slab.max())}

def mymin(slab,nm):
  return {"custom_%s_min" % nm:float(slab.min())}

def my_custom(var,dm,do):
  out = {}
  for f in [mymax,mymin]:
    out.update(f(dm,"model"))
    out.update(f(dm,"ref"))
  out["some_custom"]=1.5
  return out
compute_custom_metrics = my_custom
```

**Comment by doutriaux1** [comment]
@jservonnat I like the idea, it's fairly easy to implement to as it is.
