### ISSUE TITLE
Update wiki developer corner to newest workflow (much easier)

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#233]
https://github.com/PCMDI/pcmdi_metrics/wiki/Tip-for-Developers

**Comment by durack1** [comment]
@doutriaux1 what needs to be done here?

**Comment by doutriaux1** [comment]
we don't use devel branch anymore, just master and forks and PR

**Comment by doutriaux1** [comment]
I assigned oyu because you like these sort of things. Or at least you're much better at it than me.

**Comment by durack1** [comment]
@doutriaux1 ok I see what needs being done here.. Will do it upon my return..

**Comment by durack1** [comment]
@doutriaux1 I think this is now done, [take a peek](https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers) and if it's correct these close away..
