### ISSUE TITLE
add option for "offscreen" build

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#237]
On super computers we may not have X11 avail. Adding the possibility to run the metrics built against mesa might make it faster, easier to use.

**Comment by durack1** [comment]
+1 @doutriaux1 lets set this as a 1.1 milestone so we can get around the issue described at https://github.com/UV-CDAT/uvcdat/issues/1134

**Comment by durack1** [comment]
@doutriaux1 is there a `mesa` build option flag available for this? I couldn't find it documented at https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options

**Comment by doutriaux1** [comment]
@durack1 it is actually a good idea, we should probably add mesa and turn it on by default. The main purpose of this script is to run in batch and produce files, not really meant for interactive purposes.

**Comment by durack1** [comment]
@doutriaux1 I think this is should be an upstream UVCDAT issue - want me to create an issue for it?

**Comment by doutriaux1** [comment]
no, it's already in UV-CDAT and it's OFF by default there as it should.

**Comment by durack1** [comment]
@doutriaux1 ok, well I think https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options needs to be updated to show this functionality exists too..

**Comment by doutriaux1** [comment]
done. Thanks

**Comment by durack1** [comment]
@doutriaux1 ok great, so should I wedge that into the `install_metrics.sh` as an option or the default do you reckon?

**Comment by doutriaux1** [comment]
yes ti's done waiting for the build on my little suffering mac to be done to confirm and push PR

**Comment by durack1** [comment]
@doutriaux1 is it in master or a branch? I can kick off a build elsewhere too..

**Comment by durack1** [comment]
Fixed by #273
