### ISSUE TITLE
Custom name for the mask

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#245]
I didn't find the way (via the parameter file) to define a variable mapping for the mask... in our IPSL outputs we do have the land-ocean mask, but named "fract_ter".
Can we already control this from the param file? If not I can propose a fix for this.

**Comment by durack1** [comment]
@jservonnat does the code found in https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/parameter_files/input_parameter_file_all_options.py#L15-25 help out here?

So `"variable_mapping" : { "fract_ter" : "sftlf"}` may work?

**Comment by jservonnat** [comment]
@durack1 I think that the mechanism of a dictionary to define a variable mapping is indeed the way to go (it surely works for our 'IPSL to CMIP5' variable names matching) but apparently the driver does not handle the variable mapping for the mask variable name. Is that correct?
I tried to add the 'sftlf':'fract_ter' to the list of variables mapped, but it didn't work.

**Comment by durack1** [comment]
@doutriaux1 with the variable remapping, we need to define this a bit better - is it `"user_varName" : "cmip_varName"` or the other way around, it wasn't clear to me in the parameter or driver files..

**Comment by gleckler1** [comment]
Good idea... sftlf id remapping should be done consistent mapping different variable names, e.g.,

"GFDL-ESM2G" : {
"variable_mapping" : { "tas" : "tas_ac"},
},

**Comment by durack1** [comment]
@doutriaux1 what's the status of this?
