### ISSUE TITLE
is it possible to...

### ISSUE THREAD

**Issue by markcollier** [PCMDI/pcmdi_metrics#251]
Hi,
I've been using the PCMDI Metrics software to generate basic statistics. I've been looking at the code to make some changes to do the following,

1. define my own regions, in addition to the 4 currently defined. For example, I want to define a box that covers Australia, say longitude 110:160 and latitude 10s:50s? I could call this "OZBOX".
I see:
.../PCMDI_METRICS/v1p0/tmp/metrics/src/python/pcmdi/mean
_climate_metrics_calculations.py
allows to loop over a subset of latitude, can longitude be performed?

2. how to specify a specific observational reference? How will this work if there is a list of variables rather than just 1? If I can create my own obs. dictionary (point 3) then I can define just the observational sets that I use (e.g. one for each variable) and then use "default".

3. how to define my own observational reference? I can make it, but how do I tell the system to select it?
There is a dictionary under
.../PCMDI_METRICS/v1p0/share/pcmdi/obs_info_dictionary.json, but how is this created or modified?
Can I point the software to my own version somehow?

I'm not a python programmer although are trying to do my own edits. However, as part of the documentation it would be good to know what is definable without having to make code changes, i.e. what are possible options.

Regards, Mark.
CSIRO

**Comment by markcollier** [comment]
For point 4 I was able to specify the obs. dictionary by hardwiring to my own modified file. Is there a tool to generate the obs. dictionary by specifying a observational path/tree? 
There is an option:
save_mod_clims
for saving out the interpolated model data, it would be good to have an equivalent variable to save out the observational sets. This is very useful for validation of the metrics, something most first time users will want to be able to do.

**Comment by doutriaux1** [comment]
@markcollier would you be so kind to create a separate issue for each of these, this will make it easier for us developers to address them. Thanks!

**Comment by durack1** [comment]
@markcollier there is an option in the most updated version to use a custom observational dictionary - which appends files/directory tree to the existing observational data it's discussed at #232 and https://github.com/PCMDI/pcmdi_metrics/pull/244/files

We currently use the script https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/pcmdi/scripts/build_obs_meta_dictionary.py to build the existing obs dictionary. We're planning on updating these in time, and will optimise the creation of the dictionary when this occurs.
