### ISSUE TITLE
defining own regions by reducing latitudes & longitudes

### ISSUE THREAD

**Issue by markcollier** [PCMDI/pcmdi_metrics#252]
Is it possible to define my own regions, in addition to the 4 currently defined. For example, I want to define a box that covers Australia, say longitude 110:160 and latitude 10s:50s? I could call this "OZBOX".
I see:
.../PCMDI_METRICS/v1p0/tmp/metrics/src/python/pcmdi/mean
_climate_metrics_calculations.py
allows to loop over a subset of latitude, can longitude be performed?
Regards,
Mark.

**Comment by durack1** [comment]
@markcollier this functionality is available, however it's use is not clearly documented in the parameter file examples - @doutriaux1 has self-assigned this and we'll let you know when we have something to test

**Comment by doutriaux1** [comment]
@durack1 I don't think it is implemented at all yet. All we can do so far is select land/ocean
I plan on letting you use more sophisticated masks in the future, but I think what @markcollier really wants is a subset of lat/lons (e.g. elnino area) which is not implemented at all. That could be done though via a "user-defined" diagnostic.

**Comment by durack1** [comment]
@doutriaux1 yes exactly, we already have the domains specified in https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/pcmdi/mean_climate_metrics_calculations.py (`'GLB','NHEX','TROPICS','SHEX'`) we just need to expose this list and their definition to the parameter file

**Comment by markcollier** [comment]
Is it just a case of adding in another domain, and somehow specifying that I want to work over limited longitudes too?
eg.
domains = ['GLB','NHEX','TROPICS','SHEX','OZ']
if dom == 'OZ':
            dm = dm_glb(latitude = (-50.,-10),longitude = (110.,115.))
            do = do_glb(latitude = (-50.,-10),longitude = (110.,115.))
sorry my python skills are not enough to know how to test this...

**Comment by doutriaux1** [comment]
@markcollier #361 will actually implement this. It was a quick fix wasn't it 😜  Sorry about that.
