### ISSUE TITLE
Revisit observational dataset dictionary creation

### ISSUE THREAD

**Issue by markcollier** [PCMDI/pcmdi_metrics#253]
I was able to specify the obs. dictionary by hardwiring to my own modified pcmdi_metrics_driver.py

It would be good if a variable could be set rather than changing the driver code, but that is a small point. 

Is there a tool to generate the obs. dictionary by specifying a observational path/tree, for now I am hand editing the file?

Regards,
Mark.

**Comment by durack1** [comment]
@markcollier as noted in #251 you can specify a custom dictionary of observations, and append these..

@markcollier there is an option in the most updated version to use a custom observational dictionary - which appends files/directory tree to the existing observational data it's discussed at #232 and https://github.com/PCMDI/pcmdi_metrics/pull/244/files

We currently use the script https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/pcmdi/scripts/build_obs_meta_dictionary.py to build the existing obs dictionary. We're planning on updating these in time, and will optimise the creation of the dictionary when this occurs.

I will need to append an example to the parameter file - https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/parameter_files/input_parameter_file_all_options.py - to make this clear to a user

**Comment by durack1** [comment]
This revisit will be done in conjunction with #317
