### ISSUE TITLE
saving out interpolated observational data

### ISSUE THREAD

**Issue by markcollier** [PCMDI/pcmdi_metrics#254]
in input_parameters.py there is an option:
save_mod_clims
for saving out the interpolated model data, it would be good to have an equivalent variable to save out the observational sets. This is very useful for validation of the metrics, something most first time users will want to be able to do.

Regards,
Mark.

**Comment by doutriaux1** [comment]
@markcollier I'm not 100% I understand, you mean saving the regridded/masked observational datasets?

**Comment by markcollier** [comment]
Yes, verification of metrics will be important before anyone will want to adopt and contribute to the system - it is important to see how the final data before the statistical routine is applied. It could also be a useful feature if analysts want to perform additional  offline work with the data. I identified a bug or typo. in the bias calculation and this was only detected through verification of the basic statistic. Regards, Mark.

**Comment by doutriaux1** [comment]
thanks @markcollier I will add this option as soon as possible.

**Comment by gleckler1** [comment]
I agree this would be useful in certain situations, especially when masking is involved, e.g., masking out reanalysis surface winds over land.
