### ISSUE TITLE
Add new obs

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#260]
Add new obs:
- [ ] CERES-EBAF surface short wave (rsds)
- [ ] CERES-EBAF surface long wave (rlds)
- [ ] CERES-EBAF surface downwelling shortwave flux in air (rsds)
- [ ] CERES-EBAF surface downwelling longwave flux in air (rlds)
- [ ] CERES-EBAF surface downwelling shortwave flux assuming clear sky (rsdscs)
- [ ] CERES-EBAF surface downwelling longwave flux assuming clear sky (rldscs)
- [ ] QuikSCAT eastward wind (uas)
- [ ] QuikSCAT northward wind (vas)

@gleckler1 can clarify the above

**Comment by durack1** [comment]
@gleckler1 rather than just assigning me, it might be useful to clarify that what's listed above is just the ticket?

**Comment by durack1** [comment]
@gleckler1 you getting these alerts?

**Comment by gleckler1** [comment]
This list is good.   PD had been assigned all along, but PG inadvertently unassigned PD as he attempted to ADD PG to the assigned... but could not figure out how to have both names assigned.   So PG put PD back in charge ;-)

**Comment by durack1** [comment]
I might assign @doutriaux1 as he's a nice chap and he likes observations..

**Comment by durack1** [comment]
I might assign @doutriaux1 as he's a nice chap and he likes observations.. He also likes passwords which don't make much sense in any tongue, either the Queens, his native, or even the local language..

**Comment by durack1** [comment]
@gleckler1 obtaining the data above from ESGF is going to require the system to be up, so I'll schedule this for mid-July..

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 and @durack1 would like you to use the `@` sign in front of our github login names `@gleckler1` which then means that we know what you're talking about (and we're pinged), PG, PD and CD doesn't help much..
