### ISSUE TITLE
Update install_metrics.bash to install CMAKE 3.2.x branch

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#262]
We're currently building cmake 2.8.12, whereas the 3.2.x branch is [now available](https://github.com/Kitware/CMake/releases) - Update to 3.2.2

**Comment by jservonnat** [comment]
@durack1 @doutriaux1 could this explain that I can't install the PMP anymore on our servers (at IPSL, not at TGCC behind those firewalls)? I've tried multiple times this week to set the PR linked with #219, with no luck. Any idea?

**Comment by durack1** [comment]
@jservonnat nope, this is not likely the problem.. What's the error..?

**Comment by jservonnat** [comment]
We are looking at it with Nicolas Carenton. When we have defined it clearly we'll get back to you.

**Comment by durack1** [comment]
I'd make sure to build `1.0`, the `master` branch is where we're currently pushing new stuff which has been tested significantly less..

**Comment by durack1** [comment]
As per discussion set `min > 2.8.12` and `max = 3.2.2`, also set `UV-CDAT 2.2.0` as `master` build point

**Comment by durack1** [comment]
@jservonnat you were most likely hitting an issue with the `UV-CDAT` installation, not the `pcmdi_metrics`.. So once the PR #269 is approved you should now be able to build again with the `PCMDI_Metrics master` and everything should work as expected
