### ISSUE TITLE
Computing metrics on T and S with Levitus at depth

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#266]
Hi guys,
we want to add metrics for the ocean temperature (to) and salinity (so) on a list of vertical levels in depth (say, 50, 100, 250, 500 and 1000m). The idea would be to do the same thing as you do on the atmospheric vertical levels, i.e. select a variable that is pre-defined on the level of interest. For example, the variable to_500 is the ocean temperature at 500m. I've slightly modified the driver to separate the atmosphere case (where you need to multiply the level by 100 to have the correct pressure level) with the ocean:
```
140     ## REGRID OBSERVATIONS AND MODEL DATA TO TARGET GRID (ATM OR OCN GRID)
141     if len(var.split("_"))>1:
142         if obs_dic[vr][obs_dic[vr]["default"]]["CMIP_CMOR_TABLE"]=="Amon":
143            level = float(var.split("_")[-1])*100.
144         if obs_dic[vr][obs_dic[vr]["default"]]["CMIP_CMOR_TABLE"]=="Omon":
145            level = float(var.split("_")[-1])
```
I've prepared the obs files (Levitus) and the package seems to be able to ingest it. In parallel, I've pre-treated our NEMO files to have to (votemper) and so (vosaline) on the 'standard' depths (50, 100...). But apparently the package doesn't like the non-regular grid. Here is the error that I get:
``` 
OBS SHAPE IS  (12, 1, 72, 144)
 auto generating sftlf for model /ccc/scratch/cont003/dsm/p86ipsl/tmp_files_for_metrics/ccc/store/cont003/dsm/p86caub/dmf_import/IGCM_OUT/IPSLCM5A/PROD/piControl/piControl2/OCE/Analyse/SE/piControl2_SE_2500_2509_1M_grid_T.nc
 Error while processing observation to for variable default:
	Error: target grid must be rectilinear
```
I've tried to run exactly the same driver for tos on the same target file (before pre-treatment) with the same grid (but in 3D, not in 4D), and it works.

Would you have an idea/suggestion to make it work? Do you think we can manage to sort this out from the package side or should I provide one x/y/time variable for each depth and variable (more than ten variables for T and S, with some not convenient practical issues...)?

By the way, I've successfully added a new variable for our land surface model (the gpp) in the suite of diagnostics. We are on the good tracks ;).

**Comment by jservonnat** [comment]
I'll re-open this issue if I can't make it on my side. It seems that it is coming from our model file.

**Comment by durack1** [comment]
@jservonnat we've got this ocean stuff on the to-do list our side too, so I think we'll be learning from one another.. With regard to ocean grids, you might be able to change the regridder to ESMF (if it's not already) which should deal with the `target grid must be rectilinear` issue, that might get you a little further along..

**Comment by jservonnat** [comment]
That's actually quite strange at the moment. It works with SST on exactly the same grid, with the same dimensions and attributes. And it doesn't work neither on this 4D setup, nor on a test with only one vertical level (to100) in a 3D file.
There are still some things to be tried before I get back at you ;). But thank you for your help!

**Comment by jservonnat** [comment]
Actually the parameter regrid_tool_ocn is set to esmf (so is regrid_tool); I've tried to set the parameter regrid_method_ocn to 'conservative' (also tried 'conserve') but it didn't change anything.

**Comment by durack1** [comment]
@jservonnat if you do an `ncdump -h` on the file that works and the file that doesn't.. Does that show some different/missing info contained in the file regarding grids.. That would be my guess with the info you've provided

**Comment by jservonnat** [comment]
@durack1 I've been through those paths but didn't find anything striking (both have the same dimensions, attributes, bounds...)

**Comment by durack1** [comment]
@jservonnat an explicit diff
```
ncdump -h file1.nc > file1.txt
ncdump -h file2.nc > file2.txt
diff file1.txt file2.txt
```
Might show you something which wasn't obvious at a glance..

I'd certainly be keen to know what the problem is here, it'd be great to figure this out and fix it!

**Comment by jservonnat** [comment]
@durack1 Here is the only difference I see at the moment:
- in the file that doesn't work:
```
  float nav_lon(y, x) ;
    nav_lon:standard_name = "longitude" ;
    nav_lon:long_name = "Longitude" ;
    nav_lon:units = "degrees_east" ;
    nav_lon:_CoordinateAxisType = "Lon" ;
    nav_lon:bounds = "lon_bnds" ;
  float nav_lat(y, x) ;
    nav_lat:standard_name = "latitude" ;
    nav_lat:long_name = "Latitude" ;
    nav_lat:units = "degrees_north" ;
    nav_lat:_CoordinateAxisType = "Lat" ;
    nav_lat:bounds = "lat_bnds" ;
```
And in the file that works:
```
  float nav_lat(y, x) ;
    nav_lat:standard_name = "latitude" ;
    nav_lat:units = "degrees_north" ;
    nav_lat:valid_min = -78.19058f ;
    nav_lat:valid_max = 89.6139f ;
    nav_lat:long_name = "Latitude" ;
    nav_lat:nav_model = "Default grid" ;
    nav_lat:bounds = "lat_bnds" ;
  float nav_lon(y, x) ;
    nav_lon:standard_name = "longitude" ;
    nav_lon:units = "degrees_east" ;
    nav_lon:valid_min = -179.7507f ;
    nav_lon:valid_max = 180.f ;
    nav_lon:long_name = "Longitude" ;
    nav_lon:nav_model = "Default grid" ;
    nav_lon:bounds = "lon_bnds" ;
```
The valid_min and valid_max attributes are missing in the file that doesn't work. I'll try that unless you think it's not worth it.

**Comment by jservonnat** [comment]
@durack1 we are getting there... this is actually due to the generation of the land-sea mask. The error comes from this line:
```
295                          sftlf[model_version]["raw"]=cdutil.generateLandSeaMask(Vr(*(slice(0,1),)*N))*100.
```
Here is the error:
```
>>> cdutil.generateLandSeaMask(Vr(*(slice(0,1),)*N))*100.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ccc/work/cont003/dsm/p86ipsl/PCMDI-MP/work_install_v2/PCMDI_METRICS/lib/python2.7/site-packages/cdutil/create_landsea_mask.py", line 182, in generateLandSeaMask
    raise Exception, "Error: target grid must be rectilinear"
Exception: Error: target grid must be rectilinear
```
Apparently the function doesn't want to generate a Land-Sea mask for a non-rectilinear grid.
Does this mean that I don't need to precise a region in the param file? i.e. like this (it is working like this):
```
regions = {"to" : [None],
                }
```
and not like that:
```
regions = {"to" : ['ocean'],
                }
```

**Comment by durack1** [comment]
@jservonnat it appears you've uncovered a long-standing issue related to the underlying metrics package modules - long story short functionality with non-rectilinear grids in `cdutil/genutil` is limited and there's an open issue https://github.com/UV-CDAT/uvcdat/issues/402 in the queue..

**Comment by jservonnat** [comment]
@durack1 so the question now is: can we compute a metric on such ocean grid without precising that you want to work only on the ocean mask? i.e., the fact that we have FillValue over land is enough?

**Comment by durack1** [comment]
@jservonnat ok so this is now a bug (I've changed the status) as this issue will recur time and time again with ocean output, I'll query @doutriaux1 on this and see what can be done.. A path forward might be to use the `ESMF` regridder to bring back to a `rectilinear` (Levitus/obs) grid before generating the mask.. We'll have to think a little about this I think..

**Comment by jservonnat** [comment]
Ok that's fine for me ;).
