### ISSUE TITLE
metrics on sftbrgn

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#268]
This requires some thought to ensure it is done properly.   Will likely require a several stage process (e.g., using land/sea mask interpolate land and ocean separately to common grid, then recombine and then identify multiple land and ocean regions). Adding this feature and getting it to work right may be complicated but its going to make the package very unique.

**Comment by jservonnat** [comment]
@gleckler1 I totally agree. I can tell you that I'm very interested in this functionnality both ocean regions and for land surfaces.

**Comment by gleckler1** [comment]
@doutriaux1  The recently added capability of selecting a "region+mask" is largely what was expected out of this issue... so closing...

**Comment by doutriaux1** [comment]
@gleckler1 it's not quite the same though but close you're right
