### ISSUE TITLE
tweak driver to allow non-climatology

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#27]
need to come up with system to tell driver which set of metrics to use (-m/-e option?)

**Comment by doutriaux1** [comment]
@gleckler1 why did you close this? You do not want this anymore?

**Comment by gleckler1** [comment]
@doutriaux1   We need to discuss strategy for PMP expansion that will include additional mean climate metrics (e.g., monsoon precip index, regional statistics) as well as inter-annual variability and high frequency analysis... will these all be driven by the same driver?   I tend to think not, except possibly for the additional analysis using climatologies (monsoon, regional,...) we may decide to add to current driver.   So to answer your question yes, this is very important, but before we get specific with a task-based issue lets talk how best to approach this - ps: part of the reason I closed this was an attempt (perhaps unwisely) to get us down to 1 page of issues (25).
