### ISSUE TITLE
output clim not masked for ocean case...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#270]
In the parameter file, we can select variables for which we want metrics on 'global', 'ocean' and 'land' case (e.g., below).   Global and ocean cases are ok, but the output.nc clims for the 'ocean' case are not masked over land.   

## REGIONS ON WHICH WE WANT TO RUN METRICS (var specific)
regions = {"tas" : [None,"land","ocean"],
           "uas" : [None,"land","ocean"],
           "vas" : [None,"land","ocean"],
            "pr" : [None,"land","ocean"],
            "psl": [None,"land","ocean",],
           "huss": [None,"land","ocean"],
            "prw": [None,"land","ocean"],

**Comment by jservonnat** [comment]
Hi there!
I also add that the 'ocean' masking doesn't work for non rectilinear grid (in my case, the ORCA grid). Have you ever met this problem?

**Comment by doutriaux1** [comment]
will add an example/test for this then.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 
Output climatologies for the land case are ok, but for the ocean case the masking is still not being saved to the output climatologies

**Comment by doutriaux1** [comment]
@gleckler1 is it working now? Or did you close by accident?

**Comment by gleckler1** [comment]
@doutriaux1  Closed by accident!  Still not working

**Comment by doutriaux1** [comment]
Darn! was too good to be true!

**Comment by durack1** [comment]
@doutriaux1 maybe you could hijack @gleckler1's keyboard so that these things are "accidentally" closed more often.. No more "TOPPRIORITY" tags or anything..

**Comment by gleckler1** [comment]
@doutriaux1 does not appear to be fixed....

**Comment by doutriaux1** [comment]
@gleckler1 did you try this branch?
