### ISSUE TITLE
Defining a 1.0x1.0 common grid: issues with targetGridName

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#271]
I would like to add some metrics for the mixed layer depth in our suite of metrics at IPSL. For this, and to avoid smoothing of the results (particularly in the deep convection areas), I would like to define a 1°x1° common target grid (rather than the 2.5x2.5 grid).
I did this easily by setting the parameter targetGrid to a cdms grid object as explained in the parameter file:

```
targetGrid        = cdms2.createUniformGrid(-89,179,1,0,360,1)
```

The metrics are computed and the remapping seems to work, but there is an error at the end:

```
 No mask for  /ccc/scratch/cont003/dsm/p86ipsl/tmp_files_for_metrics/ccc/store/cont003/dsm/p86caub/dmf_import/IGCM_OUT/IPSLCM5A/PROD/piControl/piControl2/OCE/Analyse/SE/piControl2_SE_2500_2509_1M_grid_T.nc
 parameter file ref is:  default
 ref is:  ['default']
/ccc/work/cont003/dsm/p86ipsl/PCMDI-MP/work_install_v2/PCMDI_METRICS/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1241: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (srcMaskValues != None):
/ccc/work/cont003/dsm/p86ipsl/PCMDI-MP/work_install_v2/PCMDI_METRICS/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (dstMaskValues != None):
 OBS SHAPE IS  (12, 179, 360)
 mldpd   IPSLCM5A   (12, 179, 360)   (12, 179, 360)    default
/ccc/work/cont003/dsm/p86ipsl/PCMDI-MP/work_install_v2.12/PCMDI_METRICS/bin/pcmdi_metrics_driver.py:331: UserWarning: Model and observation units differed, converted model (m) to observation unit (meters) scaling: 1 offset: 0
  warnings.warn("Model and observation units differed, converted model (%s) to observation unit (%s) scaling: %g offset: %g" % (dm.units,do.units,scaling,offset))
---- shapes  GLB     (12, 179, 360)   (12, 179, 360)
/ccc/work/cont003/dsm/p86ipsl/PCMDI-MP/work_install_v2/PCMDI_METRICS/lib/python2.7/site-packages/numpy/ma/core.py:935: RuntimeWarning: overflow encountered in multiply
  result = self.f(da, db, *args, **kwargs)
mldpd    annual mean bias is  1.22590120646
---- shapes  NHEX     (12, 60, 360)   (12, 60, 360)
mldpd    annual mean bias is  3.13896921168
---- shapes  TROPICS     (12, 61, 360)   (12, 61, 360)
mldpd    annual mean bias is  1.24714685537
---- shapes  SHEX     (12, 60, 360)   (12, 60, 360)
mldpd    annual mean bias is  -0.569248861596
 Error while processing variable mldpd:
    expected a character buffer object
```

This comes from the fact that we pass a cdms grid to targetGrid, and not a character chain like '2.5x2.5'. In io/base.py, there is the mechanism to 'link' a grid name '2.5x2.5' with a cdms grid. But if you set targetGrid to a cdms object, you will have the regridding working but you will also have a 'targetGridName' set to a cdms object. I've tried to set targetGridName within the driver like this:
- first, add this to the parameter file:

```
targetGridName = '1.0x1.0'
```
- then, modify the driver accordingly like this:

```
if parameters.targetGrid == "2.5x2.5":
  tGrid = cdms2.createUniformGrid(-88.875,72,2.5,0,144,2.5)
  targetGridName = parameters.targetGrid
else:
  tGrid = parameters.targetGrid
  targetGridName = parameters.targetGridName
```

But this is actually not enough because of this line:

```
OUT.setTargetGrid(parameters.targetGrid,regridTool,regridMethod)
```

It works if you add this just below:

```
OUT.targetGridName = targetGridName
```

i.e. it overwrites the targetGridName with the OUT object that is set via the function setTargetGrid.

So first question: am I using correctly the parameter file and driver? i.e., my problem is due to a real limitation of the package or because I'm not using it properly to set a common target grid that is different from a '2.5x2.5' grid?
If there is a true limitation, let me know if you want me to setup a PR or if you prefer to handle it on your side.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @jservonnat  I will take a look at this, but its probably a question for Charles to investigate.   However, I can say that at present we predefine several target resolutions so that we can just provide results from other models and don't have to provide the actual model climatologies.  We will work away from this but not quite yet.   That said, I don't know why you would not be able to do your calculations on another grid.   Have you tried running a common variable like 'rlut'  at 1x1?

**Comment by durack1** [comment]
@doutriaux1 how hard will it be to generalize this so that we determine the highest obs resolution then use this obs target resolution to generate metrics? This could be a useful expansion for circa 2.0 version metrics

**Comment by jservonnat** [comment]
@gleckler1 the calculations actually worked when I added my little fix in the parameter file and the driver.
Today the bug is that in the parameter file, you can set targetGrid to '2.5x2.5' or to a cdms grid object. The problem is if you pass a cdms grid object to targetGrid: at some point, the driver and the setTargetGrid function will need a character chain as a grid name to store the informations in the json file correctly. This is why I came out with this fix.
@durack1 that would be a very interesting option too. Also, allowing the calculations on the native grid (i.e. switch off the regridding) would be great to compute quantities on sea ice or mixed layer depth (among others). But that might be out of the scope of the metrics package.

**Comment by durack1** [comment]
@jservonnat native grid stuff isn't going to work, as to generate the fields you need to be on the same `x,y` grids for both the model and the provided baseline obs - we're thinking multi-model here which is a different perspective to you currently.. @gleckler1 has some pretty strong views on this stuff, so will let him pipe in..
