### ISSUE TITLE
Adding Standard Deviation as Standard Metrics ?

### ISSUE THREAD

**Issue by zhang40** [PCMDI/pcmdi_metrics#272]
Hi, I just installed and have the metrics package running. Thanks to Charles and Paul. 
Charles showed me how to create customer metrics for calculating standard deviation. It would be nice to include std in the new release. Because for monthly statistics, with std we can easily generate Taylor Diagram similar to Figure 1 in Gleckler et al. 2008 :)

Thanks,
Jill

**Comment by gleckler1** [comment]
Good idea!  I'm on travel and will say more about this later @zhang40

**Comment by gleckler1** [comment]
@doutriaux1 See pull request.
