### ISSUE TITLE
Fix test suite errors

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#277]
The following issues are occurring due the `test_suite.py` run in the current master branch:
```
1:
failed with 4D OBS tas alternate1 Cannot open file /export/durack1/150901_pcmdi_metrics/PCMDI_METRICS/tmp/metrics/test/pcmdi/obs/atm/mo/tas/ERA40/ac/tas_pcmdi-metrics_Amon_ERA40_195709-200208-clim.nc (Variable not found) 

Which is related to non-existent test data – we need to fix this

2:
Error while processing variable aVarThatIsNot:                                                                                      
       'aVarThatIsNot'

Not sure where this is coming from – I’ll have to probe Charles on this, it doesn’t appear to be in the pcmdi_metrics source…

And 3:
Error while processing variable tas:                                                                                                
       not all arguments converted during string formatting 
```

**Comment by doutriaux1** [comment]
@durack1 is the test suite reporting an error? Some test are actually expected to fail and recover hence some messages about errors, but again the test is to see how we recover from this. You should only focus on the test suite report at the end.

**Comment by durack1** [comment]
@doutriaux1 looks to me like we still have [errors on the travis builds](https://travis-ci.org/PCMDI/pcmdi_metrics/builds) and the last time I checked it was due to test errors.. I haven't looked at this for a while though..
