### ISSUE TITLE
New issues with installing the package behing a firewall

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#278]
@doutriaux1 @durack1 I'm having new issues when trying to install the MP at TGCC on our computing center (behind a firewall).
Until now, we've overcome the problem of downloading all the tar files by:
- launching the install script until it stops (when it tries to download the tar files)
- then, copying the tar files in tmp/uvcdat/uvcdat_build
- and re-launch the install_metrics script

But now, the installation wants to 'git clone' two repo: libcdms and uvcdat-testdata.
I've done a clone of those repo at IPSL (as we do for cmake, uvcdat and the source of the MP). But if I modify directly tmp/uvcdat/uvcdat_build/libcdms-prefix/tmp/libcdms-gitclone.cmake accordingly (replacing  git://github.com/UV-CDAT/libcdms.git by igcmg@ciclad.ipsl.jussieu.fr:/home/igcmg/PCMDI-MP/libcdms) the file is then overwritten when I relaunch the install_metrics script. Same if I do directly the git clone in the tree to get the sources for libcdms and uvcdat-testdata.
Can you tell me where I can change the github address (for our igcmg@ciclad address) upstream in the sources to get libcdms and uvcdat-testdata?

**Comment by durack1** [comment]
@jservonnat this is a good test case, which we have dealt with before.. I'm pinging @doutriaux1 as he's more familiar with getting around these issues than I am..

Once we have a path forward, we should document the additional steps on the [Wiki install page](https://github.com/PCMDI/pcmdi_metrics/wiki/Install)

**Comment by jservonnat** [comment]
Great, thank you @durack1 !

**Comment by doutriaux1** [comment]
@jservonnat go to your temp/uvcdat/uvcdat directory that's where the sources used for building sit. also you might  need to tell it to not remove the build directory: https://github.com/PCMDI/pcmdi_metrics/blob/master/install_metrics.bash#L9

**Comment by jservonnat** [comment]
@doutriaux1 this is what I do actually; the problem is that I didn't find the mean to by the downloading of libcdms. I can't just copy the libcdms-prefix directory from a working installation because it is already a build with the paths of the installation. And if I modify libcdms-download to point at my igcmg@... adress, it is overwritten when I rerun the install script.
If you have another solution so I can get libcdms (even by downloading it by hand in uvcdat_build) I'll take it ;).

**Comment by doutriaux1** [comment]
edit the file in the tmp directory once it's cloned it will not be overwritten. (you may have to comment out the line that remove the clone)

**Comment by jservonnat** [comment]
@doutriaux1 just to let you know it is working now, with the classical protocole to install the package behind a firewall (copying the tar files by hand).
