### ISSUE TITLE
clim_code error

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#283]
@doutriaux1 @durack1 First attempts trying to get the clim code working... it is bombing on data that should work (CMIP5 data and other obs data written by CMOR.    I have cp'ed the CMIP5_Amon table to pcmdi_metrics which the code expects ... several examples of failure below.... pls help ...

**
/export/gleckler1/git/pcmdi_metrics/src/python/pcmdi/scripts/pcmdi_compute_climatologies.py -f /clim_obs/obs/atm/mo/rlut/CERES/rlut_CERES-EBAF_L3B_Ed2-6r_200003-201206.nc -v rlut

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                               !
! Error: axis time2 has values not within bounds at indice: 0: 2146.500000 not within: 2466.000000, 2556.000000 !
!                                                                                                               !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

----------------------------------------------------------------------------------------------------

/export/gleckler1/git/pcmdi_metrics/src/python/pcmdi/scripts/pcmdi_compute_climatologies.py -f /work/cmip5/historical/atm/mo/rlut/cmip5.MIROC4h.historical.r1i1p1.mo.atm.Amon.rlut.ver-1.latestX.xml -v rlut

We found data from  0.00 days since 1950-1-1 to 20454.00 days since 1950-1-1 MID YEAR: 1978
T: 0-1-15 12:0:0.0 14.5
/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)

C Traceback:
In function: cmor_check_values_inside_bounds
called from: cmor_axis

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                  !
! Error: axis time2 has values not within bounds at indice: 0: 10241.500000 not within: 10561.000000, 10651.000000 !
!                                                                                                                  !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by durack1** [comment]
@gleckler1 I think this is a @doutriaux1 query.. Where is the `time2` axis coming from, it would seem to be from within cmor..

**Comment by doutriaux1** [comment]
Let me check, I think we actually a special branch of CMOR

**Comment by doutriaux1** [comment]
ok I can reproduce, I'm on it.

**Comment by doutriaux1** [comment]
@gleckler1 try again with:
```
pcmdi_compute_climatologies.py -f /clim_obs/obs/atm/mo/rlut/CERES/rlut_CERES-EBAF_L3B_Ed2-6r_200003-201206.nc -v rlut -X '{"positive":"down"}'
```

BUT it still fails because @gleckler1 and @durack1 need to fine tune the table we distribute in `share/pcmdi_metric_table` even possibly renaming it

**Comment by doutriaux1** [comment]
@gleckler1 don't forget to pull and update your installation to get my changes.

**Comment by durack1** [comment]
@doutriaux1 I have no idea what tweaks/how this table is being used.. We'll have to chat about this on Monday..

**Comment by gleckler1** [comment]
Got your changes.   Progress.   But its not making it through yet.   Getting an error (below) that the 'positive' argument is not provided... but it is there in share/pcmdi_metric_table for variable rlut

C Traceback:
In function: cmor_variable
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                    !
! Error: you did not provide the 'positive' argument for variable: rlut (table Amon) !
!                                                                                    !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 

Got your changes. Progress. But its not making it through yet. Getting an error (below) that the 'positive' argument is not provided... but it is there in share/pcmdi_metric_table for variable rlut

C Traceback:
In function: cmor_variable
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! !
! Error: you did not provide the 'positive' argument for variable: rlut (table Amon) !
! !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  This one does not appear related to the table....

/export/gleckler1/git/pcmdi_metrics/src/python/pcmdi/scripts/pcmdi_compute_climatologies.py -f /clim_obs/obs/atm/mo/pr/GPCP/pr_GPCP_197901-200909.nc -v pr
DATA: (369, 72, 144) 1979-1-16 12:0:0.0 2009-9-16 0:0:0.0

-16 12:0:0.0, 2008-8-16 12:0:0.0, 2008-9-16 0:0:0.0, 2008-10-16 12:0:0.0, 2008-11-16 0:0:0.0, 2008-12-16 12:0:0.0, 2009-1-16 12:0:0.0, 2009-2-15 0:0:0.0, 2009-3-16 12:0:0.0, 2009-4-16 0:0:0.0, 2009-5-16 12:0:0.0, 2009-6-16 0:0:0.0, 2009-7-16 12:0:0.0, 2009-8-16 12:0:0.0, 2009-9-16 0:0:0.0]
We found data from  10592.00 days since 1950 to 21823.00 days since 1950 MID YEAR: 1994
T: 0-1-15 12:0:0.0 14.5
BOUNDS 2: 1993-12-1 0:0:0.0 1994-3-1 0:0:0.0
Traceback (most recent call last):
  File "/export/gleckler1/git/pcmdi_metrics/src/python/pcmdi/scripts/pcmdi_compute_climatologies.py", line 328, in <module>
    **xtra
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/cmor/pywrapper.py", line 793, in dataset
    raise Exception, "Error argument %s must be an integer" % o
Exception: Error argument i must be an integer
[gleckler1@oceanonly clim_test]$

**Comment by doutriaux1** [comment]
@gleckler1 I posted the command line that provides the positive argument above.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 Got the climo script to partially execute, but not yet producing expected/completed results....  1) it is producing 4 seasonal climatologies but not for the right period (198312-198402, when is should be a 10 year period), and 2) it bombs before completing, so we don't have the full annual cycle clim or annual mean clim. 

pcmdi_compute_climatologies.py -f /work/cmip5/historical/atm/mo/rlut/cmip5.CESM1-CAM5.historical.r1i1p1.mo.atm.Amon.rlut.ver-v20120608.latestX.xml -v rlut -X '{"positive":"down"}' -s 1979-01 -e 1989-12

We found data from  47054.00 days since 1850-01-01 00:00:00 to 51069.00 days since 1850-01-01 00:00:00 MID YEAR: 1984
T: 0-7-2 12:0:0.0 182.5
BOUNDS 2: 1984-1-1 0:0:0.0 1984-1-1 0:0:0.0
C Traceback:
In function: cmor_check_values_inside_bounds
called from: cmor_axis
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                  !
! Error: axis time2 has values not within bounds at indice: 0: 49092.500000 not within: 48910.000000, 48910.000000 !
!                                                                                                                  !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by doutriaux1** [comment]
ok will tweak the "bounds magic" a little further.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 Progress!!!   
Code is running to completion,  but the start-end dates in the output files are wrong (below).
Also, after the date in the output file name the season should be included as part of the file name (DJF, MAM, JJA, SON, ANN)


pcmdi_compute_climatologies.py -f /work/cmip5/historical/atm/mo/rlut/cmip5.CESM1-CAM5.historical.r1i1p1.mo.atm.Amon.rlut.ver-v20120608.latestX.xml -v rlut -X '{"positive":"down"}' -s 1979-01 -e 1989-12

 ls -lrt
total 3556
-rw------- 1 gleckler1 climate  241180 Nov 12 15:05 rlut_Amon_CESM1-CAM5_historical_r1i1p1_198312-198402-clim.nc
-rw------- 1 gleckler1 climate  241180 Nov 12 15:05 rlut_Amon_CESM1-CAM5_historical_r1i1p1_198403-198405-clim.nc
-rw------- 1 gleckler1 climate  241180 Nov 12 15:05 rlut_Amon_CESM1-CAM5_historical_r1i1p1_198406-198408-clim.nc
-rw------- 1 gleckler1 climate  241180 Nov 12 15:05 rlut_Amon_CESM1-CAM5_historical_r1i1p1_198409-198411-clim.nc
-rw------- 1 gleckler1 climate 2674468 Nov 12 15:05 rlut_Amon_CESM1-CAM5_historical_r1i1p1_198401-198412-clim.nc

**Comment by durack1** [comment]
@gleckler1 ok great, so it's time I start testing this out on 3D ocean fields then..?

**Comment by doutriaux1** [comment]
oh yes. I will fix that in just a moment, do frequent `git pull` in case I forget to notify you about this being fixed :smile:

**Comment by gleckler1** [comment]
I'm back.  @doutriaux1 @durack1 
Got the latest on the climo script (I think).   Its producing files, but the start and end dates on the file names are wrong (using the year in the middle of the period).... For example,  

pcmdi_compute_climatologies.py -f /work/cmip5/historical/atm/mo/rlut/cmip5.CESM1-CAM5.historical.r1i1p1.mo.atm.Amon.rlut.ver-v20120608.latestX.xml -v rlut -X '{"positive":"down"}' -s 1979-01 -e 1989-12 -T pcmdi_metrics

Should produce a file with name
rlut_Amon_CESM1-CAM5_historical_r1i1p1_198401-198412-clim.nc
but instead produces
rlut_Amon_CESM1-CAM5_historical_r1i1p1_197901-198912-clim.nc

**Comment by gleckler1** [comment]
@doutriaux1 @durack1
Correction... I had that reversed..... it should read

It outputs a file with name
rlut_Amon_CESM1-CAM5_historical_r1i1p1_198401-198412-clim.nc
but it should be
rlut_Amon_CESM1-CAM5_historical_r1i1p1_197901-198912-clim.nc

**Comment by durack1** [comment]
@doutriaux1 @gleckler1 should we create a new label `glecklerError`?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 Also needs command line option for setting output path which is currently hardwired for directory "Test"

**Comment by gleckler1** [comment]
Just worked out with Karl... to be consistent with CMIP6....
"clim" should be replaced with "clim-ac", "clim-djf", "clim-mam","clim-jja", "clim-son"

**Comment by gleckler1** [comment]
In summary:
1) Start and end year in filename needs to be fixed to reflect start and end clim period
2) Append "-ac", "-djf", "-mam", "-jja" and "-son" to "clim" accordingly
3) Enable outpath as a command line option (i.e., remove hardwire to "./Test")
