### ISSUE TITLE
matplotlib graphics option for build

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#284]
@doutriaux1 @durack1 We need to add matplotlib as an option for the build.   Better to keep this as a separate option to vcs, e.g., graphics_vcs = True;  graphics_matplotlib = True

**Comment by doutriaux1** [comment]
they both come together in the build, there's no way in UV-CDAT at the moment to build "just matplotlib"

**Comment by doutriaux1** [comment]
matplotlib triggers even more dependencies than vcs anyway.

**Comment by durack1** [comment]
@gleckler1 the relevant build options that are currently available are documented [here](https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options). I thought that there was a `matplotlib` specific flag, but there doesn't appear to be (any more).

@doutriaux1 it would seem that even when we build with `build_graphics=true` we're not getting `matplotlib`:
```
[durack1@oceanonly ~/150626_pcmdi_metrics_mesa]$ source PCMDI_METRICS/bin/setup_runtime.csh
Successfully updated your environment to use UVCDAT
(changes are valid for this session/terminal only)
Version: 2.2.0
Location: /export/durack1/150626_pcmdi_metrics_mesa/PCMDI_METRICS
[durack1@oceanonly ~/150626_pcmdi_metrics_mesa]$ python
Python 2.7.9 (default, Jun 26 2015, 14:42:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named matplotlib
```

**Comment by doutriaux1** [comment]
@durack1 probably because we are still pointing to 2.2.0 we should update the tag point for uvcdat.

**Comment by durack1** [comment]
@doutriaux1 let's do this for the next release.. We need to get a new release out fairly soon.. @gleckler1 can specify what is needed and when..

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  My understanding was that this was "easy and already done" ... it would be very helpful to have this ASAP, not "next release" which we have not defined yet....

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 when the new metrics version is tagged, we can align this with the upcoming `UV-CDAT 2.4.0` we'll get both `vcs` and `matplotlib` when `build_graphics=true`
