### ISSUE TITLE
Portrait broken

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#296]
This comes from a code that used to work....  

python -i test_portrait-4seas_02102016.py
/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
Traceback (most recent call last):
  File "test_portrait-4seas_02102016.py", line 199, in <module>
    P.plot(out1_rel,x=x,multiple=1.1,bg=1)
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/pcmdi_metrics/graphics/portraits.py", line 983, in plot
    x.plot(MV2.ravel(data), M, template, meshfill, bg=bg)
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/Canvas.py", line 2424, in plot
    a = self.__plot(arglist, keyargs)
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/Canvas.py", line 3747, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/VTKPlots.py", line 528, in plot
    vtk_backend_grid, vtk_backend_geo))
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 288, in plot
    self._createMaskedDataMapper()
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 333, in _createMaskedDataMapper
    deep=False)
  File "/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 115, in putMaskOnVTKGrid
    vtkmask.SetNumberOfTuples(attributes2.GetPedigreeIds().GetNumberOfTuples())
AttributeError: 'NoneType' object has no attribute 'GetNumberOfTuples'

**Comment by gleckler1** [comment]
Code location is /export/gleckler1/processing/metrics_package/my_test/portrait/test_portrait-4seas_02102016.py

**Comment by durack1** [comment]
@gleckler1 commit the code into a new `Pete` or whatever, just not the usual cr*p name - that way @doutriaux1 can get to it very easily..

**Comment by doutriaux1** [comment]
@gleckler1 it's a known bug in vcs, I have Kitware working on it. Should be fixed within a week.

**Comment by doutriaux1** [comment]
@durack1 @gleckler1 bug is fixed and in master. I tested Portrait test and it passes.

**Comment by durack1** [comment]
@doutriaux1 hold your horses.. If you check your inbox you'll see that @gleckler1 has hit a problem..

**Comment by doutriaux1** [comment]
@durack1 I think @gleckler1 is using an older branch, the test passes for me off the climo_script branch which is the one that should really be merged quickly into master. But I don't mind keeping this open until we figured out what's wrong with @gleckler1 test.

**Comment by gleckler1** [comment]
@doutriaux1 ... here is the latest....
![crap](https://cloud.githubusercontent.com/assets/4553389/13092712/5cb5d500-d4b6-11e5-8a5b-cb45f8941e19.png)

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 ... does the test suite do 4 triangles?

**Comment by durack1** [comment]
@gleckler1 take a peek at https://github.com/PCMDI/pcmdi_metrics/blob/master/test/graphics/testPortrait.png

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 
Works for fine for cases 1 and 2 but not 3 and 4, ie.:
P.plot(out1_rel,bg=1,x=x)
and
P.plot(out1_rel,x=x,multiple=1.2,bg=1)
P.plot(out2_rel,x=x,multiple=2.2,bg=1)
are good but craps out on:

P.plot(out1_rel,x=x,multiple=1.3,bg=1)
P.plot(out2_rel,x=x,multiple=2.3,bg=1)
P.plot(out3_rel,x=x,multiple=3.3,bg=1)
and
P.plot(out1_rel,x=x,multiple=1.4,bg=1)
P.plot(out2_rel,x=x,multiple=2.4,bg=1)
P.plot(out3_rel,x=x,multiple=3.4,bg=1)
P.plot(out3_rel,x=x,multiple=4.4,bg=1)

**Comment by gleckler1** [comment]
looks like no triangles in test suite....

**Comment by durack1** [comment]
@gleckler1 yep, so it would be good to drop this more complex portrait plot into the test suite so we catch any problems "automagically" in the future.. I'm sure @doutriaux1 was planning on that anyway..

**Comment by gleckler1** [comment]
@doutriaux1 Just tried with branch issue_270_ocn_clim and here is confirmation 3 and 4 triangle portraits are not working...

**Comment by durack1** [comment]
@doutriaux1 if you're convinced that #287, #295 and #297 are good to go I'm happy to merge these so we're not holding up progress.. My only concern is that all 3 are reporting travis failures..

**Comment by gleckler1** [comment]
@doutriaux1 voila z code...

[test_portrait-4seas-feb16.py.TXT](https://github.com/PCMDI/pcmdi_metrics/files/135233/test_portrait-4seas-feb16.py.TXT)

**Comment by doutriaux1** [comment]
fixed by https://github.com/UV-CDAT/uvcdat/pull/1855

**Comment by durack1** [comment]
@gleckler1 it'd be good if you can rebuild the latest (a new install should pull in changes from UV-CDAT master) and voila!
