### ISSUE TITLE
setup.py install problems...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#298]
Not sure what the implications or fix are for this...

python setup.py install
running install
running build
running build_py
copying src/python/__init__.py -> build/lib/pcmdi_metrics
copying src/python/version.py -> build/lib/pcmdi_metrics
copying src/python/io/__init__.py -> build/lib/pcmdi_metrics/io
copying src/python/io/base.py -> build/lib/pcmdi_metrics/io
copying src/python/pcmdi/seasonal_mean.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/__init__.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/meanabs_xy.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/annual_mean.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/io.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/rms_xy.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/bias.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/mean_climate_metrics_calculations.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/cor_xyt.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/rms_xyt.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/pcmdi/cor_xy.py -> build/lib/pcmdi_metrics/pcmdi
copying src/python/graphics/__init__.py -> build/lib/pcmdi_metrics/graphics
copying src/python/graphics/portraits.py -> build/lib/pcmdi_metrics/graphics
running build_scripts
creating build/scripts-2.6
copying and adjusting src/python/pcmdi/scripts/pcmdi_metrics_driver.py -> build/scripts-2.6
changing mode of build/scripts-2.6/pcmdi_metrics_driver.py from 600 to 755
running install_lib
creating /usr/lib/python2.6/site-packages/pcmdi_metrics
**error: could not create '/usr/lib/python2.6/site-packages/pcmdi_metrics': Permission denied**
[gleckler1@oceanonly pcmdi_metrics]$

**Comment by durack1** [comment]
@gleckler1 that makes sense when you are trying to install into the `/usr/lib/` directory using the system `Python2.6` and not the `Python2.7` that we've been using for UV-CDAT for the last couple of years..

Make sure you run `setup_runtime.csh` BEFORE you try and install..

And use the option:
```python
source /usr/local/uvcdat/2016-02-04/bin/setup_runtime.csh
...
> python setup.py install --user
```

Closing as a `gleckler-error` (as coined by @doutriaux1)
