### ISSUE TITLE
create development space

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#299]
At some level in the src directory tree we need a devel subdirectory or something like that.   In here, we will have sub directories and will get various metrics codes working on CMIP5 data (e.g., monsoon onset, variability, etc) that are developed by climate scientists and will at some point be better integrated into the package...

**Comment by durack1** [comment]
@gleckler1 propose something in a PR that we (@doutriaux1 and I) can comment on..

**Comment by gleckler1** [comment]
@durack1 Creation of this PR follows a f2f with C... he understands what this means and just wanted an issue because he has ideas on soln

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 
I did a git checkout -b 299_create_dev_space
Then a git pull
my git status was then on an updated branch 299_create_dev_space as expected
I went to /export/gleckler1/git/pcmdi_metrics/src/python and there was no directory devel so I created it.
I then tried 
[gleckler1@oceanonly pcmdi_metrics]$ python setup.py install --enable-devel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --enable-devel not recognized

**Comment by durack1** [comment]
@gleckler1 out of curiosity did you
```
> /PATH/TO/UVCDATINSTALL/bin/setup_runtime.csh
```
Before you executed the `python setup.py` command?

**Comment by gleckler1** [comment]
@durack1  OUI

**Comment by durack1** [comment]
@gleckler1 geez, you're starting to get good at this `git` stuff.. Next I'll be coming to you for tips..

**Comment by doutriaux1** [comment]
welll it's there: https://github.com/PCMDI/pcmdi_metrics/tree/299_create_dev_space/src/python/devel/example_dev

**Comment by doutriaux1** [comment]
@gleckler1 you probably did a `git checkout -b` **BEFORE** you pulled hence you created a new branch...

If you want to checkout a **new** branch use `-b` but if you want to checkout an existing branch drop the `-b`

So for now do:
```
git checkout master
git branch -D 299_create_dev_space
git pull
git checkout 299_create_dev_space
```

Voila.

**Comment by gleckler1** [comment]
@doutriaux1 Indeed I did.   Never used "git branch -D" before.
I trust I can make pull requests to this branch even though you are owner?

**Comment by gleckler1** [comment]
@doutriaux1 OK I see it.   If I understand correctly, for now if I want to create a new devel project I need to do it from 299_create_dev_space because that branch has not yet been pulled into master... is that correct?

**Comment by doutriaux1** [comment]
nope, let's sit together, see what's missing in this branch, merge it and then have you start off of master.

**Comment by gleckler1** [comment]
@doutriaux1 Please merge with master now so I can give it a try and we can discuss my first steps next week.  Every day counts right now need to be moving forward.  thanks p

**Comment by doutriaux1** [comment]
done

**Comment by gleckler1** [comment]
@doutriaux1 getting close.   I still have git checkout 299_create_dev_space locally (altho you have merged with master) and when I check out this branch it works fine when I run
python setup.py install --enable-devel
However, when I checkout master and try 
python setup.py install --enable-devel
the --enable-devel option is not recognized (below)
My impression from your #fix 299 is that it should now work on master - do I have that right?
In attempt to get it working I just did a rebuild on oceanonly and but --enbable-devel is still not working on master.   

python setup.py install --enable-devel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

**Comment by doutriaux1** [comment]
it's in master, you probably need:
```
git checkout master
git pull
```

**Comment by gleckler1** [comment]
[gleckler1@oceanonly pcmdi_metrics]$ which python
/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/bin/python
[gleckler1@oceanonly pcmdi_metrics]$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/python/version.py
nothing added to commit but untracked files present (use "git add" to track)
[gleckler1@oceanonly pcmdi_metrics]$ python setup.py install --enable-devel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --enable-devel not recognized

**Comment by doutriaux1** [comment]
did you run `git pull` while on branch `master` ?

**Comment by gleckler1** [comment]
@doutriaux1 OUI

**Comment by gleckler1** [comment]
@doutriaux1 
gleckler1@oceanonly pcmdi_metrics]$ which python
/export/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/bin/python
[gleckler1@oceanonly pcmdi_metrics]$ git status
On branch master
Untracked files:
(use "git add ..." to include in what will be committed)
src/python/version.py
nothing added to commit but untracked files present (use "git add" to track)
[gleckler1@oceanonly pcmdi_metrics]$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details
    git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=origin/<branch> master

[gleckler1@oceanonly pcmdi_metrics]$ python setup.py install --enable-devel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --enable-devel not recognized
[gleckler1@oceanonly pcmdi_metrics]$

**Comment by doutriaux1** [comment]
@gleckler1 per your error message:
```
 There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details
git pull
If you wish to set tracking information for this branch you can do so with:
git branch --set-upstream-to=origin/ master
```

So no you're not really on master...

do as git tells you:
```
git branch --set-upstream-to=origin/ master
git pull
```
code is in see:
git branch --set-upstream-to=origin/ master
