### ISSUE TITLE
Climatology production in /devel

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#306]

**Comment by doutriaux1** [comment]
Ah! Got your master branch going I guess :wink:

**Comment by gleckler1** [comment]
@durack1 Have added branch 306_pjg_climproduction_indevel
which includes a code to create model clims using cmor and an (ATM only so far) CMOR table.   Everything hardwired so far.   Lets talk about using argparse to set parameters from command line and including logging.

**Comment by durack1** [comment]
@gleckler1 want to propose this in a PR? That way it'll be easy to see what you have done, the "Files changed" tab (e.g. https://github.com/PCMDI/pcmdi_metrics/pull/301) makes that really easy..

**Comment by gleckler1** [comment]
@durack1 Not ready for master, why not just use the branch I created? 306_pjg_climproduction_indevel

**Comment by durack1** [comment]
@gleckler1 you can submit it as a pull request, but just prefix with [WIP] (work in progress) so we can see it in the queue, but not merge until we're happy with it.. You can continue to commit and push changes into the branch while it's a pull request..

**Comment by durack1** [comment]
@gleckler1 https://github.com/PCMDI/pcmdi_metrics/pull/308 - here's the pull request - with [WIP] prefix
