### ISSUE TITLE
Master build failing (Linux and OS X 10.11)

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#307]
Failed attempt to build on oceanonly... log attached

[build_log.oceanonly.02022016.txt](https://github.com/PCMDI/pcmdi_metrics/files/155705/build_log.oceanonly.02022016.txt)

**Comment by durack1** [comment]
@gleckler1 my quick test lead to the following error:
```
  /export/durack1/160302_pcmdi_metrics/PCMDI_METRICS/lib/python2.7/site-packages/MyProxyClient-1.3.0-py2.7.egg
  Processing dependencies for MyProxyClient==1.3.0
  Searching for cryptography>=0.7
  Reading https://pypi.python.org/simple/cryptography/
  Couldn't retrieve index page for 'cryptography'
  Scanning index of all packages (this may take a while)
  Reading https://pypi.python.org/simple/
  -------------------------------------------------
   From /export/durack1/160302_pcmdi_metrics/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/MyProxyClient-prefix/src/MyProxyClient-stamp/MyProxyClient-install-err.log                                                                                                           
  -------------------------------------------------
  Download error on https://pypi.python.org/simple/cryptography/: [SSL:
  CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some
  packages may not be found!
  Download error on https://pypi.python.org/simple/: [SSL:
  CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some
  packages may not be found!
  No local packages or download links found for cryptography>=0.7
  error: Could not find suitable distribution for
  Requirement.parse('cryptography>=0.7')
```

It's (almost) fixed in https://github.com/UV-CDAT/uvcdat/pull/1840 - I'm not sure what the status of this is, it's passing all the `travis` tests that I have seen.. Not certain about what's happening with the `mac-bots`.. @doutriaux1?

**Comment by doutriaux1** [comment]
@gleckler1 please try again, the latest changes in UV-CDAT/uvcdat#1840 should have fix this.

**Comment by durack1** [comment]
@doutriaux1 ok great, this fixes my issues for the `pcmdi_metrics` - you might want to ping Matthias to try again with the master branch..

**Comment by gleckler1** [comment]
@doutriaux1 
[build_log.oceanonly.02032016.txt](https://github.com/PCMDI/pcmdi_metrics/files/157283/build_log.oceanonly.02032016.txt)

**Comment by durack1** [comment]
@gleckler1 add:
```
setenv PATH "$PATH:/export/durack1/bin/downloads/cmake3.2.2/150422_build/bin"
```
Into the top of your `install_metrics.bash` - this will isolate if it's a `CMake` issue..

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 
Can't build on crunchy either.   Looks like a different issue.   I must be doing something wrong...
[build_log.crunchy.02032016.txt](https://github.com/PCMDI/pcmdi_metrics/files/157355/build_log.crunchy.02032016.txt)

**Comment by doutriaux1** [comment]
I'm coming to your office

**Comment by gleckler1** [comment]
@doutriaux1 @durack1   The cmake update on oceanonly needs also to be on crunchy where build is still failing....

Your branch is up-to-date with 'origin/master'.
removing UVCDAT build directory
LEAN MODE will not build graphics
CMAKE ARGS: cmake /export_backup/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/tmp/uvcdat/uvcdat -DCDAT_BUILD_MODE=LEAN -DCDAT_BUILD_ESMF_ESMP=ON -DCMAKE_INSTALL_PREFIX=/export_backup/gleckler1/METRICS_PACKAGE/PCMDI_METRICS -DZLIB_PATCH_SRC=3 -DGIT_PROTOCOL=git://
PATH:/export_backup/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/Externals/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin
PWD:/export_backup/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/tmp/uvcdat/uvcdat_build
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/export_backup/gleckler1/METRICS_PACKAGE/PCMDI_METRICS/Externals/bin
CMake Error: Error executing cmake::LoadCache(). Aborting.

 ERROR: Could not configure (cmake) cdat code (2)
~/METRICS_PACKAGE/PCMDI_METRICS/tmp/uvcdat/uvcdat ~/METRICS_PACKAGE/PCMDI_METRICS/tmp/metrics

Sorry...
This action did not complete successfully
Please try to re-run this task until successful before continuing further

 ERROR: Could not compile (make) cdat code
~/METRICS_PACKAGE/PCMDI_METRICS/tmp/metrics

Sorry...
This action did not complete successfully
Please try to re-run this task until successful before continuing further

**Comment by doutriaux1** [comment]
yep

**Comment by durack1** [comment]
@doutriaux1 so I have also hit issues on OS X 10.11.3:
```
OS X: 10.11.3
XCode: 7.2.1
XQuartz: 2.7.8
gfortran: 5.2.0
git: 2.6.2
```
And using the `install_metrics.bash options:
```python
num_cpus=1
build_graphics=true
build_graphics_against_mesa=false
build_cmor=true
build_parallel=false
keep_uvcdat_build_dir=false
cmake_version="3.4.3"
cdat_version="master"
```
The error I hit is:
```
[ 11%] Performing build step for 'freetype'
CMake Error at /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/freetype-prefix/src/freetype-stamp/freetype-build.cmake:56 (message):
  CTEST_FULL_OUTPUT
...
Do you want more here?
```

**Comment by durack1** [comment]
@doutriaux1 ok got things building on `OS X 10.11.3` but have hit a bunch of errors in the tests - as per the attached file [160305_PCMDIMETRICS-master-testlog.txt](https://github.com/PCMDI/pcmdi_metrics/files/160070/160305_PCMDIMETRICS-master-testlog.txt)

**Comment by durack1** [comment]
@doutriaux1 @gleckler1 it seems this long-standing issue is still a problem..
![metricsfail](https://cloud.githubusercontent.com/assets/3229632/13992532/ac9ccfa8-f0d9-11e5-9907-3b7f7d74b6fd.png)
As the EOS article is scheduled for publication soon, and as we're likely to get a lot of eyes looking at the repo in coming weeks it'd be great to solve this today.

**Comment by durack1** [comment]
@doutriaux1 the Travis badge still says failing

**Comment by doutriaux1** [comment]
I know, i know... Need to go thru the mac numbers with @gleckler1
