### ISSUE TITLE
external check of parameter table model and obs data

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#320]
@doutriaux1 @durack1 With a switch available on the parameter table it would be great to be able to do a dry run only on trying to read all model (including land sea masks) and obs data and to report the results in a file that can be browsed.   If there is a single script for doing all of these checks CD, PG and PD via iteration should be able to provide some comprehensive error trapping.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 Last week I was really impressed at how well they were trapping user errors in the ILAMB package.   This can make all the difference to users.   We should revisit this for our parameter files, having a dry run test case accomplished via a dedicated script that can be continuously modified with new exceptions as we bang on it.   So, I propose again this be done in a separate file, not from within the pcmdi_metrics_driver.py...  lets chat about this...

**Comment by durack1** [comment]
@gleckler1 it would seem that there are many things to chat about - wanna schedule a sit down so we can go over the more comprehensive and targeted issue list and bang things into line regarding the milestones and then also set dates?

**Comment by gleckler1** [comment]
@durack1 @durack1 noon lunch in courtyard?
