### ISSUE TITLE
Add durolib library

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#325]
The functions inside durolib.py are being heavily used, this should be folded into the package.

@doutriaux1 how easy is it to clone a file during install? Conda package wrapping?

@gleckler1 @lee1043 pinging you both here

**Comment by doutriaux1** [comment]
you want to go the conda way. I'll push  a PR on your durolib to do this.

**Comment by doutriaux1** [comment]
@durack1 where is durolib repo?

**Comment by durack1** [comment]
@doutriaux1 https://github.com/durack1/pylib/blob/master/durolib.py

**Comment by doutriaux1** [comment]
so it's just one file?

**Comment by doutriaux1** [comment]
I would recommend renaming your whole pylib repo `durolib` and give a more menaningful to the durolib.py file. Then package the whole thing for conda.

**Comment by durack1** [comment]
@doutriaux1 at this stage yep.. I will be adding a couple of new functions in time, and there may be a `json` or similar data file required

**Comment by durack1** [comment]
Linked https://github.com/durack1/pylib/issues/11 and https://github.com/durack1/pylib/issues/12

**Comment by durack1** [comment]
@doutriaux1 in prep for `1.1` how do I get the `durolib` library wedged into the metrics - this is fairly trivial to do right?

**Comment by durack1** [comment]
@doutriaux1 thanks for the help on this - I believe we're closed as `1.0.0` is now available at https://anaconda.org/durack1/durolib
