### ISSUE TITLE
clean up tags?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#327]
@doutriaux1 @durack1 
We currently have the following tags:  v1.0.0, v1.0, 1.05, 1.0

Would should be consistent... do we have a 'v' in front or not?   In the EOS paper we do - its PMPv1.1 ...
I don't think we have to use the "PMP" or "v" ... although it might be nice to do so...
The main thing is that we are consistent.   
Next Weds May 4 we will tag 1.1 .... shall we call in PMPv1.1   ?
Is there a way to remove tags so that we don't have 3 tags that refer to 1.0?  
C, lets talk about this.

**Comment by doutriaux1** [comment]
@gleckler1 tags are free in github, I have no objection. Let's have both.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 I see the diversity of naming in uv-cdat...  I think it is confusing to have things like v2.4.1 and uvcdat-2.4.1 ... what is the difference?   Of course a few developers know, but there may come a time (very soon with the PMP) where there are non experts browsing through our accomplishments.   If we are going to have both for the PMP, lets have one which is "official" - I vote for PMP-x.x - so that we can provide some summary "diff" documentation for users to see...

**Comment by doutriaux1** [comment]
PMP- is not standard practive though, most software just have either the version number `X.x` or a v in front of it `v1X.x` I don't see why you care if there are many variant of this, but if you do it's ok to have just one.

**Comment by gleckler1** [comment]
@doutriaux1 mostly politics - we are going to be queried about specific advancements across versions and it will help if we can be clear and consistent and not have multiple naming conventions that include X.x
Why is there v2.4.1 and uvcdat-2.4.1  ... how does one know which is the official (e.g., referenced in a paper)?

Lets drop the PMP if its not standard, but make tags that start with a "v" as our lineage for "official" releases...

**Comment by doutriaux1** [comment]
sounds good.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 here is another reason why its good to have a consistent naming convention that I'm sure you're experienced with ... I'm trying to prepare some documentation for the wiki and its important to have a clearly defined tag to point to. :-)

**Comment by doutriaux1** [comment]
no problemo my friend, vx.x.x it is.
