### ISSUE TITLE
wrong obs in test obs dir - test suite fails

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#331]
@doutriaux1 @durack1 changes obs really much up everything.  We need to make it easier to update obs database and not have issue propagate across package.   Need to replace test obs file...
tas_pcmdi-metrics_Amon_ERAINT_198901-200911-clim.nc
with
tas_ERAINT_000001-000012_ac.nc

Yes... we want to have the dates in the obs clim filenames but we've got to clean up obs database before making a new version of pmp obs database

**Comment by doutriaux1** [comment]
@gleckler1 this is all taken care of in the "conda" branch which revamps the test suite to address all these things. It's 99% done but I need to sit with you because of some discrepancies that appeared on mac.
