### ISSUE TITLE
Since zonal mean added, metrics fail on level data

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#333]
Since the zonal mean fcns were added pmp is failing on level data extracted from 4d, eg., ta-850

**Comment by doutriaux1** [comment]
will fix tomorrow

**Comment by gleckler1** [comment]
k

**Comment by gleckler1** [comment]
@doutriaux1 sorry, but this one is more urgent than deciphering max linux discrepancy... PMP currently not working 4d fields which we need to replace
