### ISSUE TITLE
complete documentation of v1.1

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#348]
@doutriaux1 once v1.1 has been tagged, we'll need to:
- [ ] Validate version info is correctly written (version indicated v1.1)
- [ ] Update wiki so correct paths are noted (for test cases, demos etc)
- [ ] Obtain zenodo DOI
- [ ] Finalise README.md with updated DOI
- [ ] Move tag point to new commit
- [ ] After tag point set, reset all checkout tagpoints to point back to `master` tags (metrics, UV-CDAT)
- [ ] Generate conda release and update https://anaconda.org/PCMDI/pcmdi_metrics/files

@gleckler1 to further supplement

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  We need to produce a v1.1 now, please.   We need to get the jsons off github and removed from the conda build.   Please accept pull request to remove jsons and then lets tag a version to send to conda

**Comment by durack1** [comment]
@doutriaux1 can you proceed with the `1.1` tagging steps above and update the conda release.. It'd be great to get the conda release updated to `1.1` tomorrow

**Comment by gleckler1** [comment]
Yes, @doutriaux1 @durack1  FREEZE NOW and get on conda

**Comment by doutriaux1** [comment]
@gleckler1 @durack1 we're releasing uvcdat 2.6 today. As soon as it's out. I will release 1.1. Ok?

**Comment by doutriaux1** [comment]
yes I guess you're right we do not require any specific version of uvcdat so we can do that. But I would still prefer to wait, people are going to get 2.4.1 if they install right now vs in a couple of hours.

**Comment by durack1** [comment]
@doutriaux1 as long as we have `v1.1` out by COB today I don't think it matters.. I personally do like the graphics tweaks coming in `UVCDAT v2.6.0` and would personally wait a day for it

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 We will have another version ready next week.   The critically thing right now is to remove the jsons from the conda build.

**Comment by durack1** [comment]
@doutriaux1 can you generate the zenodo DOI today? And if so can you tick off the list of items [up top](https://github.com/PCMDI/pcmdi_metrics/issues/348#issue-156641527) and close this issue?

**Comment by durack1** [comment]
@doutriaux1 can you bump my repo privileges to admin so I can sort the items out above? As I'm not an admin I can't generate Zenodo DOIs..

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 this `v1.1` issue was hijacked during discussions - I'll create a new issue for the `v1.1.1` tagging along with the new milestone created today
