### ISSUE TITLE
fix correlation calculations

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#350]

**Comment by doutriaux1** [comment]
@gleckler1 commenting out is not quite the same as "fixing" no?

**Comment by gleckler1** [comment]
@doutriaux1  Y and N.   Some probs with the corr were fixed (same values for each season)... but yes the xyt for precip only (?) is producing values >> 1... we need to figure this out.   Closed the issue for now only to reduce clutter of what needs to be done in the next few days before lockdown of 1.1... we don't have to have the pr xyt fixed by then but of course it would be good...

**Comment by durack1** [comment]
@gleckler1 I'd suggest setting this to a milestone (future) and reopening if it's still an unresolved issue.. You can always then just sort to only show yourself 1.1 items for e.g.
