### ISSUE TITLE
odd failures...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#359]
@doutriaux1  Something strange happening... can't run on too many variables... bombing in irreproachable ways.   Crashes after Nth variable but on rerun works fine on the Nth variable run by itself.... example.... output:

Exception in thread Thread-9064:
Traceback (most recent call last):
  File "/export/gleckler1/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/export/gleckler1/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/export/gleckler1/anaconda2/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 122, in pingPCMDIdbThread
    t.start()
  File "/export/gleckler1/anaconda2/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by durack1** [comment]
@gleckler1 the `pingPCMDIdbThread` is attempting to report to HQ if I'm not mistaken.. This needs to be considered by @doutriaux1 to see whether it's at all useful, otherwise turf..

**Comment by doutriaux1** [comment]
@chaosphere2112 let's restart the server and see if it helps. 
@gleckler1 try to set your env variable `UVCDAT_ANONYMOUS_LOG` to  `False` or edit your `${HOME}/.uvcdat/.anonymouslog` to set it there.

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 if it turns out that the issue is problems logging then I'd advocate this all gets revisited.. It should cause a code bomb like this

**Comment by gleckler1** [comment]
Thanks seems to have done the trick turning to False ... will keep it that way!

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 I would advocate that this logging needs a revisit if it is causing outages for users.. It should ping and if ANYTHING goes wrong it just continues, rather than what occurred above..

**Comment by chaosphere2112** [comment]
@durack1 The logging absolutely needs a revisit. It's on the (long) list of things to do.

**Comment by durack1** [comment]
@chaosphere2112 thanks for the heads up - glad to know it's on the to-do list
