### ISSUE TITLE
wrong single level (ua_850, etc) interpolated filenames 

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#367]
@doutriaux1 
Will need CD to repair this as pcmdi_metrics.io.base.Base in driver is too terse for PG to follow.   The problem is single sliced layers (ua_850, ta_200, zg_500, ...) have a duplicate (but x100, in pa rather than hPa) description in the filename.   The correction for the file below is to remove the "20000-" in the filename.

cmip5.MPIESM-MR.historical.r1i1p1.mo.Amon.ta_**20000-**200.ver1.1979-1989.interpolated.linear.2.5x2.5.global.AC.nc

**Comment by gleckler1** [comment]
@doutriaux1 note how the level info is dealt with in filename (e.g. "ta_850") should be consistent between output clims and json files

**Comment by gleckler1** [comment]
@doutriaux1 ok, regional domains may take a little work, but this one should be quick/easy... but not for me!

**Comment by doutriaux1** [comment]
@gleckler1 we need to talk this was `intended` I think the first one is the actual value retrieved and the second one is the value in param files. So you want to merge them into:
`cmip5.MPIESM-MR.historical.r1i1p1.mo.Amon.ta-200.ver1.1979-1989.interpolated.linear.2.5x2.5.global.AC.nc` ?

**Comment by gleckler1** [comment]
@doutriaux1  oui!
