### ISSUE TITLE
json files should contain filed indication which var was used

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#369]

**Comment by gleckler1** [comment]
@doutriaux1 pls clarify filed indication"

**Comment by gleckler1** [comment]
@doutriaux1  Still not clear what this issue is for... time to close?

**Comment by doutriaux1** [comment]
@gleckler1 I think the variable information is only comtained in the file name `tas_bla.json` nowhere in the json file we have a field: `variable:tas`

**Comment by gleckler1** [comment]
@doutriaux1 ok, I thought that is what you meant and I agree  - good to get it in z json...
