### ISSUE TITLE
Add OSX to travis continuous integration

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#380]

**Comment by durack1** [comment]
@doutriaux1 this would be an ideal candidate for the last issue tagged against `1.1.1` - it'd be good to get our systematic tests working asap..

**Comment by doutriaux1** [comment]
@gleckler1 and I don't think it's really high priority. I'd say a huge chunk of our customers are on Linux systems.

**Comment by doutriaux1** [comment]
And I put 3.0 just to mess with you @durack1 😜

**Comment by durack1** [comment]
I shall need to create a `robust` tag, and remove it in situations such as this :disappointed:

**Comment by doutriaux1** [comment]
There's a french saying: `Le mieux est l'ennemi du bien`

**Comment by doutriaux1** [comment]
In the same line of thought: https://en.wikipedia.org/wiki/Le_Chef-d%27%C5%93uvre_inconnu

**Comment by durack1** [comment]
I have a saying in my family: "Aspiring for 51% and settling for 30% means that you'll be lucky to reach 25% but 100% certain of mediocrity"

**Comment by durack1** [comment]
@doutriaux1 to get this working will likely require a resolution for #303 - which could be closed as a dupe

**Comment by gleckler1** [comment]
@doutriaux1 I think this can be close now correct?
