### ISSUE TITLE
Create json data query demo

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#384]

**Comment by durack1** [comment]
@gleckler1 wanna assign a milestone here?

**Comment by durack1** [comment]
@gleckler1 not sure what this is.. Some more info and a milestone would be helpful for others to attempt to get at what this means to you

**Comment by gleckler1** [comment]
@durack1 ... PG and CD working on demos for how to create a portrait plot and how to extract info out of json files

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 renamed to target just the json query demo as the portrait plot demo already has it's own issue #390 - both assigned to the 1.2 milestone

**Comment by lee1043** [comment]
Closing this for house keeping
