### ISSUE TITLE
pr 3hr xmls needed to begin work on diurnal cycle 

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#389]
@durack1  Not needed to be run weekly.   Just once would do on the historical runs...

**Comment by durack1** [comment]
@gleckler1 take a peek at `crunch:/work/cmip5/make_cmip5_xmls_da.py` You'll need to edit your destination path to your `HOME` and then you should be close to a `daily -> 3hr` tweak and you're off

**Comment by gleckler1** [comment]
@durack1 could use your help with both 3hr and daily pr for historical and picontrol.  Does not need to be in cron job.

**Comment by durack1** [comment]
@gleckler1 what's the milestone on this - are we a `1.2` nexter?

**Comment by gleckler1** [comment]
@durack1 what is needed asap is some xmls for historical 3hr and daily "pr".... ok if its only 1 realization/model ... this will enable us to get started on a series of high freq analysis

**Comment by durack1** [comment]
@gleckler1, so I ***think*** there should be a bunch of `3hr` and `day` files for `pr` building in:
```
crunch:/work/durack1/cmip5/
```
Take a peek on Monday and see what has been built.. You should have multiple experiments and ***most*** of the current data indexed on the local systems.. However it is cobbled together, so may require some iteration

**Comment by gleckler1** [comment]
@durack1   thanks, but still no can read... permissions need to be set recursively

**Comment by durack1** [comment]
@gleckler1 should be fixed now, however it's still building so will need to redo once it completes..

**Comment by durack1** [comment]
@gleckler1 ok seems to be complete - wanna close this if you can read the xmls?
