### ISSUE TITLE
update regions for variability

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#391]

**Comment by doutriaux1** [comment]
typos in PR merged by @gleckler1 please fix

**Comment by lee1043** [comment]
typo corrected, sorry! @gleckler1 @doutriaux1

**Comment by durack1** [comment]
@gleckler1 wanna assign a milestone here? @lee1043 is there an open/merged PR that goes with this issue - if so should it be closed?

**Comment by doutriaux1** [comment]
@lee1043 @gleckler1 can we close now that typo is fixed?

**Comment by lee1043** [comment]
@doutriaux1 Yes we can!
