### ISSUE TITLE
Update and CMORize observational database

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#394]
The observational database will be CMORed and updated to include both climatological data along with timeseries. The ultimate aim is to house a version-controlled database hosted in the ESGF system and include the download of this data during the install/or run step.

Some alternate approaches to versioning input data can be found at: https://github.com/BreakawayLabs/mom/issues/151

I also note that additional data may be needed:
- [ ] CERES-EBAF surface short wave (rsds)
- [ ] CERES-EBAF surface long wave (rlds)
- [ ] CERES-EBAF surface downwelling shortwave flux in air (rsds)
- [ ] CERES-EBAF surface downwelling longwave flux in air (rlds)
- [ ] CERES-EBAF surface downwelling shortwave flux assuming clear sky (rsdscs)
- [ ] CERES-EBAF surface downwelling longwave flux assuming clear sky (rldscs)
- [ ] QuikSCAT eastward wind (uas)
- [ ] QuikSCAT northward wind (vas)

@gleckler1 can clarify the above - not certain what has been added and what is still left to do

**Comment by gleckler1** [comment]
Now handled on a separate repository
