### ISSUE TITLE
Add derived variable capability

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#395]
pr = PRECL+PRECS

**Comment by durack1** [comment]
@doutriaux1 wanna assign a milestone here?

**Comment by doutriaux1** [comment]
hum... is 2.0 when we port to the CDP? or 3.0?

**Comment by gleckler1** [comment]
@doutriaux1 Lets talk about this.   We currently "derive" variables before input into the PMP, and there advantages to that approach.

**Comment by gleckler1** [comment]
@doutriaux1 Its better to produce "derived" variables before running mean_climate driver... that is still what we do.
