### ISSUE TITLE
Add alternate zonal bands 

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#398]
our default includes
        'NHEX' : {'domain':cdutil.region.domain(latitude=(30.,90,'ccb'))},
        'SHEX' : {'domain':cdutil.region.domain(latitude=(-90.,-30,'ccb'))},
       'TROPICS': {'domain':cdutil.region.domain(latitude=(-30.,30,'ccb'))},

which is good but there are several other common definitions, one will be added here

**Comment by doutriaux1** [comment]
@gleckler1 #399 adds the regions but not in the default list. Is this correct?
