### ISSUE TITLE
Monsoon evolution metrics - pentad scale

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#404]
PG, KS and JL to begin working on monsoon onset metrics

**Comment by durack1** [comment]
@gleckler1 I'd use the handles so you actually ping folks: @lee1043, I think Ken is not on the grid yet..

**Comment by gleckler1** [comment]
@lee1043  Lets talk about this one when you feel ready to do so.

crunchy xmls are at /work/durack1/cmip5/historical/atm/da/pr

For each of the monsoon domains in Sperber et al. (DOI 10.1007/s00382-014-2099-3) we will want to:

1) Compute and save domain area average time series of daily precipitation for a selected beginning year and end year (default could be 1980-2005).  Have options to save into netcdf time series.

2) Compute pentadal time scale annual cycle "climatologies" or "composites",  and save into netcdf
2a) One argparse option could be to do 1) and 2) in combination and not save data from 1)

3) With the pentadal annual time scale climatologies,  calculate monsoon "onset", "rapid fractional accumulation of rainfall " and "decay" and save in json files 

4) Bar charts could point to model CDF results.  Scatter plots from Fig 4 of Sperber et al. 

Each of the above may be best as individual scripts using argparse, with a usual driver script to loop over exp, model, realization...

This is much of the work, JW and PG to work through any remaining details with KS

**Comment by durack1** [comment]
@gleckler1 @lee1043 just for completeness Ken has a bunch of "supplemental" plots hosted at https://pcmdi.llnl.gov/home/about/staff/sperber/suplemental.html

**Comment by lee1043** [comment]
opened branch for the task: https://github.com/PCMDI/pcmdi_metrics/tree/404_jwl_pentmonsoon

**Comment by lee1043** [comment]
@gleckler1 In my understanding it seems like we start coding for the metrics from the scratch, is that correct? Please let me know if there is a draft code that I can refer somewhere.

**Comment by lee1043** [comment]
@durack1 could you please remind me what was for the given link? The link does not work anymore, so cannot get what you meant. Thanks!

**Comment by gleckler1** [comment]
@lee1043 Yes, from scratch...  but good news... https://github.com/PCMDI/pcmdi_metrics/blob/master/share/default_regions.py

One headache... we need to mask out over ocean.

**Comment by durack1** [comment]
@lee1043 it seems like the server pcmdi.llnl.gov is down, so try here https://pcmdi.github.io/staff/sperber/supplemental.html

**Comment by lee1043** [comment]
Pull Request: https://github.com/PCMDI/pcmdi_metrics/pull/563

NOTE FOR ISSUES (*: resolved)
*1. syear/eyear given by parameter file need to be refered in the code
*2. ocean mask for land only is not complete; refer placeholder
*3. pathin need to be fully replaced by modpath
*4. reference data (obs) is yet to be used
*5. 72 pentad to 73 pentad interpolation need to be added for HadGEM2 models 
*6. Adding of custom domain maybe needed to test Indian region as in Sperber & Annamalai 2014 Clim Dyn (or define the domain in the share/default_regions.py)
7. Make the results_dir aknowledge the tree structure
*8. use unit adjust parameter in the code
*9. leaf year
*10. start from July 1st for SH region
*11. add pentad time series to cumulative and archive it in netCDF
*12. calculate metrics based on cumulative pentad time series
*13. add time checker
14. add test

**Comment by gleckler1** [comment]
@lee1043 @doutriaux1  JW thank you for making this happen and CD for tests!   Closing issue now...
