### ISSUE TITLE
Sector scale sea-ice (Ivanova et al., 2016)

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#405]

**Comment by gleckler1** [comment]
PG to work with DI on this.

**Comment by lee1043** [comment]
This project will be revisited for HiLAT-PCMDI collaboration once it is established.

**Comment by lee1043** [comment]
The branch `405 pjg ivanova sic` has not been touched in a while. 

To get it back on track:
- [  ] sync the directory structure with the current PMP
- [  ] set up documentation
- [  ] (this might be later) convert the code to work with xCDAT

**Comment by durack1** [comment]
@lee1043 @acordonez @gleckler1 I was having a think about the notebook, and thought I would drop my notes down here. These are just ideas, there is no expectation that this would be completed for the CAMAS workshop, but it could be if there is general appeal.

Does it make sense to have a PMP/PCMDI logo/graphic somewhere up the top of the notebook? (Can you even do that). Just thinking it might be a good template to develop, which means as these pages are being looked at, the project wins - will also be a win for a screenshot to advertise this activity to Renu. If yes, then an ESGF and potentially DOE logo (ala logos on the [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs/#acknowledgement) acknowledgements).

Also, as we have some CMIP6 results, to inject some science into the notebook, could we compare the Ivanova CMIP5 results to the limited CMIP6 results - so 3 models in the [current notebook](https://nbviewer.org/github/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb) draft? Not sure if there are digital files somewhere that contain the Ivanova results - in this repo?

**Comment by acordonez** [comment]
@durack1 Regarding your last question, I haven't seen the original Ivanova metrics saved digitally anywhere.

**Comment by durack1** [comment]
@acordonez that's a bummer. I was just peeking at Figs 7, 8, 9 [here](https://journals.ametsoc.org/view/journals/clim/29/24/jcli-d-16-0026.1.xml#d80986528e554) and it would be really cute to generate a CMIP5 ensemble mean and compare it to our 30 CMIP6 realizations in an attempt to gauge quantified model improvement.

I wonder if @gleckler1 has anything digital that he could scrounge up? I recall in a long lost PMP branch there was some remnant code, and maybe some remnant digi results

**Comment by acordonez** [comment]
@durack1 if we have access to CMIP5 sea ice then we can run our version of the metrics for that mip - as we've seen it probably won't be the exact same data Ivanova had, but we can still make the comparison.

**Comment by durack1** [comment]
@acordonez my gut feeling is that getting ~10 CMIP5 models running will take some work, there were far more issues with the previous phase than with CMIP6, having said that the grid complexities are likely a little less, who knows. Either way, it's unlikely a quick line path that could be added for the workshop. I am anticipating that we might get a similar suggestion from the HiLAT folks when we chat on Wed, so was anticipating the suggestion now

**Comment by acordonez** [comment]
@durack1 Yes I do not think we could get this comparison ready in time for the workshop.

**Comment by lee1043** [comment]
I agree with @acordonez that comparison with CMIP5 may not get done by the workshop, but it is good to have the brain storming for the future update. Thanks, @durack1, feel free to throw any ideas and post them here for the future references.

**Comment by lee1043** [comment]
> Does it make sense to have a PMP/PCMDI logo/graphic somewhere up the top of the notebook? (Can you even do that). Just thinking it might be a good template to develop, which means as these pages are being looked at, the project wins - will also be a win for a screenshot to advertise this activity to Renu. If yes, then an ESGF and potentially DOE logo (ala logos on the [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs/#acknowledgement) acknowledgements).

@durack1 That's great idea. I made that edit in your PR #1028.

**Comment by lee1043** [comment]
Implementation completed, led by @acordonez, and included in [PMP v3.3](https://github.com/PCMDI/pcmdi_metrics/releases/tag/v3.3). Closing this issue.
