### ISSUE TITLE
zm option

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#407]
@doutriaux1 we currently have option in parameter files to save interpolated model clims as netcdf files.   We should add a companion option to save model 12month zonal means to netcdf files (pre-interpolation).    These could be in a single file as (12, latitude).

**Comment by doutriaux1** [comment]
@jservonnat awesome we can now assign work to you! Awesome! Don't worry about this one though, I was just testing.

**Comment by gleckler1** [comment]
@doutriaux1  In addition to having option in paramater file to save zonal means, it would be good also to save  area average 12 month time series for each region metrics are calculated for

**Comment by doutriaux1** [comment]
@gleckler1 and I just had a chat about this, it's better to keep it as a separate process.
