### ISSUE TITLE
missing portraits.scr file

### ISSUE THREAD

**Issue by tangq** [PCMDI/pcmdi_metrics#411]
After installation, the portraits.scr file is missing. I have to manually copy it to bypass the problem.

**Comment by gleckler1** [comment]
@tangq @doutriaux1 Thanks for reporting this!

**Comment by doutriaux1** [comment]
file in in share/pmp/graphics not in share/graphics any longer you need to edit the script that @gleckler1 gave you which is NOT part of this repo.
