### ISSUE TITLE
have travis push to nightlies

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#412]

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 can this be merged with PR 423?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 redundant with #423 thereore closing....

**Comment by doutriaux1** [comment]
different issue, @jservonnat could not download it. This is about automatic upload.

**Comment by zshaheen** [comment]
Conda nightlies are now created in #465, which is now in master.

**Comment by durack1** [comment]
@zshaheen this is great thanks!
