### ISSUE TITLE
Provide PCMDI logo for png branding

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#413]
Add new png for PCMDI branding of png output - keep under 500KB.

Should be under share/pcmdi/

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 @taylor it's time to vote - pick which one:
a)
![160915_pcmdi_logo](https://cloud.githubusercontent.com/assets/3229632/18560257/a40b9532-7b2f-11e6-9faa-0e5c9acaf530.png)
or b)
![160915_pcmdi_oblong_logo](https://cloud.githubusercontent.com/assets/3229632/18560313/e2c51c12-7b2f-11e6-8a85-67f588c582fe.png)

**Comment by gleckler1** [comment]
@durack1 in the obslong version its clear Tassie has been wiped off the map... if this is a sensitive issue, PD should choose!

**Comment by doutriaux1** [comment]
Alaska seems to be missing from both :wink:
I like a) better but I think that to add to graph b) is much lighter and cleaner. You don't want it to become the point of focus of your plot.

**Comment by durack1** [comment]
@taylor13 votes a) - correct?

**Comment by taylor13** [comment]
Why don't we include both as options.  For a letter or a ppt with white background, I prefer a.  I can see b might be preferred if you want to deemphasize.

**Comment by durack1** [comment]
@jservonnat has voted b)

**Comment by doutriaux1** [comment]
@taylor13 not a bad idea but we still need to pick a default. I'll make sure users can pass any png.
