### ISSUE TITLE
Add durolib as conda dependency

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#418]
Currently durolib is not listed as a dependency (and is not installed from conda during PMP installation), as it's [available on conda](https://anaconda.org/durack1/durolib) this should be added to the [meta.yaml](https://github.com/PCMDI/pcmdi_metrics/blob/master/conda-recipes/pcmdi_metrics/meta.yaml)

**Comment by doutriaux1** [comment]
@durack1 I don't think it is needed quite yet (as in master). This should be done as part of any/all branch that actually requires it.

**Comment by durack1** [comment]
@doutriaux1 it'll simplify things considerably for @gleckler1 and @lee1043 - they can chime in on this one.. Gentlemen?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @lee1043 although I don't think external users will have reason to use durolib, JL and PG rely on it heavily for running through our internal CMIP database... we need it to be there always without inconvenience - we have both wasted considerable time in the past over this issue - so yes, please stuff it in there even if buried and only for internal purposes.

**Comment by doutriaux1** [comment]
This is never going to happen. I refuse to install useless dependencies
Seriously it takes no time to type:
```
conda install durolib -c pcmdi
```

**Comment by durack1** [comment]
@doutriaux1 I'm not sure you've correctly labeled this a "useless dependency" it has a bunch of functions that make dealing with the local archive easier.. And a number of other things that are in development, or testing

**Comment by gleckler1** [comment]
if it is really this easy to install we might have a compromise

**Comment by doutriaux1** [comment]
it is, try it.

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 I would note the channel above was wrong, it should be:
```
conda install durolib -c durack1
```

**Comment by doutriaux1** [comment]
Thanks @durack1 I'm willing to meet you guys half way and put `durolib` on PCMDI channel.

**Comment by durack1** [comment]
@doutriaux1 as long as I have write access and can update it, that would be fine

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  Is durolib on pCMDI channel yet?  If so we can close this issue

**Comment by durack1** [comment]
@gleckler1 nope - https://anaconda.org/PCMDI doesn't list it yet.. Over to @doutriaux1

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 Guess we are settled on this being external.  As long as its easy to get thats fine
