### ISSUE TITLE
cleaning up the wiki

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#419]
Some pages on the wiki seems to be outdated and/or not really belonging on the wiki (or must be reclassified)

examples:
https://github.com/PCMDI/pcmdi_metrics/wiki/Reference-Syntax-indexation
https://github.com/PCMDI/pcmdi_metrics/wiki/IPSL-Corner

probably more...

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  great idea.... It would be good to figure out how to remove and organize the the links in the "pages" box on the rhs of main wiki page

**Comment by gleckler1** [comment]
@durack1 should we move to ipython notebooks for documentation?

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 good question, I've noted that if we host the notebooks (`*.ipynb`) on a webserver, then using the jupyter viewer these can be displayed in their full fruit versions - see the UV-CDAT example, the file is hosted on the UV-CDAT webserver:
http://nbviewer.jupyter.org/url/uvcdat.llnl.gov/iPython/boxfill/boxfill.ipynb

It might be a very good way to keep things organized, and just by updating the notebook, we further document our functionality and examples..

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  The github wiki functionality is bulky and very limited.   Are you suggesting we migrate away from having PMP documentation on the wiki and migrate somehow to jupiter?   If yes, how do we get this started?

**Comment by durack1** [comment]
@doutriaux1 @zshaheen I defer this question to you

**Comment by doutriaux1** [comment]
I think jupyter is good complement. anything tutorial should be done with jupyter (i.e anything involving python) . The Jupyter files still need to be hosted somewhere. We could use github.io to host the pmp website @mattben can help us to set this up it's not very hard.

**Comment by zshaheen** [comment]
I agree with Charles. Jupyter is good for interactive documentation or documentation involving code. The wiki is probably best for static stuff like installing pmp, etc.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @zshaheen @mattben  Will follow comp-sci lead, just one request... lets try to identify a sufficiently stable path that we can expect to last for a few years, ie, avoid any cutting edge solutions that require reinventing how we document things every 6 months.  

I like this example which links jupiter files directly to the github site, circumventing the github wiki via the README.md .... what do you think?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @zshaheen @mattben   I'm wondering if we move away from using the clunky wiki altogether and follow the above koldunovn example for documenting via the README.md

**Comment by gleckler1** [comment]
@doutriaux1 on same site, FYI.... 

http://nbviewer.jupyter.org/github/koldunovn/python_for_geosciences/blob/master/07%20-%20Other%20modules%20for%20geoscientists.ipynb

**Comment by doutriaux1** [comment]
@gleckler1 yes it's great for tutorials, we already have some for uvcdat see: http://uvcdat.llnl.gov/tutorials.html

**Comment by doutriaux1** [comment]
@gleckler1 @zshaheen @chaosphere2112 @mattben this nbviewer linking to github might be something we want to use.

**Comment by gleckler1** [comment]
@zshaheen @chaosphere2112 @mattben  @durack1  How does the overhead look, getting it set-up, maintaining, making it easy for tech-weak climate scientists to use, etc??

**Comment by doutriaux1** [comment]
I'll let @mattben take a look and let us know, he's the expert on this.

**Comment by doutriaux1** [comment]
@zshaheen you can tell us too, you're a young hipster as well.

**Comment by mattben** [comment]
I've never used Jupiter notebook @chaosphere2112 is the one you want

**Comment by doutriaux1** [comment]
guys it's really easy simply point https://github.com/doutriaux1/pcmdi_metrics/tree/master/tutorials at: http://nbviewer.jupyter.org/ and it's done for you!

**Comment by doutriaux1** [comment]
result can be accessed at: http://nbviewer.jupyter.org/github/doutriaux1/pcmdi_metrics/tree/master/tutorials/

So basically there's no setup we simply need to create the url above that points to a git repo with ipython notebooks!

@williams13 @mattben @chaosphere2112 we should use this for our UV-CDAT ipython notebook tutorials, it's easier than what we have now! No need to generate nbconvert. Granted we do not get the pretty picture. But that could be all wrapped up in a top ipython notebook that links them all. Just an idea.

**Comment by doutriaux1** [comment]
@mattben you should look into jupyter notebook with your other web skills that would be a really good plus.

**Comment by doutriaux1** [comment]
wow, i just discovered that actually github converts ipynb for you as well! This is really really slick see: https://github.com/doutriaux1/pcmdi_metrics/blob/master/tutorials/ParallelCoordinates.ipynb

**Comment by gleckler1** [comment]
@doutriaux1 Now you're talking!!

**Comment by zshaheen** [comment]
After speaking to some of the guys, I think it's a good idea to transition to Jupyter. As @doutriaux1 showed, it's pretty simple to setup and use. We can have tons of tutorials if needed, especially with the current and forthcoming changes to the driver using cdp.

**Comment by doutriaux1** [comment]
Just set it up for uv-cdat, needs cleaning but look at:
https://github.com/uv-cdat/tutorials
and
http://nbviewer.jupyter.org/github/UV-CDAT/tutorials/tree/master/
