### ISSUE TITLE
Multiple parallel coordinates (y-axis) on single plot

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#421]
@jservonnat pinging you here UV-CDAT/vcs#11
![parallel_coordinates_with_r](https://cloud.githubusercontent.com/assets/3229632/18879084/eadb9816-8487-11e6-85c3-08eabba198a9.png)

**Comment by gleckler1** [comment]
@doutriaux1 @jservonnat .... mission accomplished - time to close this issue?

**Comment by gleckler1** [comment]
@doutriaux1 pls when creating branch put issue# as prefix to help us keep track of things.

**Comment by durack1** [comment]
@doutriaux1 if you'd like to refresh your memory: https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers 😄

**Comment by doutriaux1** [comment]
Except I believe I created the branch before the issue was recorded ;)

C.
