### ISSUE TITLE
some obs do not have a default, this may lead to failure when running the driver

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#422]
example: `sftlf` (but that is normal) or `rtnetcre`

thanks @zshaheen for noticing this

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen The only additional variable that we use (so far), rtnetcre, has been added.   There is a pull request to implement.   When one of you has pushed to master I'll remove this issue... which will likely resurface from time to time as additional fields are added to our database
