### ISSUE TITLE
conda nightly channel doesn't seem to be working (or updating)

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#423]
@jservonnat and I are hitting issues:

```
(pcmdiMetrics) duro@ocean:[~]:[2113]> conda install -c pcmdi pcmdi_metrics=2016.9.16
Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - pcmdi_metrics 2016.9.16*

You can search for packages on anaconda.org with

    anaconda search -t conda pcmdi_metrics
```

**Comment by durack1** [comment]
@jservonnat try the following:
`conda install -c pcmdi/label/nightly pcmdi_metrics`

But I still don't think what you want is in there:
```
(pcmdiMetrics) durack1@oceanonly:[~]:[2118]> python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pcmdi_metrics
>>> dir(pcmdi_metrics.pcmdi.io)
['OBS', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'pcmdi_metrics']
```
@doutriaux1 he's after the `JSONs` class

**Comment by doutriaux1** [comment]
it's because it's only in the `nightly` channel

**Comment by durack1** [comment]
@doutriaux1 if you look above the nightly labels are being used.. It's just that nightlies aren't updated.. It'd be good to get this working - building a nightly Conda release from the master each night

**Comment by doutriaux1** [comment]
agreed but it's not a top priority. For now I just do it manually.

**Comment by durack1** [comment]
@zshaheen in addition to the `linux-64` nightlies, can you also add in `osx-64` nightlies? Most of the development is occurring on `osx-64` so having these available alongside the linux will be very useful..

**Comment by doutriaux1** [comment]
@durack1 it's my fault, we need to get mac and linux in agreement first (otherwise the suite will fail for one at the moment. 
@zshaheen we do need to build the nightly for linux no X support though (thst's where the meta.yaml.in comes in) look at my .travis for vcs

**Comment by zshaheen** [comment]
@doutriaux1 Doesn't your `.travis.yml` for vcs already do what we do for pmp? I see that you're testing on linux and osx, but looking at your `conda_upload.sh` you only upload to Anaconda for linux. For pmp, we just test and upload on linux. In the end, only the linux builds are being uploaded.

@durack1 @doutriaux1 We can have the osx nightly being upload without testing. This is not ideal, but it's a middle ground. Maybe have an `osx-nightly` or `unstable-nightly` label on Anaconda. This would be different than the stuff in the current `nightly` label, since it's untested.

**Comment by durack1** [comment]
@zshaheen @doutriaux1 we need to solve these test issues - what do we need to address this?

**Comment by zshaheen** [comment]
Conda nightlies are now created in #465, which is now in master. The issue with non-osx nightlies is a separate issue, since we need to get the tests working on osx first.
