### ISSUE TITLE
finding a common path for using argparse

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#425]
@doutriaux1 @durack1 @zshaheen @lee1043 @jservonnat This has been scattered about but now is urgent because we have many issues awaiting a solution to this.  The most advanced example we have is 
https://github.com/PCMDI/pcmdi_metrics/blob/377_Variability_mode_NAO/src/python/devel/variability_mode_nao/lib/argparse_functions.py

This could be done differently, but we need to find common ground as soon as possible and somehow centralize our use of arguments (in share?)

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen  @lee1043 @durack1 We now have a solution for this with the PMPparser.     It needs to be implemented for the following (and everything after that):

- [ ] mean climate
- [X] monsoon-wang
- [ ] ENSO
- [ ] Variability modes

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1 The PMP parser needs to be included as part of the PMP to facilitate how we are trying to integrate different metrics.   Sure it can be installed separately but having it included will greatly facilitate the modification of the default arguments shown on 
https://github.com/PCMDI/pcmdi_metrics/wiki/PMPParser
Can we include it now?

**Comment by zshaheen** [comment]
@gleckler1 It's in all of the nightly releases after October 18. So a person would need to do `conda install pcmdi_metrics=SOME_NIGHTLY -c conda-forge -c pcmdi` instead of the more direct `conda install pcmdi_metrics -c conda-forge -c pcmdi`. We would need to release a new version of pcmdi_metrics (v1.2?) so there would be no need to put in a version number.

**Comment by gleckler1** [comment]
@zshaheen I"ve been doing that.   What I'm looking for is having the default arguments (https://github.com/PCMDI/pcmdi_metrics/wiki/PMPParser) in **master on github** so that it is easier for us to modify them.

**Comment by zshaheen** [comment]
@gleckler1 sure, I'll talk to @doutriaux1 about this. We'll get to accepting that pull request too also.

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1  Thanks for this... done here for now...
