### ISSUE TITLE
JSONs class: compatibility with the previous versions of the json files

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#436]
@doutriaux1 @gleckler1 The JSONs class (in io/base.py) does not seem to work on the old structures of the jsons files. At least with some of the ones that @gleckler1 gave me with all CMIP5 historical results.
Should we work on having the right structure in the json files or on the JSONs class to be able to ingest the different structures that have been produced by the PMP?

**Comment by doutriaux1** [comment]
works for me on the json files you sent me.

**Comment by doutriaux1** [comment]
anyhow we have a writter that wotks for he future json too.

**Comment by jservonnat** [comment]
On all the variables? It only works for me on a subset (the ones with the metrics names without the region)

**Comment by doutriaux1** [comment]
yes for all variables but because I have a fix for #435 which is probably your issue.

**Comment by jservonnat** [comment]
I guess not, for instance the variable rlds comes out empty of the JSONs class, although there are data in the json file.

**Comment by gleckler1** [comment]
@doutriaux1 @jservonnat   I suspect this results from not having and estimate of rlds in the obs dataset..... this error should be trapped

**Comment by jservonnat** [comment]
@gleckler1 @doutriaux1 I haven't add any issues with the JSONs class since the last update. I will provide you with some feedbacks after more testing but it sounds like the last version works pretty well.

**Comment by jservonnat** [comment]
@gleckler1 @doutriaux1 I haven't add any issues with the JSONs class since the last update. I will provide you with some feedbacks after more testing but it sounds like the last version works pretty well.

**Comment by jservonnat** [comment]
@gleckler1 @doutriaux1 I haven't add any issues with the JSONs class since the last update. I will provide you with some feedbacks after more testing but it sounds like the last version works pretty well.

**Comment by jservonnat** [comment]
@gleckler1 @doutriaux1 I haven't add any issues with the JSONs class since the last update. I will provide you with some feedbacks after more testing but it sounds like the last version works pretty well.

**Comment by gleckler1** [comment]
@jservonnat @doutriaux1 Sounds like we can close this for now
