### ISSUE TITLE
add masks for reference data 

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#445]
As we embark on cmorizing the PMP database we should include land sea masks

**Comment by durack1** [comment]
@gleckler1 to do this right it will likely involve obtaining masks from the original data sources, and while this happening we may as well update the data alongside the masks.. so not sure what milestone you want to pin this to?

**Comment by gleckler1** [comment]
@durack1 For now its just good to have it jotted down.   Getting PMP1.5-obs going is certainly a higher priority

**Comment by durack1** [comment]
@gleckler1 ok perfect `2.0` it is then..
