### ISSUE TITLE
better alternative to argparse?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#456]
@doutriaux1 @zshaheen  Before we commit 100% to argparse for everything, should we consider http://docopt.org ?

**Comment by doutriaux1** [comment]
Argparse is official python, I'd rather limit the dependencies, but @zshaheen please take a look if there's any missing feature in argparse that we could absolutely use let me know.

**Comment by durack1** [comment]
https://realpython.com/blog/python/comparing-python-command-line-parsing-libraries-argparse-docopt-click/ - this seems to discuss many of the options, including argparse and docopts.. Although it is 2015..

**Comment by zshaheen** [comment]
I've look through docopt and it's just an easier way to do the stuff that argparse does, specifically using doc strings. docopt also has it's own rules for things and that just makes people using it need to know more stuff. 

Unless there's something missing in how we parse stuff, I think the default argparse is the best. If we did choose another argument parsing library, we'd need to add it to cdp and we don't really want to add more dependencies.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @zshaheen  OK, thanks for looking.  Shelved.
