### ISSUE TITLE
test suite isn't reporting correctly

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#458]
I just took a look at the latest log from the `master` build and the tests are not finding data, yet they are not reporting test errors:

https://travis-ci.org/PCMDI/pcmdi_metrics/builds/181746675#L1066

This is an issue in the reliability of the test suite

**Comment by doutriaux1** [comment]
what are you talking about?

i see the ldsea mask not being found but that's normal. I don't see anything weird in this log.

**Comment by durack1** [comment]
@doutriaux1 you don't think the `cdms I/O error` At L1066 isn't weird? It's indexing a non-existent file
