### ISSUE TITLE
conda package uploaded for every PR even if branch is not master

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#461]
see: https://travis-ci.org/PCMDI/pcmdi_metrics/builds/189601037

**Comment by durack1** [comment]
@doutriaux1 nice!! This relates to #457, #423, #412, kinda #380 (this needs the `OS X` vs `linux` problem fixed - also #303), so when it's locked down and has the **robust** tag firmly assigned these semi-dupes may need closing too

@gleckler1 ping

**Comment by doutriaux1** [comment]
yes if @zshaheen doesn't get to it first, I'll make sure it only uploads for master branch, not every PR.

**Comment by zshaheen** [comment]
@doutriaux1 If feel like this is unavoidable, since when doing a PR, git will always try to merge with master to see if there are any conflicts and then test the code on Travis. Like @durack1 mentioned, this this exactly the same issue I had in December, see #457.

**Comment by doutriaux1** [comment]
@zshaheen now it never gets build because travis only builds on PR now... Let me change that back.

**Comment by zshaheen** [comment]
@doutriaux1 This was fixed in #465, which has now been merged into master.
