### ISSUE TITLE
strategy for organizing graphics functions in devel...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#464]
@doutriaux1  Making progress with a series of branches that include new metrics in, for example, devel/monsoon/scripts and devel/monsoon/lib.    We need to decide how best to partition analysis (metrics) codes from graphics fcns.   Question: when developing a plotting routines, should they go in devel/monsoon/scripts and devel/monsoon/lib or devel/monsoon/scripts and devel/monsoon/graphics ?

**Comment by durack1** [comment]
@gleckler1 at the moment you have [/src/python/graphics](https://github.com/PCMDI/pcmdi_metrics/tree/master/src/python/graphics) which contains all graphic (the portrait.py) functions, and [/src/python/pcmdi](https://github.com/PCMDI/pcmdi_metrics/tree/master/src/python/pcmdi) that contains all the metrics calculation functions.. To me I think having these separated (graphics from calcs) is a good idea.. A rename of the `pcmdi` to something more descriptive could be useful..

@doutriaux1 thoughts?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  Its a 2 part question... the first is where to put graphics in "devel" branches ... we want to do this consistently to ease how its dealt with in setup.py... 2nd question is where do we them to go in master when merged.   I think PD's suggestion is part 2.

**Comment by durack1** [comment]
@gleckler1 just to comment (you're actually doing this, I'm just commenting) would it be smart to have a complete directory tree under devel, so [src/python/devel/monsoon_wang](https://github.com/PCMDI/pcmdi_metrics/tree/334_monsoon_wang/src/python/devel/monsoon_wang) and then under this directory duplicate the "functions" and "graphics" directories, that would then be folded back into the master [/src/python/graphics](https://github.com/PCMDI/pcmdi_metrics/tree/master/src/python/graphics) and [/src/python/pcmdi](https://github.com/PCMDI/pcmdi_metrics/tree/master/src/python/pcmdi) or "function" trees?

At least in my head it would be relatively straight forward to then extract the contents of the subdirs out of the branch/devel subdir and place them in their appropriate "master" subdirs as part of the install..?

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 Thats what I'm thinking.

**Comment by doutriaux1** [comment]
scripts go in scripts, that's easy
now all code should go under lib at that point you have 3 choices
if it's tiny put in graphics.py under monsson/lib
if it's so big you need to break it then put it inside directory: monsoon/lib/graphics/files.py
if it's going to be used by many many branches then put it under src/python/graphics

**Comment by gleckler1** [comment]
@durack1 @doutriaux1   How do you define "tiny"  or "so big" ?
Can't we decide where they should go based on logic?  
I don't have strong feeling how/where we do this, except I would like it to be sufficiently self describing by have all graphics under one tree rather than scattered about.

**Comment by durack1** [comment]
@gleckler1 I see two options, use directories to separate stuff.. Or use a naming convention that allows for this information to be gleaned from filenames.. Probably better to chat about this with a whiteboard..

**Comment by doutriaux1** [comment]
ok stick it in monsoon/lib/graphics/ directory
