### ISSUE TITLE
execfile?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#466]
@doutriaux1 

Line 40 of 
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/pcmdi/scripts/pcmdi_metrics_driver.py

is
execfile(sys.prefix + "/share/pmp/default_regions.py")

This makes good sense to me, but I thought we were being discouraged from using execfile.  And if that is the case, what is the best alternate solution to execfile?

**Comment by doutriaux1** [comment]
good point. I don't even really know why it's in share. Except to make it easy for developers to edit just this file. I'll fix this.

**Comment by gleckler1** [comment]
@doutriaux1    Its is share because we decided that was the right place to put it... its being shared by multiple metrics applications.    **My question is... If we don't use execfile, how should we load it?**  I'm asking because I am following this lead in other metrics branches.

**Comment by gleckler1** [comment]
@doutriaux1 ok
