### ISSUE TITLE
Updating pcmdi_metrics-nox?

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#469]
The latest version of pcmdi_metrics-nox is from 2016-10-20, as confirmed by:
https://anaconda.org/PCMDI/pcmdi_metrics-nox/files
Is there an update planned soon?

**Comment by doutriaux1** [comment]
@zshaheen did you push the changes to make it fully backward compatible? Also things went into master so why is the nightly so old?

**Comment by doutriaux1** [comment]
@zshaheen i bet you don't build the `nox` version. Take a look at vcs's conda_upload for this.

**Comment by zshaheen** [comment]
@doutriaux1 It's not the nox version, I'll get to that by tomorrow. And yeah, legacy support is available via `pcmdi_metrics_driver_legacy.py`

**Comment by doutriaux1** [comment]
@zshaheen there was something that was not fully compatible when you put CDP in. I'm not sure what exactly. You said you would fix it. (parameter names?)

**Comment by zshaheen** [comment]
If you use the old driver (`pcmdi_metrics_driver_legacy.py `), the old parameter names work. The new driver only works with the new naming. I can add code that translates the old parameter's keywords to work with the new one.

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen  This issue is about pmp-nox.   When can we start nightlies?   Does this first require us having an updated tag?

**Comment by doutriaux1** [comment]
@gleckler1 nightlies work but @zshaheen forgot to build the nox ones. @jservonnat you install the regular one and then install vtk-cdat-nox after the fact into your env.

**Comment by zshaheen** [comment]
@jservonnat @gleckler1 @doutriaux1 It works now guys. See here: https://anaconda.org/PCMDI/pcmdi_metrics-nox/files

**Comment by durack1** [comment]
@zshaheen this is great, so does that mean that each time a new PR is merged into `master` we get a new nightly? What happens if multiple PRs are merged in one day?

**Comment by doutriaux1** [comment]
@durack1 in case of multiple PR on the same day. Then the latest one overrides the first one, which is fine.

**Comment by durack1** [comment]
@doutriaux1 @zshaheen that's great, is it a 12am cron? So when is the deadline for merging PRs before the nightly is built?

**Comment by doutriaux1** [comment]
It's automatic as soon as travis successfully built and tested the master branch

**Comment by zshaheen** [comment]
Fyi, we have been getting this for the non-nox pcmdi_metrics since January.
