### ISSUE TITLE
Dealing with the vertical levels in ocean variables (to / so)

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#472]
We've set that up at IPSL (against WOA) and found it pretty interesting. It only involves a couple of lines added to the driver to enable the PMP to automatically extract, say, to at 200m at depth, if you pass to_200 (same mechanism as for the atmospheric variables, but without the 100 factor).
If you guys are interested I can set up a PR.

**Comment by durack1** [comment]
@jservonnat I would be really interested to see what you've done, yeah go ahead and drop in a PR or create a branch that we can starting iterating on.. Also there are updates coming down the pipe on the regridding functionality, we're getting a regridding upgrade :)

**Comment by jservonnat** [comment]
Ok great I'll do this (it's really simple actually).

**Comment by durack1** [comment]
@jservonnat just don't merge it!!

**Comment by jservonnat** [comment]
@durack1 I've set up a PR, tell me if I did it correctly or if I need to do something differently.

**Comment by gleckler1** [comment]
@jservonnat This will be a great contribution!   And a good opportunity to "grease the wheels" on making a contribution.    It does not look to me as though you have created a branch for this.   Check the gh site, there is a button on the left side for branches with master as a default.   Click on that and you will see all of the branches and see the syntax for how we create them.   Took me a while to get this, maybe we can make this part of our Fri chat.    Anyhow, after you have created a branch (git checkout -b newbranch), made changes and documented them (git commit -am "crap"), then you can git push it to the gh repository.    After that, you can make a pull request and we'll review your branch.
