### ISSUE TITLE
Demo of PMP_nightly (default and nox) fails

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#473]
I've run the PMP_nightly-nox pmp_demo_1.py and it fails (same with PMP_nightly; both are 2017.03.01-0):
```
[Press enter]
We will now run the pmp using this parameter file
To do so we are using the follwoing command
pcmdi_metrics_driver_legacy.py -p /home/jservon/anaconda2/envs/PMP_nightly-nox/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
Traceback (most recent call last):
  File "/home/jservon/anaconda2/envs/PMP_nightly-nox/bin/pcmdi_metrics_driver_legacy.py", line 194, in <module>
    for model_version in parameters.model_versions:
AttributeError: 'module' object has no attribute 'model_versions'
```
 
I've tried to correct this issue by modifying the param file but I keep hitting new issues.
I've also tried with pcmdi_metrics_driver.py and it doesn't work neither:
```
(PMP_nightly-nox) jservon@ciclad-ng:/data/jservon/Evaluation> pcmdi_metrics_driver.py -p /home/jservon/anaconda2/envs/PMP_nightly-nox/share/pmp/demo/pmp_input_parameters_demo1.py
CDMS system error: No such file or directory
CDMS I/O error: Opening file /data/jservon/Evaluation/pmp_demo/cmip5clims_metrics_package-amip/_ACCESS1-0_Amon_amip_r0i0p0_198001-200512-clim.nc
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
/home/jservon/anaconda2/envs/PMP_nightly-nox/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1241: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (srcMaskValues != None):
/home/jservon/anaconda2/envs/PMP_nightly-nox/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (dstMaskValues != None):
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
```

**Comment by zshaheen** [comment]
Use the command `pcmdi_metrics_driver_legacy` instead of `pcmdi_metrics_driver` for scripts with the old vocabulary.

**Comment by jservonnat** [comment]
I've tried both (see first block) and none of them work.

**Comment by zshaheen** [comment]
But yeah, I'll see why the demo fails. I must have forgot to change a keyword from `model` to `test`

**Comment by jservonnat** [comment]
It might not be the only one. Last time I've tried I had to change a couple of them and didn't actually managed to make it work...

**Comment by jservonnat** [comment]
It's true both for the default and nox.

**Comment by durack1** [comment]
@jservonnat thanks for kicking the tyres on this stuff, it's really helpful having you input

**Comment by jservonnat** [comment]
@durack1 you're welcome mate ;)

**Comment by gleckler1** [comment]
@jservonnat @zshaheen  I will sample some of my "legacy" parameter files to make sure they are all still working.   If not, we'll have to revert back or get this fixed now.   We need full backwards compatibility.

**Comment by jservonnat** [comment]
@gleckler1 I'll be waiting for you!

**Comment by zshaheen** [comment]
@jservonnat @gleckler1 `pmp_demo1.py` works now on the latest version. It wasn't an issue with the `pcmdi_metrics_driver_legacy.py`, but rather `pmp_demo1.py` didn't use the new driver. Download the latest version like so:

`conda install pcmdi_metrics=2017.03.06 -c pcmdi/label/nightly -c conda-forge -c uvcdat`

**Comment by jservonnat** [comment]
@zshaheen not working on my side... it looks like it is not handling the variable (provides a blank):
```
THIS DEMO PARAMETER FILE IS AVAILABLE AT: https://github.com/PCMDI/pcmdi_metrics/blob/master/demo/parameter_files/pmp_input_parameters_demo1.py
FOR A COMPLETE LISTING OF ALL AVAILABLE KEYS IN THE PMP PARAMETER FILES SEE: https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/parameter_files/input_parameter_file_all_options.py
This ends this parameter file
[Press enter]
We will now run the pmp using this parameter file
To do so we are using the follwoing command
pcmdi_metrics_driver.py -p /home/jservon/anaconda2/envs/TEST/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
CDMS system error: No such file or directory
CDMS I/O error: Opening file /data/jservon/Evaluation/PMP/pmp_demo/cmip5clims_metrics_package-amip/_ACCESS1-0_Amon_amip_r0i0p0_198001-200512-clim.nc
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
/home/jservon/anaconda2/envs/TEST/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1241: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (srcMaskValues != None):
/home/jservon/anaconda2/envs/TEST/lib/python2.7/site-packages/ESMP/src/ESMP_API.py:1248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (dstMaskValues != None):
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
OBS
INFO:root:Could not figure out obs mask name from obs json file
MODEL
You can now look at the results in: ./pmp_demo/simple-test1/
[Press enter]
```

**Comment by zshaheen** [comment]
@jservonnat I'll look into this

**Comment by jservonnat** [comment]
@zshaheen thanks a lot. I've re-tried from scratch and obtain the same result.
I've also tried to look into the driver but the structure of the new version is totally enigmatic for me (I'm really not good with python classes...).

**Comment by zshaheen** [comment]
@jservonnat Okay, I hopefully got the no output issue working now. Please get the latest nightly from Anaconda or manually install it from master.

There is an issue regarding the downloading of the demo data. It's an issue on our side, so the current workaround is using a command line argument to point to the location of the tarball:

`pmp_demo_1.py -d /path/to/pmpv1.1_demodata.tar `

If you don't use the `-d` argument, I'll try to download it and that currently doesn't work. If you don't have `pmpv1.1_demodata.tar`, I can email it to you, since GitHub doesn't allow me to attach that filetype. 

Let me know how this goes.

**Comment by jservonnat** [comment]
@zshaheen apparently I have no issue with downloading the tarball but the demo fails now on another error related with cdp (for the default and nox versions):
```
THIS DEMO PARAMETER FILE IS AVAILABLE AT: https://github.com/PCMDI/pcmdi_metrics/blob/master/demo/parameter_files/pmp_input_parameters_demo1.py
FOR A COMPLETE LISTING OF ALL AVAILABLE KEYS IN THE PMP PARAMETER FILES SEE: https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/parameter_files/input_parameter_file_all_options.py
This ends this parameter file
[Press enter]
We will now run the pmp using this parameter file
To do so we are using the follwoing command
pcmdi_metrics_driver.py -p /home/jservon/anaconda2/envs/TEST/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
Traceback (most recent call last):
  File "/home/jservon/anaconda2/envs/TEST/bin/pcmdi_metrics_driver.py", line 2, in <module>
    import pcmdi_metrics.driver.pmp_driver
  File "/home/jservon/anaconda2/envs/TEST/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_driver.py", line 3, in <module>
    import cdp.cdp_driver
ImportError: No module named cdp_driver
```
With the 'legacy' version I get:
```
(TEST-nox) jservon@ciclad-ng:/data/jservon/PMP> pcmdi_metrics_driver_legacy.py -p /home/jservon/anaconda2/envs/TEST-nox/share/pmp/demo/pmp_input_parameters_demo1.py
Traceback (most recent call last):
  File "/home/jservon/anaconda2/envs/TEST-nox/bin/pcmdi_metrics_driver_legacy.py", line 194, in <module>
    for model_version in parameters.model_versions:
AttributeError: 'module' object has no attribute 'model_versions'
```
Any thought on that?

**Comment by zshaheen** [comment]
Please install `cdp` (`conda install cdp -c conda-forge -c uvcdat`). Also the demos don't work with the legacy due to the new keyworks.

**Comment by jservonnat** [comment]
@zshaheen after verification it was already installed:
```
We will now run the pmp using this parameter file
To do so we are using the follwoing command
pcmdi_metrics_driver.py -p /home/jservon/anaconda2/envs/TEST/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
Traceback (most recent call last):
  File "/home/jservon/anaconda2/envs/TEST/bin/pcmdi_metrics_driver.py", line 2, in <module>
    import pcmdi_metrics.driver.pmp_driver
  File "/home/jservon/anaconda2/envs/TEST/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_driver.py", line 3, in <module>
    import cdp.cdp_driver
ImportError: No module named cdp_driver
You can now look at the results in: ./pmp_demo/simple-test1/
[Press enter]
(TEST) jservon@ciclad-ng:/data/jservon/PMP> conda install cdp -c conda-forge -c uvcdat
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/jservon/anaconda2/envs/TEST:
#
cdp                       1.0.3                         0    uvcdat
```
Is it the right version? (I've tried conda update with no success)

**Comment by zshaheen** [comment]
@jservonnat I'll work on this and get back to you with a fix.

**Comment by zshaheen** [comment]
@jservonnat Do you have the latest code from master? With the newer version of cdp, I made a fix for pmp on 14/03/2017. Grab the latest code from master and it should work.

**Comment by jservonnat** [comment]
@zshaheen Can you confirm how to do that? Is it just a git clone git://github.com/UV-CDAT/CDP in the lib/python2.7/site-packages/cdp directory of my anaconda install (~/anaconda2/envs/TEST/lib/python2.7/site-packages/cdp)?
I've cloned the master and here is what I get:
```
_cache.py  cdp_metric.py  cdp_parameter.py  cdp_provenance.py  cdp_viewer.py  test
cdp_io.py  cdp_output.py  cdp_parser.py     cdp_tool.py        __init__.py
```
Actually I find no cdp_driver.py file in the cdp master github repo:
https://github.com/UV-CDAT/cdp/tree/master/cdp

**Comment by zshaheen** [comment]
@jservonnat Yes, there's no driver now. Just do `python setup.py install` and all should work.

**Comment by jservonnat** [comment]
The problem is that the demo is complaining about a missing cdp.cdp_driver (see message above), I might be confused with this message but in this case, I don't understand what I'm doing :)...

**Comment by zshaheen** [comment]
@jservonnat It's okay :)

You need to get the latest code from pmp. But it's good that you got the latest from cdp as well.

**Comment by jservonnat** [comment]
@zshaheen the version I'm working with is:
pcmdi_metrics             2017.03.14                    0    pcmdi/label/nightly

Which is a later version than the one you pointed in a previous (2017.03.06). Should I use 2017.03.06?

**Comment by gleckler1** [comment]
@jservonnat @zshaheen  Is this issue resolved?

**Comment by jservonnat** [comment]
@gleckler1 work in progress!!

**Comment by jservonnat** [comment]
@zshaheen I ping you about the issue, do you have something new? I really need to have it working as soon as possible.

**Comment by zshaheen** [comment]
@jservonnat I will work on this now. So sorry for the delay. I had to release another project and just did that yesterday.

**Comment by jservonnat** [comment]
@zshaheen no problem ;)

**Comment by zshaheen** [comment]
@jservonnat Okay, let's hope it works this time.

There was a problem with the nightlies (they weren't being updated) so now that's all hopefully fixed. Here's what I tried and it worked for me:

```
conda create -n pcmdi-nightly-nox -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox=2017.04.13
source activate pcmdi-nightly-nox
pmp_demo_1.py
```

Let me know how this goes.

**Comment by jservonnat** [comment]
@zshaheen @gleckler1 I'm really glad to confirm that the demo now works for me ;).
FYI I've also tried without the 'pcmdi_metrics-nox=2017.04.13' (just with pcmdi_metrics-nox), and it worked as well.
If you have nothing left to say we can close this issue.
Back to work, thanks a lot @zshaheen !
