### ISSUE TITLE
New options for the parallel_coordinates vcsaddons

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#476]
@doutriaux1 I post it here but it might not be the right place.
I would be interested in two functionalities for the parallel coordinates GM in vcs.

1/ For the plots showing biases, the plot as it is now is a little bit messy at the moment because we can have both positive and negative values (on one axis and across the axes):
![bias_parallel_coordinates](https://cloud.githubusercontent.com/assets/7254214/23560570/3ac5a234-003b-11e7-9675-9b37aca7638f.png)
It would be of great interest to display the zero value as an horizontal straight line (possibly at mid-height on the axes), with the range of values of each axis being [ -max(absolute(values)) : max(absolute(values)) ].

2/ I would like to show only the 'highlighted' colored simulations in the legend:
![cor_parallel_coordinates](https://cloud.githubusercontent.com/assets/7254214/23560309/405ae3f4-003a-11e7-8605-7906118e560b.png)
Here the interest of the spaghetti of grey lines is to show the spread of the CMIP5 models but in this case we don't need to (and actually can't) identify them. The legend contains too much information that is not usable.
Can we add a mechanism to select only the subset of simulations that we want to display in the legend?

Please give me your thoughts on those points. The first point has the highest priority for me. I really think it is a great way to display the summary statistics and I hope you guys are keen on investing a little bit more on that.

**Comment by jservonnat** [comment]
@doutriaux1 @gleckler1 I ping you to activate this issue ;). @doutriaux1 do you think it is feasible to add that to the GM?

**Comment by doutriaux1** [comment]
@jservonnat 
1- I'm guessing you can achieve that via template/ticks use the mticks to go accross the template ```python
t=vcs.createtemplate()
t.ytic1.x1=t.data.x1
t.ytic1.x2=t.data.x2
```
2- turn the legend off on template, and then draw it yourself then, using 
```python
import vcs
t=vcs.createtemplate()
t.legend.priority=0
# plot here
vcs.utils.drawLinesAndMarkersLegend(canvas, templateLegend, linecolors, linetypes, linewidths, markercolors, markertypes, markersizes, strings
, scratched=None, bg=False, render=True)
```

**Comment by jservonnat** [comment]
@doutriaux1 I've tried the 'plug and play' approach with the lines you gave but it didn't work.
Then I've tried the 'read the doc' method (together with the lines you gave) but couldn't find my way...

I would thus need some help to learn how to control VCS on those aspects... Could we plan a session together (visio) to get those things working?

**Comment by jservonnat** [comment]
@gleckler1 @durack1 @doutriaux1 Here is a teaser for you guys:
https://vesg.ipsl.upmc.fr/thredds/fileServer/IPSLFS/jservon/parallel_coordinates_metrics_figures/TeaserForPCMDI/parallel_coordinates_TeaserForPCMDI.html
The plots are made with an R script. The goal could be doing the same with the VCS script (but at least now I have something that we can use at IPSL).
