### ISSUE TITLE
Update install from source page

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#478]
The [Install-from-source](https://github.com/PCMDI/pcmdi_metrics/wiki/Install-from-source) page points to the `install_metrics.bash` file which was removed a long time ago. If we are supporting installations from source, this page needs to be updated so a user can install `cdms2`, `vcs` and the `PMP`
```
On 3/6/17, 6:57 AM, Doutriaux, Charles wrote:

    Hi Mark,
    
    Wow we need to update this very very old page.
    
    Here’s the correct way.
    In your python (with cdms2 and possibly vcs for graphics)
    
    git clone git://github.com/pcmdi/pcmdi_metrics
    cd pcmdi_metrics
    python setup.py install
    
    Voila!
    
    Let me know if you run into difficulties.
    
    C>
    
    On 3/5/17, 9:40 PM, Mark.Collier wrote:
    
        Hi I thought I would install PMs from source so that I have a working cdms2 environment, and currently I am doing development outside of an anaconda setup (hence source approach). However, when I try step 3 on the page:
    
        https://github.com/PCMDI/pcmdi_metrics/wiki/Install-from-source
    
        namely
    
        wget --no-check-certificate https://raw.githubusercontent.com/PCMDI/pcmdi_metrics/master/install_metrics.bash
    
        ​it fails with:
    
        Resolving raw.githubusercontent.com... 151.101.100.133
        Connecting to raw.githubusercontent.com|151.101.100.133|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2017-03-06 16:39:33 ERROR 404: Not Found.
    
        Is there something out-of-date or required to be able to download the install script?
    
        Thanks,
        Mark.
```

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 Haven't we abandoned support of installing from source?

**Comment by durack1** [comment]
@gleckler1 I think you're right, so we need to delete the page.. I see no reason why we'd want to continue to support this installation approach

**Comment by doutriaux1** [comment]
we should move it into a developer section

**Comment by durack1** [comment]
If we're not going to test and support it, we purge it, otherwise it gets too difficult

**Comment by doutriaux1** [comment]
well I'm testing it because that's how we install it when developing, no?

**Comment by durack1** [comment]
`install_metrics.bash` doesn't exist - so this page is just out of date altogether

**Comment by doutriaux1** [comment]
oh god! Yes that page is completely out of date... the correct way is setup.py install...

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 I'd probably muck this up if I tried to change

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  Do we want to remove 
https://github.com/PCMDI/pcmdi_metrics/wiki/Install-from-source
And just point users to conda?

**Comment by durack1** [comment]
@gleckler1 yep - it's the only supported path
