### ISSUE TITLE
ncar_cmip_direct_name_map, 'pr' maps to 'PRECC'

### ISSUE THREAD

**Issue by chengzhuzhang** [PCMDI/pcmdi_metrics#485]
Hi @doutriaux1  

I came across this ncar_cmip_direct_name_map list, where 'pr' is mapping to 'PRECC' in NCAR convention. However pr in CMIP stands for total precip flux, while PRECC stands for convective precip flux. 'pr'='PRECT'='PRECC'+'PRECL'. Not sure if this dictionary is still in use. Just a reminder here.

**Comment by doutriaux1** [comment]
@durack1 did you write this?

**Comment by durack1** [comment]
@chengzhuzhang @doutriaux1 yep that was me.

@chengzhuzhang [the file you have referred to](https://github.com/PCMDI/pcmdi_metrics/blob/master/examples/external-setups/NCAR/transform_ncar_clims_to_CMIP5_structure.py) was generated by @gleckler1 in his demos for NCAR.

Thanks for pointing out the `PR` equivalence, we actually do have this captured in the code [here](https://github.com/PCMDI/pcmdi_metrics/blob/master/examples/external-setups/NCAR/createXmlAndNcs.py#L76-L78) and [here](https://github.com/PCMDI/pcmdi_metrics/blob/master/examples/external-setups/NCAR/createXmlAndNcs.py#L142-L154) (there are also some other fields that require more than a single input)

We will need to revise these demos, and I believe they are now out of sync with the latest master branch.. The example data is also likely deprecated..

**Comment by durack1** [comment]
@chengzhuzhang it would make sense to generate a "mapping dictionary" for all these variable names, I had started that in https://github.com/PCMDI/pcmdi_metrics/issues/176, however, it seems to have been closed this rather than pursuing this further.. Feel free to kick something like this off, I would be more than happy to iterate over this with you

**Comment by gleckler1** [comment]
@chengzhuzhang @durack1  It would be great to set something up as part of the code base, not a GH table.    

One possibility would be to create a variable id mapping for all models.  We have a few nascent examples for several groups here:
https://github.com/PCMDI/pcmdi_metrics/tree/master/examples/external-setups

Starting with these, we could pull the variable_id mapping (+units and equations where variables are combined) across models into a common dictionary and build upon it, for example: 
https://github.com/PCMDI/pcmdi_metrics/tree/master/examples/external-setups/AllModstoCMIP
or something like that.   Once we get a thought out example started we can close this issue and just open new ones as additions are made.  
Thoughts?

**Comment by durack1** [comment]
@chengzhuzhang can you ping me where these mappings are located in the [ACME-Climate/acme_diags](https://github.com/ACME-Climate/acme_diags)?
