### ISSUE TITLE
possible simplification of pcmdi driver

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#492]
I used to have code to mask `bad` values after mask regridding via esmf/esmp I think @dnadeau4 fixed this and this code shouldn't be needed any longer.

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen I don't understand this issue.  Is it resolved?

**Comment by doutriaux1** [comment]
@gleckler1 it was mostly a memo for me to take a look if i can simplify the code. I'll double check today.

**Comment by gleckler1** [comment]
@doutriaux1   CD did you ever do this?   If y pls close.

**Comment by doutriaux1** [comment]
No I didn't remove it. It's not hurting anything except maybe performance. I'll take it out next week.
