### ISSUE TITLE
Cannot install with vcs 2.12

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#508]
```
(uvcdat-2.12) -bash-4.1$ conda install -f pcmdi_metrics -c conda-forge -c pcmdi
```

I created uvcdat 2.12 conda env then was trying to pmp in the env, but it seems like pmp limits to use certain version of vcs and vcsaddons as 2.10. 
 

```
Fetching package metadata ...............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - pcmdi_metrics -> vcs ==2.10
  - pcmdi_metrics -> vcsaddons ==2.10
```

**Comment by doutriaux1** [comment]
you're missing uvcdat channel!
```
conda install -f pcmdi_metrics -c conda-forge -c uvcdat -c pcmdi
```

**Comment by lee1043** [comment]
```
(uvcdat-2.12) -bash-4.1$ conda install -f pcmdi_metrics -c conda-forge -c uvcdat -c pcmdi
```
@doutriaux1  It still requires vcs 2.10.

```
Fetching package metadata .................
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - pcmdi_metrics -> vcs ==2.10
```

**Comment by lee1043** [comment]
My vcs version from conda list is:

```
(uvcdat-2.12) -bash-4.1$ conda list vcs
# packages in environment at /export/lee1043/anaconda2/envs/uvcdat-2.12:
#
vcs                       2.12             py27had75802_0    uvcdat
vcsaddons                 2.12             py27h7706516_0    uvcdat
```

**Comment by doutriaux1** [comment]
yes it is "pinned" you could use the nightlies which I believe do not enforce pinning, or try:
conda install pcmdi_metrics -c uvcdat/abel/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly --no-update-dependencies

**Comment by doutriaux1** [comment]
if you're happy with downgrading to 2.10 use:
```
conda install pcmdi_metrics  -c conda-forge -c uvcdat/label/v210 -c uvcdat -c pcmdi/label/nightly --no-update-dependencies
```

**Comment by lee1043** [comment]
@doutriaux1 

Should the [installation document](https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-Anaconda#installing-the-pcmdi-metrics-package-pmp) include uvcdat channel?

**Comment by lee1043** [comment]
@doutriaux1 installing nightly version of pmp works. Thanks.

**Comment by lee1043** [comment]
Installing PMP and latest VCS as nightly version (note for future record):

```conda create -n pmp_nightly -c uvcdat/label/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly -c pcmdi pcmdi_metrics```

**Comment by lee1043** [comment]
Attempt:
`conda install pcmdi_metrics -c cdat/label/nightly -c conda-forge -c cdat -c pcmdi/label/nightly -c pcmdi`

Error message:
```
libdrs-3.0-0.t 100% |############################################################################################| Time: 0:00:00 488.39 kB/s
vtk-cdat-8.0.1 100% |############################################################################################| Time: 0:00:03   7.83 MB/s
libcdms-3.0.1- 100% |############################################################################################| Time: 0:00:00  15.71 MB/s
output_viewer- 100% |############################################################################################| Time: 0:00:00  35.95 MB/s
cdp-1.3.3.2018 100% |############################################################################################| Time: 0:00:00  15.63 MB/s
cdat_info-8.0. 100% |############################################################################################| Time: 0:00:00   6.06 MB/s
cdms2-3.0-py27 100% |############################################################################################| Time: 0:00:00  15.86 MB/s
genutil-8.0.20 100% |############################################################################################| Time: 0:00:00  30.90 MB/s
cdutil-8.0.201 100% |############################################################################################| Time: 0:00:00  36.95 MB/s
vcs-8.0.2018.0 100% |############################################################################################| Time: 0:00:00  15.51 MB/s
pcmdi_metrics- 100% |############################################################################################| Time: 0:00:00  17.01 MB/s
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /export_backup/lee1043/anaconda2/envs/pmp_nightly_20180614/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.


LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /export_backup/lee1043/anaconda2/envs/pmp_nightly_20180614/bin/.gcc-post-link.sh
==> script messages <==
<None>
```

@doutriaux1 any advice please?

**Comment by lee1043** [comment]
conda create -n pmp_nightly_20180614-3 -c cdat/label/nightly -c pcmdi/label/nightly -c conda-forge -c cdat -c pcmdi pcmdi_metrics python=2.7

**Comment by lee1043** [comment]
Installing instruction at https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-Anaconda needs to be updated

**Comment by gleckler1** [comment]
@doutriaux1 @lee1043  Probably good to plan a release soon because its not great to point to a moving target.

**Comment by durack1** [comment]
@gleckler1 set a target date, https://github.com/PCMDI/pcmdi_metrics/milestones

**Comment by doutriaux1** [comment]
Let's finish the tweaks for @lee1043 jsons tomorrow and release tomorrow then.

**Comment by gleckler1** [comment]
@doutriaux1 @lee1043 @durack1  OK, this will be another minor (low profile) release - 1.1.3 ... at least since 1.1.2 we've added Wang's Monsoon precipitation index and Curt's diurnal cycle codes.

**Comment by doutriaux1** [comment]
@gleckler1 it should be 1.2 the last digit is supposed to indicate "patches", these are actually new features, which we can consider as "minor"

**Comment by durack1** [comment]
@doutriaux1 if we want to go down the py2 AND py3 path, this is something that we need to discuss.. It'd be nice to have both versions available for users

**Comment by doutriaux1** [comment]
@durack1 py2 and py3 are both available, you're right. It's kind of major tooo, might want to up to 2.0? Plus we will introduce the cdat-forge channel

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 Agreed with 1.2.  Not ready for 2.0 because additions of new metrics is nominal.    GREAT to introduce the cdat-forge channel in this release!

**Comment by gleckler1** [comment]
@lee1043
