### ISSUE TITLE
pmp-1.1.2.yml broken

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#514]
This is the output when attempting to generate a "canned" environment:
```
[durack1@oceanonly pcmdi_metrics]$ conda env create -f recipes/conda-envs/pmp-1.1.2.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .................

ResolvePackageNotFound:
  - esmf 7.0.0 6
```

**Comment by durack1** [comment]
@doutriaux1, I'm a bit confused by this the [`pmp-1.1.2.yml` shows](https://github.com/PCMDI/pcmdi_metrics/blob/master/recipes/conda-envs/pmp-1.1.2.yml#L3-L10):
```
channels:
- !!python/unicode
  'pcmdi'
- !!python/unicode
  'uvcdat'
- !!python/unicode
  'conda-forge'
- !!python/unicode
'defaults'
...
```
and [further down](https://github.com/PCMDI/pcmdi_metrics/blob/master/recipes/conda-envs/pmp-1.1.2.yml#L44-L45):
```
...
- !!python/unicode
'esmf=7.0.0=6'
...
```
This package is available on `conda-forge` for `linux-64` as noted [here](https://anaconda.org/conda-forge/esmf/files)

So this yml should work, right?

**Comment by durack1** [comment]
conda-forge have just changed the labels for a number of packages from the default `main` to `broken`, this is causing grief with this `pmp-1.1.2.yml` file:
![171121_brokencondaforge](https://user-images.githubusercontent.com/3229632/33091839-19cc0d16-cead-11e7-86ce-c23d0d22d5f6.png)

**Comment by durack1** [comment]
The issue has been *almost* fixed by adding the new channels and labels:
```
name: pmp-1.1.2a
channels:
- !!python/unicode
  'pcmdi'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'conda-forge/label/broken'
- !!python/unicode
  'uvcdat'
- !!python/unicode
  'uvcdat/label/v210'
- !!python/unicode
  'uvcdat/label/v2.10'
- !!python/unicode
  'defaults'
dependencies:
...
```
But it really needs to be cleaned up and a new `*.yml` file generated, we should combine this with a `1.1.3` push after the thanksgiving break

**Comment by durack1** [comment]
Attached are 2 files that have been working on ocean
[pmp_10172017.yml](https://github.com/PCMDI/pcmdi_metrics/files/1493455/pmp_10172017.yml.txt)
[pmp1.1.2.yml](https://github.com/PCMDI/pcmdi_metrics/files/1493457/pmp1.1.2.yml.txt)

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 I guess it will be the next release (next week?) where we finally get a stable yml via release on PMP-forge or CDAT-forge... i.e., 1.1.2 yml is not going to get fixed so now closing this.

**Comment by durack1** [comment]
@doutriaux1 it would be great to push out a new release, so we're up-to-date

**Comment by doutriaux1** [comment]
let me fix them. I'm in the process of fixing cdat yam ls as well! And yes next release with cdat-forge will be so nice!
