### ISSUE TITLE
Update logos

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#517]
Add PMP and PCMDI logos [share/pcmdi](https://github.com/PCMDI/pcmdi_metrics/tree/master/share/pcmdi)

**Comment by durack1** [comment]
Address @doutriaux1 comments in https://github.com/PCMDI/pcmdi_metrics/pull/518#issuecomment-346211193

**Comment by lee1043** [comment]
![pr access1-0_djf](https://user-images.githubusercontent.com/17091564/33142364-1320630e-cf6b-11e7-9d29-33383f62dbd1.png)

@durack1 @gleckler1 @doutriaux1 
Candidate plot with new logos. 
For PCMDI, 200x65 used without resizing. For CDAT, size shrinked 0.08 times.

**Comment by gleckler1** [comment]
@lee1043 @durack1 @doutriaux1  I like both new logos.  Maybe put PCMDI in upper right and CDAT in lower left... CDAT is pretty close to the legend units.

**Comment by lee1043** [comment]
@gleckler1 What about the locations of logos?

**Comment by gleckler1** [comment]
@lee1043 Currently PCMDI is in upper left... it could go to upper right.   Similarly CDAT could go in lower left.  But the main reason I am suggesting this is to get the logo away from the (mm d-1)... alternatively the units could get moved to be centered with colorbar or in lower left.   I don't have strong opinions about this so happy to follow your lead.

**Comment by lee1043** [comment]
@gleckler1 Like your idea. Thanks!

**Comment by durack1** [comment]
@lee1043 glad you were able to use these straight away, I’ll regenerate the CDAT logo at a smaller size, the 200px seems reasonable.. great!

**Comment by lee1043** [comment]
@durack1 Thanks. I had to cut out the Full name of CDAT under the logo, because resizing make the letter look bad.

**Comment by durack1** [comment]
@lee1043, yeah there are some resize jaggies associated with the CDAT logo, it looks great, but with targeted sizes it’ll look cleaner. The native 200px PCMDI logo is as sharp as the text, so we’ve achieved exactly what I was hoping, this looks great!

**Comment by lee1043** [comment]
![pr access1-0_djf](https://user-images.githubusercontent.com/17091564/33143966-6b2f5eba-cf70-11e7-97ab-ceb5ee7ccfc0.png)

suggestion of @gleckler1

**Comment by lee1043** [comment]
![pr access1-0_djf](https://user-images.githubusercontent.com/17091564/33151843-97160790-cf8e-11e7-9beb-aeac7d375fb9.png)

@gleckler1  Logo location changed.
