### ISSUE TITLE
TypeError: load_default_args

### ISSUE THREAD

**Issue by wk1984** [PCMDI/pcmdi_metrics#525]
I have installed PMP by using conda:

conda install -c pcmdi/label/nightly pcmdi_metrics

Also, I tested "which pcmdi_metrics_driver.py" to confirm whether it was installed successfully.

All things look good. However, when I used "pmp_demo_1.py" to run the demo, it reported a TypeError like:

===============
Traceback (most recent call last):
  File "/Users/kangwang/anaconda2/envs/PCMDI/bin/pcmdi_metrics_driver.py", line 208, in <module>
    parser = pcmdi_metrics.driver.pmp_parser.PMPParser()
  File "/Users/kangwang/anaconda2/envs/PCMDI/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_parser.py", line 8, in __init__
    super(PMPParser, self).__init__(pcmdi_metrics.driver.pmp_parameter.PMPParameter, *args, **kwargs)
  File "/Users/kangwang/anaconda2/envs/PCMDI/lib/python2.7/site-packages/cdp/cdp_parser.py", line 25, in __init__
    self.load_default_args(default_args_file)
TypeError: load_default_args() takes exactly 1 argument (2 given)
You can now look at the results in: ./pmp_demo/simple-test1/
===============

I searched but don't find any solution.

Thank you.

**Comment by doutriaux1** [comment]
You will need to get the package that was updated just shortly and cdp > = 1.2.2 and the cia package

Conda create -n pmp -c uvcdat/label/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly -c pcmdi pcmdi_metrics cia

should do the trick. Please let us know.

C.

**Comment by wk1984** [comment]
I used the command you @doutriaux1  suggested to create a new conda environment.

However, it is still the same problem.

-----------

We will now run the pmp using this parameter file
To do so we are using the follwoing command
pcmdi_metrics_driver.py -p /Users/kangwang/anaconda2/envs/pmp/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
Traceback (most recent call last):
  File "/Users/kangwang/anaconda2/envs/pmp/bin/pcmdi_metrics_driver.py", line 208, in <module>
    parser = pcmdi_metrics.driver.pmp_parser.PMPParser()
  File "/Users/kangwang/anaconda2/envs/pmp/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_parser.py", line 8, in __init__
    super(PMPParser, self).__init__(pcmdi_metrics.driver.pmp_parameter.PMPParameter, *args, **kwargs)
  File "/Users/kangwang/anaconda2/envs/pmp/lib/python2.7/site-packages/cdp/cdp_parser.py", line 28, in __init__
    self.load_default_args(default_args_file)
TypeError: load_default_args() takes exactly 1 argument (2 given)
You can now look at the results in: ./pmp_demo/simple-test1/
[Press enter]

**Comment by doutriaux1** [comment]
my bad i didn't realize you were using the demo. I need to update this script as well. I will ping you as soon as this is corrected.

**Comment by liuye923** [comment]
I also tried the demo script and got the same error. I solved it by adding a "_" before "load_default_args" in cdp_parser.py to make it a private function. However, I do not know the reason but it works in my case.

**Comment by jcovert1994** [comment]
I downloaded the latest version of pmp using anaconda and the following command as suggested on the install page:

$ conda install pcmdi_metrics -c conda-forge -c uvcdat -c uvcdat/label/v210 -c pcmdi

I got the same error as noted in this issue so I then proceeded to install it using doutriaux1's suggested command:

Conda create -n pmp -c uvcdat/label/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly -c pcmdi pcmdi_metrics cia

When running the demo, I get the following error...

CDMS system error: No such file or directory
CDMS I/O error: Opening file /home/jason/PycharmProjects/pmp/demo/pmp_demo/cmip5clims_metrics_package-amip/sftlf_ACCESS1-0_Amon_amip_r0i0p0_198001-200512-clim.nc
Traceback (most recent call last):
  File "/home/jason/.conda/envs/pmp_nightly/bin/pcmdi_metrics_driver.py", line 385, in <module>
    driver.run_diags()
  File "/home/jason/.conda/envs/pmp_nightly/bin/pcmdi_metrics_driver.py", line 44, in run_diags
    self.obs_dict = self.load_obs_dict()
  File "/home/jason/.conda/envs/pmp_nightly/bin/pcmdi_metrics_driver.py", line 77, in load_obs_dict
    cust_obs_json_file = open(self.parameter.custom_observations)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I have done some troubleshooting and the issue appears to be related inputting custom observations. I am stuck here. Any assistance will be much appreciated.

**Comment by wjchen1203** [comment]
I download the latest version of pmp by using anaconda. I got similar problem as previous users.
When i run the demo, i got the following problem:

$ python pmp_demo_1.py
============
Traceback (most recent call last):
  File "/home/xb37/anaconda2/bin/pcmdi_metrics_driver.py", line 196, in <module>
    parser = pcmdi_metrics.driver.pmp_parser.PMPParser()
  File "/home/xb37/anaconda2/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_parser.py", line 8, in __init__
    super(PMPParser, self).__init__(pcmdi_metrics.driver.pmp_parameter.PMPParameter, *args, **kwargs)
  File "/home/xb37/anaconda2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 32, in __init__
    self.load_default_args(default_args_file)
TypeError: load_default_args() takes exactly 1 argument (2 given)
You can now look at the results in: /home/xb37/PCMDI/pcmdi_metrics-master/demo/pmp_demo/simple-test1/
========================


I am running pmp under the base environment. Would  it be the reason that cause this problem?

Thanks so much for your answer, im looking forward to hear from you!

Grace

**Comment by doutriaux1** [comment]
@wjchen1203 apologies for the delay on this, I will update the demo by the end of the week.

**Comment by doutriaux1** [comment]
@gleckler1 @durack1 is this demo still relevant anyway?

**Comment by Cypresslin** [comment]
I did a quick test for this by running the pmp_demo_1.py script directly, it looks like the problem lies within the pcmdi_metrics/driver/pmp_parser.py.

it's trying to call the load_default_args function in PMPParser, which only takes one argument, instead of the one in CDPParser:

    def load_default_args(self):
 
Thus it cause this error message:

    TypeError: load_default_args() takes exactly 1 argument (2 given)

Remove / rename the load_default_args() in pmp_parser.py (or even make to take two args) might help, but I will just stop right here due to my limited knowledge on this.

**Comment by wjchen1203** [comment]
Hi, @doutriaux1 just wanna ask if there is any updated about this issue?

**Comment by doutriaux1** [comment]
@gleckler1 @durack1 should fix this demo? Or remove it? @wjchen1203 is asking.

**Comment by doutriaux1** [comment]
yeah it's an old demo though... I'll fix it on Thursday.

**Comment by gleckler1** [comment]
We are in the process of overhauling the PMP demos.  The existing demo and demo1 should be considered deprecated - we will note that.   The new suite of demos will be ready mid to late September.
