### ISSUE TITLE
JSON structure

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#531]
I am loading a [JSON file](https://github.com/eguil/ENSO_metrics/blob/master/scripts/test_MC1_all.json) that has json structure described in it, but the Json structure is not appreciated when getting axes.

```
json_files= ['./test_MC1_all.json']
J = pcmdi_metrics.pcmdi.io.JSONs(json_files)
J.getAxisList()
```

In the sample JSON file, `json_structure` is given as below:
```
    "json_structure": [
        "type",
        "data",
        "metric",
        "item",
        "value or description"
    ],
```

But when run above code, below information is returned, which is completely different than above.

```
[   id: variable
    Length: 1
    First:  test
    Last:   test
    Python id:  0x111c0fd10,    id: model
    Length: 2
    First:  model
    Last:   obs
    Python id:  0x111c0f810,    id: reference
    Length: 21
    First:  ACCESS1-0
    Last:   Tropflux
    Python id:  0x111c0fcd0,    id: rip
    Length: 8
    First:  lhf
    Last:   thf
    Python id:  0x111c0f7d0,    id: region
    Length: 9
    First:  EnsoAlphaLhf
    Last:   EnsoSeasonality
    Python id:  0x111c0f990,    id: statistic
    Length: 2
    First:  metric_values
    Last:   raw_values
    Python id:  0x111c0fbd0,    id: season
    Length: 22
    First:  method_to_compute_diagnostic
    Last:   units
    Python id:  0x111c0f410]
```

**Comment by doutriaux1** [comment]
@lee1043 it works for me in nightly, can you please check using nightly?
```
conda install -f -c conda-forge -c cdat -c pcmdi/label/nightly -c pcmdi pcmdi_metrics
```

**Comment by lee1043** [comment]
@doutriaux1 thanks for following up this. `J.getAxisList()` returns below after installing pmp nightly, which I don't see any difference comparing to above, especially regarding the axis id. It does not match to the given [json structure](https://github.com/eguil/ENSO_metrics/blob/15661707d9b52846f1e09a3a0df7f1de4e517c36/scripts/test_MC1_all.json#L11503) 

```
[   id: variable
    Length: 1
    First:  test
    Last:   test
    Python id:  0x10c117750,    id: model
    Length: 2
    First:  model
    Last:   obs
    Python id:  0x10c117490,    id: reference
    Length: 21
    First:  ACCESS1-0
    Last:   Tropflux
    Python id:  0x10c1174d0,    id: rip
    Length: 8
    First:  lhf
    Last:   thf
    Python id:  0x104ea0890,    id: region
    Length: 9
    First:  EnsoAlphaLhf
    Last:   EnsoSeasonality
    Python id:  0x10c1177d0,    id: statistic
    Length: 2
    First:  metric_values
    Last:   raw_values
    Python id:  0x10c117510,    id: season
    Length: 22
    First:  method_to_compute_diagnostic
    Last:   units
    Python id:  0x10c117590]
```

**Comment by gleckler1** [comment]
@lee1043 @doutriaux1  Since we need this now to advance the ENSO project with our collaborators, is there an alternate json_structure we could use as a temporary kludge until this can get fixed?   I recall with the modes of variability we were able to do some reverse engineering... i.e., able to get the results even though they were not labeled properly.

**Comment by doutriaux1** [comment]
@lee1043 are you using a nightly pmp? It works for me there's even a test with YOUR json file see:

https://github.com/PCMDI/pcmdi_metrics/pull/533

**Comment by lee1043** [comment]
@doutriaux1 yes I am using nightly pmp. And I still have same issue with cdat8. Can you please copy and paste your result here when you do `J.getAxisList()`? I am curious to see. Thanks!

**Comment by doutriaux1** [comment]
@lee1043 ping me when you get in, we'll fix this. I'm suspecting you have a pcmdi_metrics installed somewhere please paste the result of:

```python
import pcmdi_metrics
print reload(pcmdi_metrics)
```

**Comment by lee1043** [comment]
```
-bash-4.1$ source activate cdat8
(cdat8) -bash-4.1$ python
Python 2.7.14 | packaged by conda-forge | (default, Mar 30 2018, 18:16:04) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```
>>> import pcmdi_metrics
>>> print reload(pcmdi_metrics)
<module 'pcmdi_metrics' from '/export_backup/lee1043/anaconda2/envs/cdat8/lib/python2.7/site-packages/pcmdi_metrics/__init__.pyc'>
```
@doutriaux1 hope this help to diagnose the problem. thanks!

**Comment by lee1043** [comment]
issue solved with help from @doutriaux1 by replacing 
```
J = pcmdi_metrics.pcmdi.io.JSONs(json_files)
```
to 
```
J = pcmdi_metrics.io.base.JSONs(json_files)
```

**Comment by doutriaux1** [comment]
@lee1043 thanks for confirming, indeed you should use the base class, I believe the one in `pcmdi` has been tweaked to reflect the structure produced by the `compute_pcmdi_metrics` script.

**Comment by lee1043** [comment]
@doutriaux1 okay, thanks for confirming! 👍
