### ISSUE TITLE
Continents coastal line in Portrait plot?

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#532]
Somehow a portrait plot that I generated has a line that looks like part of continents coastal line. I have no idea where it come from. 

![index](https://user-images.githubusercontent.com/17091564/38150565-62d7352c-3414-11e8-866e-8455b628cd62.png)

input JSON:
https://github.com/eguil/ENSO_metrics/blob/master/scripts/test_MC1_all.json

Python script: 
[ENSO_PP-Test.py.txt](https://github.com/PCMDI/pcmdi_metrics/files/1864560/ENSO_PP-Test.py.txt)

**Comment by gleckler1** [comment]
@lee1043  wow!   Thats a new feature... we'll have to think how to use that one ;-)

**Comment by doutriaux1** [comment]
@lee1043 I did see and fixed this. Are you using CDAT 8.0?

**Comment by lee1043** [comment]
@doutriaux1 I was using 3.0. I will try with 8.0.

**Comment by lee1043** [comment]
@doutriaux1 this issue was gone with using cdat 8.0. Thanks.
