### ISSUE TITLE
show values in Portrait Plots Cells

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#547]
@lee1043 had this idea.

**Comment by lee1043** [comment]
Below is for example that I created for clarification. Thanks @doutriaux1 for following up on this.

![enso_mc1_pp_matplotlib_test1_annotatenormalizednumbers](https://user-images.githubusercontent.com/17091564/39770510-15042054-52a4-11e8-9676-132b1482f822.png)

**Comment by doutriaux1** [comment]
@lee1043 I'm almost there, should have an example for you shortly

**Comment by lee1043** [comment]
@doutriaux1 awesome. Thanks. One question: below is same as above, but showing different numbers. In above plot, numbers are corresponding to the color bar, which are values getting after normalizing by median of each row. In below plot, color bar is corresponding to the normalized value, but numbers are from actual value BEFORE normalizing. Would it be possible to show as below as well?

![enso_mc1_pp_matplotlib_test2_annotateactualnumbers](https://user-images.githubusercontent.com/17091564/39770812-f8d07670-52a4-11e8-82aa-21ca23ffc647.png)

**Comment by lee1043** [comment]
@gleckler1 might be interested as well

**Comment by doutriaux1** [comment]
@lee1043 the `different` numbers options is doable, thanks for pointing it out now. I will add this.

**Comment by doutriaux1** [comment]
@lee1043 @gleckler1 is that what you want?
![testvaluesonportrait](https://user-images.githubusercontent.com/2781425/39775685-804569a4-52b3-11e8-9ef3-ed220e767c89.png)

**Comment by doutriaux1** [comment]
@lee1043 I let you control the font, color, angle, etc.. I locked the font size though, I shrink the size until the largest text fits in its cell.

**Comment by gleckler1** [comment]
@doutriaux1 @lee1043 Hey that is nifty... will it work in each triangle?  Also, as JW indicated normally we'll want the numbers to be different than the colors (e.g., one will be normalized the other not).

**Comment by doutriaux1** [comment]
@lee1043 another one where I forced the plot values to be what I want (value+2. here)

**Comment by doutriaux1** [comment]
@gleckler1 as shown above we can control the numbers

**Comment by doutriaux1** [comment]
@gleckler1 it should work in triangles

**Comment by doutriaux1** [comment]
@gleckler1 showing first out of triangles here
![testvaluesonportrait](https://user-images.githubusercontent.com/2781425/39776076-a829ec8c-52b4-11e8-8f7e-6e80824ec2f7.png)

**Comment by durack1** [comment]
Nice! @lee1043 @doutriaux1, I've used multiple colours when plotting these things against varied backgrounds, so the text is visible, so white against dark colours and black against light colours

**Comment by doutriaux1** [comment]
@durack1 darn you! I'll add an option to control the colors. @lee1043 @durack1 do you have an algorithm to pick the best possible color?

**Comment by doutriaux1** [comment]
@lee1043 @gleckler1 @durack1 ok, I looked into the dark/light color bit, it might take a bit of time to implement. Do you need this urgently?

**Comment by lee1043** [comment]
@doutriaux1 in my matplotlib example, you will see some text with white over dark background while rest text with black over light background. I was using loop for placing each numbers where I controlled its color. I am not sure how this would work with your VCS code. 

No urgency for text color for me. I will start chipping away with the new branch you pointed. Thanks!

**Comment by doutriaux1** [comment]
@lee1043 Im' 90% done with an auto detection of background color... Will let you know when I updated the branch

**Comment by lee1043** [comment]
@doutriaux1 awesome, thanks!

**Comment by doutriaux1** [comment]
@lee1043 I pushed it into the branch, is this what you want:
![testvaluesonportrait](https://user-images.githubusercontent.com/2781425/39787184-f6912cfe-52d8-11e8-919e-ac5a54e5b8e5.png)

**Comment by doutriaux1** [comment]
@lee1043 right now it's only black or white let me add an option to control these two colors

**Comment by lee1043** [comment]
@doutriaux1 correct, thanks!

**Comment by lee1043** [comment]
@doutriaux1 I am getting error for `P.PLOT_SETTINGS.values.show = True` as below.

code:
```
# PARAMETERS STUFF
P = pcmdi_metrics.graphics.portraits.Portrait()

P.PLOT_SETTINGS.values.show = True
P.PLOT_SETTINGS.values.text.angle = -45
P.PLOT_SETTINGS.values.lightcolor = "green"
P.PLOT_SETTINGS.values.darkcolor = "red"
```

error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-4fe68c9872a0> in <module>()
      2 P = pcmdi_metrics.graphics.portraits.Portrait()
      3 
----> 4 P.PLOT_SETTINGS.values.show = True
      5 P.PLOT_SETTINGS.values.text.angle = -45
      6 P.PLOT_SETTINGS.values.lightcolor = "green"

AttributeError: 'Plot_defaults' object has no attribute 'values'
```

I updated my pmp nightly as below:
```
(cdat8_nightly) GS15-9419740:anaconda2 lee1043$ conda list pcmdi_metrics
# packages in environment at /Users/lee1043/anaconda2/envs/cdat8_nightly:
#
pcmdi_metrics             1.1.2.2018.05.08.00.17.gd33119d          py27_0    pcmdi/label/nightly
```

Any advice, please. Thanks!

**Comment by doutriaux1** [comment]
hum... looks like it didn't make it in... Did you install manually in your env as well? Sometime they conflict.

**Comment by lee1043** [comment]
@doutriaux1 yes I manually installed pmp nightly in my existing env. As version number says last updated at 5/8 I thought I have the right one.

**Comment by doutriaux1** [comment]
try 
```
rm -rf /Users/lee1043/anaconda2/envs/cdat8_nightly/lib/python-2.7/site-packages/pcmdi_metrics*
conda install -c pcmdi/label/nightly -c cdat/label/nightly -c cdat -c pcmdi pcmdi_metrics
```
let me know

**Comment by lee1043** [comment]
@doutriaux1 thanks for help, it works nicely!
![index](https://user-images.githubusercontent.com/17091564/39887452-216239ae-5447-11e8-9c80-3412e0f88c69.png)

**Comment by gleckler1** [comment]
@doutriaux1 @lee1043 Great to have this capability.   It will be interesting to see how well it works with clickable :-)

**Comment by lee1043** [comment]
@doutriaux1 Could you please provide example code for control numbers? thanks!

**Comment by doutriaux1** [comment]
@lee1043 see: https://github.com/PCMDI/pcmdi_metrics/blob/master/tests/test_pmp_portrait_values_on.py#L109
