### ISSUE TITLE
add JwL's variability stats to PMP

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#552]
from this https://github.com/PCMDI/modes_of_variability/blob/master/devel/variability_mode/lib/calc_stat.py

add to https://github.com/PCMDI/pcmdi_metrics/tree/master/src/python/pcmdi

Consult with @doutriaux1 on how best to do this... one file as in JwL's code or an individual file for each statistic?
@lee1043

**Comment by gleckler1** [comment]
@doutriaux1 We don't have a PR for the @lee1043 variability modes, so for 1.2.0 we can leave this until 1.3.0

**Comment by lee1043** [comment]
Currently working on it: https://github.com/PCMDI/pcmdi_metrics/pull/623

**Comment by lee1043** [comment]
Variability code uses `eofs` and `scipy` which are currently not included as PMP dependencies. Should we consider including them or let users do their homework by installing those libraries by themselves? @gleckler1 what do you think?

**Comment by gleckler1** [comment]
@lee1043 Good question.  I think for right now its better to not include them.

**Comment by durack1** [comment]
Just chiming in, I'm pretty sure that with the dependencies of `cdms` you're already going to have `scipy`, `eofs` is unlikely

Take a peek at https://github.com/CDAT/cdms/blob/master/recipe/meta.yaml.in#L32-L47

**Comment by lee1043** [comment]
@durack1 you are correct for the `scipy`, thanks for pointing it out.

**Comment by lee1043** [comment]
[PR](https://github.com/PCMDI/pcmdi_metrics/pull/623) merged.
