### ISSUE TITLE
PMP parser help does not follow line change

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#553]
I would like to make the description given from PMPParser help nicely using line changer, `\n`, but the code does not work with the line changer.

```
from __future__ import print_function
from pcmdi_metrics.driver.pmp_parser import PMPParser

P = PMPParser(description='description_line_change_test')

P.add_argument("-v", "--var",
                   type=str,
                   default='testName',
                   help="Line1\n"
                        +"Line2\n"
                        +"      option1\n"
                        +"      option2\n"
                        +"Additional_description")

param = P.get_parameter()

print(param.variability_mode)
```

Screen printed output for `-h` option:
```
$ p test.py -h
```
```
usage: test.py [-h] [--parameters PARAMETERS]
               [--diags OTHER_PARAMETERS [OTHER_PARAMETERS ...]] [-v VAR]

description_line_change_test

optional arguments:
  -h, --help            show this help message and exit
  --parameters PARAMETERS, -p PARAMETERS
  --diags OTHER_PARAMETERS [OTHER_PARAMETERS ...], -d OTHER_PARAMETERS [OTHER_PARAMETERS ...]
                        Path to other user-defined parameter file. (default:
                        None)
  -v VAR, --var VAR     Line1 Line2 option1 option2 Additional_description
                        (default: testName)
```

Following `--var VAR`, `Line1 Line2 option1 option2 Additional_description` are listed on the same line.

**Comment by lee1043** [comment]
@doutriaux1 @zshaheen any advice for me, please? Thanks!

**Comment by lee1043** [comment]
[Solution for argparse](https://stackoverflow.com/questions/3853722/python-argparse-how-to-insert-newline-in-the-help-text) is not helpful for pmpparser

**Comment by zshaheen** [comment]
I don't really have a working pmp env, but try the following or something similar:
```python
from argparse import RawTextHelpFormatter
p = PMPParser(description='description_line_change_test', formatter_class=RawTextHelpFormatter)
```
All of the CDP parsers inherit from `ArgumentParser`, which is what your example does. So this might work.

**Comment by lee1043** [comment]
@zshaheen thanks for your reply. Unfortunately that gives error as below:
```
Traceback (most recent call last):
  File "test_pmpparser.py", line 6, in <module>
    P = PMPParser(description='description_line_change_test',formatter_class=RawTextHelpFormatter)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180622/lib/python2.7/site-packages/pcmdi_metrics/driver/pmp_parser.py", line 10, in __init__
    os.path.join(sys.prefix, "share", "cia", "DefArgsCIA.json"), *args, **kwargs)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180622/lib/python2.7/site-packages/cdp/cdp_parser.py", line 31, in __init__
    *args, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'formatter_class'
```
which seems like the `formatter_class` is not recognizable for PMPParser.

**Comment by zshaheen** [comment]
I realized that we had `formatter_class=argparse.ArgumentDefaultsHelpFormatter` be the default formatter class for `cdp_parser`. I've just removed this and tested with your example and everything works. Please get the latest code from master.

We shouldn't even have had a default value for this. When we do, users like yourself cannot overwrite it. And the default help displayed isn't so different that the one used by `ArgumentDefaultsHelpFormatter`.

**Comment by doutriaux1** [comment]
@zshaheen I did add this, why do you remove it? w/o it the `--help` does NOT show the default values, that's bad.

**Comment by doutriaux1** [comment]
@zshaheen yes that's the way to go, overwrite the default if needed (like here)

**Comment by lee1043** [comment]
@doutriaux1 @zshaheen thanks for following up. Will it be available in pmp nightly version soon?

**Comment by doutriaux1** [comment]
@lee1043 it doesn't require any change to cdp, just add it to your script, right @zshaheen ?

**Comment by zshaheen** [comment]
You'll need the latest cdp on master. So clone the cdp repo and manually install it with `python setup.py install`. If you have any issues, let me know.

So Jiwoo, after you update the example I have here would work: https://github.com/PCMDI/pcmdi_metrics/issues/553#issuecomment-400778434

**Comment by doutriaux1** [comment]
@zshaheen master should be in nightly. Did you have to change anything for @lee1043 stuff to work?

**Comment by doutriaux1** [comment]
ngihtlies are at: https://anaconda.org/cdat/cdp/files

Looks like a few push went straight into master @zshaheen 😉

**Comment by zshaheen** [comment]
@doutriaux1 Yes, I did change some stuff in CDP for Jiwoo's example to work. Nothing was changed in pmp.

**Comment by lee1043** [comment]
@zshaheen @doutriaux1 yay! The line change works nicely after I updated cdp. Many thanks to @zshaheen and @doutriaux1 👍

**Comment by gleckler1** [comment]
@lee1043  I think we can close this issue now... do you agree?

**Comment by lee1043** [comment]
@gleckler1 Of course. Thanks for reminding!
