### ISSUE TITLE
include in share a json file with model listing for each generation of CMIP for historical/20c3m, picontrol and AMIP...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#555]
Logical place for this json file will be https://github.com/PCMDI/pcmdi_metrics/tree/master/share

**Comment by gleckler1** [comment]
@lee1043 Ok this is in master so from a parameter file you can get all possible models via:
f  = open(sys.prefix + "/share/pmp/cmip_model_list.json")
possible_mod_dic = json.load(f)
modnames = possible_mod_dic[MIP][experiment]

**Comment by durack1** [comment]
@gleckler1 @lee1043 just FYI and in preparation, we also have the listing of CMIP6 contributing models found in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json - those which include an `activity_participation = [*, CMIP, *]` will be providing DECK (piControl, historical, and AMIP) simulations
