### ISSUE TITLE
include working example param files...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#559]
@doutriaux1 A fundamental part of the PMP documentation depends on having example parameter files that a user can **run out-of the box**... for 1.1.3 that will include mean climate, monsoon_wang,  diurnal_covey, and possibly compute_clims.   These param files go in https://github.com/PCMDI/pcmdi_metrics/tree/master/examples/parameter_files.   PG is working on these documentation-ready examples.    

For them to run **out-of-the-box** we need to provide sample data.   PG working on tar file to provide to CD to include as part of https://github.com/PCMDI/pcmdi_metrics/blob/master/share/test_data_files.txt

**Comment by doutriaux1** [comment]
hum... `out_of_the_box` it not going to happen until we agree on a way to distribute obs in a standard way.
