### ISSUE TITLE
tag and conda-forge Eric and Jiwoo external code.

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#564]
@lee1043 @gleckler1 can you please point me to it.

**Comment by doutriaux1** [comment]
@gleckler1 @durack1 @lee1043 is that the correct repo/tag:

https://github.com/eguil/ENSO_metrics/releases/tag/v0.1

**Comment by durack1** [comment]
https://github.com/eguil/ENSO_metrics/releases/tag/v0.1.1 might be the latest

**Comment by gleckler1** [comment]
@doutriaux1 Yes

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 @lee1043  Yes v0.1.1 seems to be latest.  How goes the pmp-forge hook-up?

**Comment by lee1043** [comment]
yes, v0.1.1 is latest
