### ISSUE TITLE
JSON class not loading compliant file

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#569]
@doutriaux1  Attached file (without the .txt) can't be read with 
J = pcmdi_metrics.pcmdi.io.JSONs(inpath)

(pmp_cdat8) bash-4.1$ python -i portrait_test.py 
Traceback (most recent call last):
  File "portrait_test.py", line 12, in <module>
    J = pcmdi_metrics.pcmdi.io.JSONs(inpath)
  File "/export/gleckler1/anaconda2/envs/pmp_cdat8/lib/python2.7/site-packages/pcmdi_metrics/pcmdi/io.py", line 57, in __init__
    ignored_keys=ignored_keys,
  File "/export/gleckler1/anaconda2/envs/pmp_cdat8/lib/python2.7/site-packages/pcmdi_metrics/io/base.py", line 491, in __init__
    self.addJson(fnm)
  File "/export/gleckler1/anaconda2/envs/pmp_cdat8/lib/python2.7/site-packages/pcmdi_metrics/pcmdi/io.py", line 61, in addJson
    f = open(filename)

[monsoon-wang_CMIP5_historical-regrid2_regrid2_2018-07-19-10-58-22.json.txt](https://github.com/PCMDI/pcmdi_metrics/files/2279786/monsoon-wang_CMIP5_historical-regrid2_regrid2_2018-07-19-10-58-22.json.txt)

**Comment by gleckler1** [comment]
@lee1043 Any ideas why this does not work after removing the ".txt" from the attached json file?

**Comment by lee1043** [comment]
@gleckler1 could you please point where I can find the portrait_test.py?

**Comment by gleckler1** [comment]
@lee1043 This is it...

import glob
import json
import os, sys
import pcmdi_metrics

inpath = '/work/lee1043/cdat/pmp/pmp_results/tree_v0.3/pmp_v1.1.2/metrics_results/monsoon/monsoon_wang/cmip5/historical/test1/monsoon-wang_CMIP5_historical-regrid2_regrid2_2018-07-19-10-58-22.json'

J = pcmdi_metrics.pcmdi.io.JSONs(inpath)
print J.keys()

**Comment by lee1043** [comment]
@gleckler1 could you please replace bottom two lines to below and give a try?
```python
J = pcmdi_metrics.io.base.JSONs([inpath])
print(J.getAxisIds())
```
For me I see below as result.
```python
['variable', 'model', 'domain', 'statistic']
```

**Comment by lee1043** [comment]
@gleckler1, 

@doutriaux1 recommended not to use `pcmdi_metrics.pcmdi.io.JSONs` as it returns something hard-coded axis IDs as below:
```python
J = pcmdi_metrics.pcmdi.io.JSONs([inpath])
print(J.getAxisIds())
```
```
['variable', 'model', 'reference', 'rip', 'region', 'statistic', 'season']
```
which is not defined as `json_structure` in the JSON file. @doutriaux1 please correct me if I am wrong.

**Comment by lee1043** [comment]
note: the `inpath` should be given as list, `[inpath]` to the json loading function

**Comment by doutriaux1** [comment]
@lee1043 correct the method used by @gleckler1 is a convenience subclass used for pcmdi_metrics results.
