### ISSUE TITLE
agrparse_function not defining varModel and varOBS

### ISSUE THREAD

**Issue by dnadeau4** [PCMDI/pcmdi_metrics#584]
The following lines need to be changed defined the right arguments.

in myParam.py I found (`varOBS` and `varModel`)
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/monsoon_sperber/doc/myParam.py#L17
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/monsoon_sperber/doc/myParam.py#L35

In the argparse_functions I found (`--varobs` and `--varmod`)
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/monsoon_sperber/lib/argparse_functions.py#L20
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/monsoon_sperber/lib/argparse_functions.py#L22

**Comment by lee1043** [comment]
@dnadeau4 for `json_update` you can add below in the argparse_functions.py

```python
P.add_argument("--json_update",
                   type=bool,
                   default=False,
                   help="Option for updating already existing json: False (defualt) or True")
```

Thank you for fixing the bugs!
