### ISSUE TITLE
harmonizing version syntax; code in param files

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#585]
@doutriaux1 @zshaheen we now routinely populate a tree of results from the pmp that includes data, metrics, diagnostics and graphics.    Its time we exercise version control on everything, following the cmor template (e.g., v20181018).   

It is helpful to be able to define templates for results_dir and output_filename_template from within the parameter file, and below is one way to do that.  However, there is something preventing us from being able to have simple code like this in the param files.   
Any suggestions on how we tackle this? 

import datetime
year = datetime.date.today().year
month = datetime.date.today().month
day = datetime.date.today().day
version_now = 'v' + str(year) + str(month) + str(day)

**Comment by durack1** [comment]
Another one liner option
```
datetime.datetime.now().strftime('v%Y%m%d')
Out[7]: 'v20181018'
```

**Comment by doutriaux1** [comment]
Or even more pythonic:
```python
"{:v%Y%m%d}".format(datetime.datetime.now())
```

**Comment by gleckler1** [comment]
@doutriaux1  @zshaheen @durack1  This is needed to flush out doc for beginners, and for that  I prefer my version because its more readable by non experts, and it too can be reduced to 2 lines and still be readable.   But more to the point, how do we implement this ASAP? ... it’s basically the last piece needed to flush out our suite of examples and thus be ready to complete documentation.

**Comment by doutriaux1** [comment]
@gleckler1 will try to put it in today. Worst case tomorrow.

**Comment by gleckler1** [comment]
@doutriaux1   Any luck with allowing some code in parameter files? 
Lousy weather in DC!

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 with either of the examples above from Chucky or I, all you'd need is the string format `"v%Y%m%d"` to be added in the file as a string variable, voila!

**Comment by doutriaux1** [comment]
@zshaheen fixed cdp, I need to review it. Hopefully tomorrow or even today

**Comment by gleckler1** [comment]
@durack1 ... input parameter files are .py

**Comment by durack1** [comment]
@gleckler1 no problem my mistake, no issue with code in a *.py, which is code...

**Comment by zshaheen** [comment]
@durack1 @doutriaux1 @gleckler1 

No, they want extra/temp variables in the `py` files that won't be set as attributes to the parameter files. Ex:

```python
import datetime
year = datetime.date.today().year
month = datetime.date.today().month
day = datetime.date.today().day
results_dir = "results_{}-{}-{}".format(year, month, day)
```

In the case above, we only want the parameter object to have a `results_dir` parameter, and **not** `year`, `month`, and `day`.

**Comment by durack1** [comment]
@zshaheen thanks for clarifying.

So why not have a `vars_to_save = [...]` or conversely a `vars_to_exclude = [...]` at the end of the file which means you can do whatever you want, including calculating derived stuff etc in a param file, and then optionally include/exclude it?

**Comment by zshaheen** [comment]
@durack1 The fix in cdp will automatically do it. Only parameters that can work with the PMP parser will be the one used. This way, there's always a 1:1 map from the py files to a command via the command line.

**Comment by durack1** [comment]
@zshaheen nice, just like magic..

**Comment by durack1** [comment]
@zshaheen ok and now that I think about it, what happens if a user assigns (for e.g.) a numpy array to a variable that CDP is expecting to be a string?

**Comment by zshaheen** [comment]
Yes, this was @doutriaux1's idea, it's pretty cool.

**Comment by zshaheen** [comment]
Regarding your second comment, we don't have an answer about that yet. For e3sm_diags, we're encountering the same issue. 
* One possible solution is to use the `ast.literal_eval` to figure that out, so the argument would be `--zonal_mean_2d_plevs 'numpy.logspace(2.0, 3.0, num=17)'`
* Or when the `py` is dumped and a command of it is saved, expand the numpy arrays.
  * If you don't get what I'm saying about this point, look at the "Show Output Metadata" [on this link](https://e3sm-project.github.io/acme_diags/sample_output/modTS_vs_modTS_3years/viewer/latitude-longitude/model_vs_model/prect-global/ann.html). It's a dump of the parameters used to create that plot.

We're still thinking how to approach this.

**Comment by durack1** [comment]
@zshaheen ok got you, so expanding contour levels (e.g. shape 10,1) makes sense, but what happens if you have a shape 1024,1024? Maybe just throw an error, with an appropriate warning, or throw a warning at first iteration, and then if a user adds `cdp.warnings = False` or equivalent, then you just push ahead with using whatever is handed to the call..

**Comment by zshaheen** [comment]
@durack1 @doutriaux1 Another idea is to just dump a `py` file of the parameters for a single plot as well. This way, we avoid the case you talked about, when the shape is 1024x1024. Also we still get an easy way for users to change the parameters for a given run as well.

**Comment by doutriaux1** [comment]
?

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen   Is the fix in CDP already in pmp nightly, i.e. can I test out making example param files for pmp documentation?

**Comment by doutriaux1** [comment]
@gleckler1 moving on to this now.

**Comment by gleckler1** [comment]
@doutriaux1 great... this is a critical step

**Comment by doutriaux1** [comment]
@zshaheen do I need a special keyword? The following does not work:
```python
import pcmdi_metrics
parser = pcmdi_metrics.driver.pmp_parser.PMPParser()
parser.add_argument("--charles", default="DEFAULT")
args = parser.get_parameters()[0]
print("You picked: {}".format(args.charles))
```

ran . with the following `myparams.py`

```python
peter = "Peter"
charles = "hi from param file"
```

I get:

```
python test_params.py -p myparams.py 
Traceback (most recent call last):
  File "test_params.py", line 7, in <module>
    args = parser.get_parameters()[0]
  File "/Users/doutriaux1/miniconda3/envs/vcs/lib/python3.6/site-packages/cdp/cdp_parser.py", line 454, in get_parameters
    orig_parameters = self.get_orig_parameters(*args, **kwargs)
  File "/Users/doutriaux1/miniconda3/envs/vcs/lib/python3.6/site-packages/cdp/cdp_parser.py", line 124, in get_orig_parameters
    self._usable_via_cmdline_args(parameter)
  File "/Users/doutriaux1/miniconda3/envs/vcs/lib/python3.6/site-packages/cdp/cdp_parser.py", line 290, in _usable_via_cmdline_args
    raise RuntimeError(msg)
RuntimeError: peter is not a valid parameter because it's not defined in the parser.
```

**Comment by zshaheen** [comment]
You have an old version. The latest code for this fix is on the `issue45` branch on cdp (not pmp). I can tell you're using an old version by [looking here](https://github.com/CDAT/cdp/commit/2f07767fce98aa0e2071f1ba128d73e859bf6a06), the function `_usable_via_cmdline_args()` displayed in your stack trace was renamed.

**Comment by doutriaux1** [comment]
@zshaheen I'll try again but I'm pretty sure I had it installed from that branch

**Comment by doutriaux1** [comment]
@zshaheen I'll completely remove it from my env and re-install again

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen  Is this ready for use yet?

**Comment by zshaheen** [comment]
@gleckler1 Charles looked at my changes to CDP and tried them in PMP and I think all is okay.

@doutriaux1, I can release another version of CDP with fix so we have a pinned down version.

**Comment by gleckler1** [comment]
@zshaheen  I think I am making some progress with it from nightly.   This will be extremely helpful.   Lets chat and THANKS!

**Comment by lee1043** [comment]
Hi could anyone please remind me what the finally selected code that was for the parameter file syntax to have CMOR style version string at the end of result_dir?

**Comment by gleckler1** [comment]
See https://github.com/PCMDI/pcmdi_metrics/issues/585
