### ISSUE TITLE
Add new metrics in collaboration with DK and MA of UW

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#589]

**Comment by lee1043** [comment]
Comparing result to the reference (Ahn et al. 2017) for an initial validation.

**Power spectra**
**_Reference:_**
![](https://user-images.githubusercontent.com/17091564/51418837-cd6c7100-1b3a-11e9-9fa4-c4deaec0870f.gif)
 **_PMP:_**
![](https://user-images.githubusercontent.com/17091564/52598905-0501cc80-2e0c-11e9-8f07-8ccc4cd50e20.gif)
_**Diff: PMP minus UW**_
![](https://user-images.githubusercontent.com/17091564/52598939-134fe880-2e0c-11e9-81f7-bf61ce387848.gif)

**EWR**
**_Ref:_**
- ewr:  `2.55743`
- east power:  `0.0198572`
- west power:  `0.00776452`
**_PMP:_**
- ewr:  `2.5566088593634797`
- east power:  `0.019740865122155112`
- west power:  `0.0077215038389055754`

**Comment by gleckler1** [comment]
@lee1043  do you think we can close this issue?

**Comment by lee1043** [comment]
@gleckler1 currently it has been developed on a separate repo (private) and need to migrate code to pmp. Please keep this issue opened for that.

**Comment by lee1043** [comment]
To do
- [ ] [Branch in this repo](https://github.com/PCMDI/pcmdi_metrics/tree/589_ljw_new_metrics_UW) needs to be updated with the latest code
- [ ] Prepare merging the branch to master.

**Comment by gleckler1** [comment]
@lee1043  ok, thanks, just doing house cleaning

**Comment by lee1043** [comment]
@gleckler1 I expect MJO metrics to be merged to master soon.
