### ISSUE TITLE
allow custom obs_dic for mean clim

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#590]
@doutriaux1  We might be very close to this already with below but need to get this function ASAP.... wrinkle... new directory structure for obs_dic.json, so may need to include some of that as a attribute in new obs_json.

https://github.com/PCMDI/pcmdi_metrics/blob/master/pcmdi_metrics/pcmdi/mean_climate_metrics_driver.py

        if hasattr(self.parameter, 'custom_observations'):
            # Can't use load_path_as_file_obj() b/c might not be in /share/
            cust_obs_json_file = open(self.parameter.custom_observations)
            obs_dict.update(json.load(cust_obs_json_file))
            cust_obs_json_file.close()
return obs_dict

**Comment by doutriaux1** [comment]
@gleckler1 I believe this is fixed
