### ISSUE TITLE
Improve monsoon sperber

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#594]
Improve monsoon_sperber to do followings for @gleckler1 

- [ ] Run the CMIP5 and CMIP6 monsoon_sperber compared to the 2 daily datasets now in
/p/user_pub/PCMDIobs/PCMDIobs2.0/atmos/day/pr
- [x] Write output in /p/user_pub/pmp/pmp_results/pmp_v1.1.2

**Comment by lee1043** [comment]
Progress:
- [x] Output goes to pmp_result dir
- [x] CMIP5 with GPCP 1-3
- [ ] CMIP5 with CMORPH-1-0
- [ ] CMIP6 with GPCP 1-3
- [ ] CMIP5 with CMORPH-1-0

**Comment by lee1043** [comment]
tracking changes: https://github.com/PCMDI/pcmdi_metrics/pull/596

**Comment by lee1043** [comment]
### To do list:
#### Check:
- [ ] If fractional cdf used for getting composite
#### Dive down plot:
- [ ] Show composite and multiple obs
- [ ] Add vertical lines for obs onset/decay
- [ ] Show statistics
- [ ] Multiple realization as grey lines (after analysis below resolved)
#### Analysis:
- [ ] Multiple realizations (may need help from @doutriaux1 for parallel running using DASK)
- [ ] CMIP6
---
### Dive down plot example:
![image001](https://user-images.githubusercontent.com/17091564/58359083-95ea3a00-7e36-11e9-97e7-516b4330f07b.png)

**Comment by lee1043** [comment]
### Drafted candidate plot:
![cmip5_ACCESS1-0_historical_r1i1p1_monsoon_sperber_1961_1962](https://user-images.githubusercontent.com/17091564/58447348-ecff4180-80b8-11e9-98e6-5a95139d7344.png)

@gleckler1 what do you think?

**Comment by gleckler1** [comment]
@lee1043 do you think we can close this or do we need to preserve some of it?
