### ISSUE TITLE
Cannot import vcs with the latest pmp nightly

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#599]
I am installing the latest pmp nightly to test watermark capability that @gleckler1 asked, but after installation I cannot import `vcs` (due to `cdtime` importing error, maybe?) @doutriaux1 any idea, please?

Installation of nightly version (following [Wiki instruction](https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-Anaconda)):
```
conda create -n [MY_ENV_NAME_HERE] -c cdat/label/nightly -c pcmdi/label/nightly -c cdat-forge -c cdat pcmdi_metrics
```

Activation of env:
```
source activate [MY_ENV_NAME_HERE]
```

Importing vcs:
```
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/vcs/utils.py", line 17, in <module>
    import cdtime
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/cdtime/__init__.py", line 8, in <module>
    from .compreltime import *
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/cdtime/compreltime.py", line 2, in <module>
    from . import _cdtime
ImportError: libcdms.so: cannot open shared object file: No such file or directory
```

Error from cdtime loading, so trying importing cdtime:
```
>>> import cdtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/cdtime/__init__.py", line 8, in <module>
    from .compreltime import *
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423/lib/python3.6/site-packages/cdtime/compreltime.py", line 2, in <module>
    from . import _cdtime
ImportError: libcdms.so: cannot open shared object file: No such file or directory
```

Version checking:
```
$ conda list vcs
# packages in environment at /export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423:
#
# Name                    Version                   Build  Channel
vcs                       8.0                      py36_0    cdat-forge
vcsaddons                 8.0.2019.02.23.07.01.g2834c20  py36h14c3975_0    cdat/label/nightly
```
```
$ conda list cdtime
# packages in environment at /export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423:
#
# Name                    Version                   Build  Channel
cdtime                    3.1.2.2019.02.09.12.03.gba9e0cb  py36ha5dfbcb_0    cdat/label/nightly
```

**Comment by gleckler1** [comment]
@lee1043 
conda create -n pmpn27_0421a -c cdat/label/nightly -c pcmdi/label/nightly -c conda-forge -c cdat pcmdi_metrics python=2.7 **libcdms cdms2**
I have no idea why

**Comment by lee1043** [comment]
@gleckler1 thanks for the line for python 2.7 version. But still, I think this error to be very critical because it will break other production codes.

**Comment by gleckler1** [comment]
@lee1043 @doutriaux1  I know... we can't have different envs for different purposes... that would be a slippery slope.   But I think this *fix* is to deal with recent changes.

**Comment by lee1043** [comment]
@gleckler1 that has a point. I am removing the `TOP PRIORITY` tag, and stick with the python version 2.7 fixed version for the mean climatology plotting purpose. But I believe this should be revisited in the early future, sooner than later.

**Comment by doutriaux1** [comment]
Jiwoo,

Peter just experienced this as well, for now replace cdat-forge with conda-forge. I will need to figure out why it brings some stuff from the wrong places.

C.

**Comment by doutriaux1** [comment]
@lee1043 you can remove python=2.7 it was only for Peter because we wanted to force python 2

**Comment by lee1043** [comment]
@doutriaux1 you mean like below?
``` conda create -n [MY_ENV_NAME_HERE] -c cdat/label/nightly -c pcmdi/label/nightly -c conda-forge -c cdat pcmdi_metrics libcdms cdms2```

**Comment by doutriaux1** [comment]
yes, probably (???) don't even need libcdms cdsm2 at the end

**Comment by lee1043** [comment]
After above installation, I've narrowed down the cause of first error simplified as below (while other errors still exists, I guess, but first thing first...). In brief, it fails to plot text on canvas. 

```
(pmp_nightly_20190423-2) -bash-4.1$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```
>>> import vcs
/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423-2/lib/python3.6/site-packages/pkg_resources/__init__.py:1243: UserWarning: /export_backup/lee1043/.cache/Python-Eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190423-2/lib/python3.6/site-packages/pkg_resources/__init__.py:1243: UserWarning: /export_backup/lee1043/.cache/Python-Eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
>>> x=vcs.init()
>>> t=vcs.createtext()
>>> t.string='abc'
>>> x.plot(t)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 761
vtkXOpenGLRenderWindow (0x55a3dfdc1790): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.

Segmentation fault (core dumped)
```

**Comment by doutriaux1** [comment]
yes you do not have opengl on the system. @danlipsa @scottwittenburg know about this, but it is yet again an occurence of this very annoying problem with RH6. Please install mesalib for now
```
conda install -c cdat/label/nightly -c conda-forge mesalib vtk-cdat
```

**Comment by lee1043** [comment]
@doutriaux1 thanks, having mesalib as advised resolved the above openGL error. 

Next issue I have is loading customized colormap and isofill levels from python script and JSON, respectively, before start using the watermark capability. Thanks for help, looking forward for more help tomorrow ;)

![rltcre ACCESS1-0_djf](https://user-images.githubusercontent.com/17091564/56630609-c5731000-6606-11e9-8fa1-20e886267c2a.png)

**Comment by durack1** [comment]
@doutriaux1 is it RH6 only, with RH7 does it go away?

**Comment by doutriaux1** [comment]
we hope so, our RH6 machine do not have a recent enough opengl driver. Hopefully newer system will be good.

**Comment by doutriaux1** [comment]
@lee1043 @gleckler1 which colormap are you trying to load? I'm looking at your dictionary and all the colormap I'm trying to load do not exist in the json file. e.g `band_6` `band_12` `AMIP_rlt`, etc...

**Comment by durack1** [comment]
@doutriaux1 I really to *hope* that you are currently testing CDAT-dev on RH7... please tell me this is so..

**Comment by gleckler1** [comment]
@lee1043 can I close this issue or is it still a problem?

**Comment by lee1043** [comment]
@gleckler1 no I think this issue is now gone.
