### ISSUE TITLE
Reinforce PMP documentation

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#648]

**Comment by lee1043** [comment]
@acordonez @gleckler1 I forked PMP repo to my own and set up a test place for developing documentation. Please check below two places. For now they are just place holder. Please feel free to add/revise.
- Directory for testing: https://github.com/lee1043/pcmdi_metrics/tree/648_jwl_documentation/docs
- Test page preview: https://lee1043.github.io/pcmdi_metrics/

**Comment by gleckler1** [comment]
@lee1043 @acordonez  Thanks for testing this - we discussed Ana reproducing this on her own repo and eventually to the PMP - do I have that right?

**Comment by lee1043** [comment]
I think so, but I also don't mind using my repo if that helps reducing Ana's workload.

**Comment by acordonez** [comment]
@lee1043 thanks, I've been practicing with sphinx in my own fork too

**Comment by lee1043** [comment]
This task will be followed up at https://github.com/PCMDI/pcmdi_metrics/issues/653
