### ISSUE TITLE
Clean up/revise/re-org directory tree

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#649]
The current directory structure may need some clean up. The current structure is listed in the following file for initiating a brainstorming.

[PMP_directory_tree_20201104.docx](https://github.com/PCMDI/pcmdi_metrics/files/5490168/PMP_directory_tree_20201104.docx)

**Comment by gleckler1** [comment]
@acordonez @lee1043  Thanks for the dir_tree structure Jiwoo.   I'm thinking the /demo/parameter_files are redundant with the direction being taken in /doc.   Ana you might want to review the param files in /demo to see if there is anything in there that would be helpful for developing the mean climate doc/notebooks.   But other than that, do you agree we should rm /demo?

**Comment by acordonez** [comment]
@gleckler1 @lee1043 Yes, it looks to me like we can remove /demo and move those parameter files to either /doc or to our new /sample_setups folder.

**Comment by lee1043** [comment]
Below is my proposal for restructuring:

[PMP_directory_tree_20201110_proposal_jlee.docx](https://github.com/PCMDI/pcmdi_metrics/files/5520800/PMP_directory_tree_20201110_proposal_jlee.docx)

**Comment by acordonez** [comment]
@lee1043 That directory reorganization makes sense to me. Just a small thing I noticed is "recipe" appears twice under the "Proposed directory tree of PMP"

**Comment by lee1043** [comment]
@acordonez oops, thank you for pointing that out! :)

**Comment by lee1043** [comment]
I am closing this issue because the PMP directory structure has been simplified in some degree after PMP v3.0.0.
