### ISSUE TITLE
internal doc usage of mean climate calcs

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#652]

**Comment by gleckler1** [comment]
@lee1043 FYI I'm starting to document internal running of the mean climate with this branch.

**Comment by lee1043** [comment]
I am closing this issue as [some documentations](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/mean_climate/scripts/README.md) were added for internal use of mean climate since after PMP v3.0.0.
