### ISSUE TITLE
New documentation format for github.io

### ISSUE THREAD

**Issue by acordonez** [PCMDI/pcmdi_metrics#653]
Initial work to set up repo for hosting documentation on github.io

**Comment by acordonez** [comment]
[gh-pages](https://github.com/PCMDI/pcmdi_metrics/tree/gh-pages) branch has been created to host the documentation. Instructions for editing and building the documentation are found on the README in that branch.

**Comment by acordonez** [comment]
@gleckler1 @lee1043 can I close this issue, or is there more work that should be included?

**Comment by lee1043** [comment]
I think it is okay to close this issue as it has become a part of our regular work flow. Thank you for your work, @acordonez

**Comment by gleckler1** [comment]
@acordonez @lee1043 Seems reasonable to close but I am wondering where we should continue comments/questions such as this one regarding documentation discussions.   That could be done by creating new issues (once the documentation gets a little further along), email, or slack.   Any thoughts?

**Comment by acordonez** [comment]
@gleckler1 @lee1043 Keeping documentation questions on GH would work for me, but I'm not sure if it would be better to have one ongoing issue or open new ones as needed.
