### ISSUE TITLE
CMEC compliant metrics output

### ISSUE THREAD

**Issue by acordonez** [PCMDI/pcmdi_metrics#663]
The overarching goal is to make PMP outputs CMEC-compliant (https://cmec.llnl.gov/). The first step is to add functionality that writes the output metrics files in the CMEC format.

**Comment by gleckler1** [comment]
@acordonez I guess this is about complete so might be ready to close this... do I have that right?   Attempting a little clean up ;-)

**Comment by acordonez** [comment]
Since we have the option to output CMEC metrics JSONs in all of the metrics now, it does seem ok to close this.
