### ISSUE TITLE
generalized parallel run function

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#680]

**Comment by gleckler1** [comment]
@lee1043  can this be closed?

**Comment by gleckler1** [comment]
@lee1043  OK, I see now this is not yet in master.   Maybe you should make a pull request and see if it passes CI and if yes we can merge with master?

**Comment by lee1043** [comment]
https://github.com/PCMDI/pcmdi_metrics/pull/697

**Comment by lee1043** [comment]
Need to make parallel_submitter to be importable.

**Comment by lee1043** [comment]
To use `parallel_submitter` it needs to be imported as follows:
```python
from pcmdi_metrics.misc.scripts import parallel_submitter
```
