### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PBrockmann** [PCMDI/pcmdi_metrics#72]
Is there a good reason not providing this pcmdi_metrics package with a python distribution like Anaconda ?
I would like to install cdms2, cdutil and pcmdi_metrics package with a simple pip install procedure.

**Comment by gleckler1** [comment]
@PBrockmann @doutriaux1 @durack1 
Anaconda it is!

**Comment by durack1** [comment]
@gleckler1 this link may also be very useful upon closing this issue:

https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda
