### ISSUE TITLE
clean up recipe / recipes

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#727]
@acordonez  @lee1043   My plan with this one is:

mv recipes/conda-envs recipe
mv recipes/pcmdi_metrics recipe
rm -rf recipes

we may decide later that recipe/conda-envs and recipe/pcmdi_metrics can be deleted.

**Comment by acordonez** [comment]
@gleckler1 That plan looks good to me.

**Comment by lee1043** [comment]
@gleckler1 looks good to me too.
