### ISSUE TITLE
precip variability across time scale 

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#731]
Implement @msahn's work into PMP

**Comment by lee1043** [comment]
Branch: 731_msa_precip_benchmark
Directory to start: https://github.com/PCMDI/pcmdi_metrics/tree/731_msa_precip_benchmark/pcmdi_metrics/precip_variability
Draft PR for tracking changes: https://github.com/PCMDI/pcmdi_metrics/pull/732

**Comment by msahn** [comment]
The branch name is changed to "731_msa_precip_variability".
