### ISSUE TITLE
Remove vcs dependencies

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#785]
Remove dependencies to [`vcs`](https://cdms.readthedocs.io/en/latest/manual/cdms_1.html?highlight=vcs#plotting-data) of CDAT because it is planned to be no longer maintained.

**Comment by lee1043** [comment]
In my attempt to replace `vcs` by `cartopy`, followings were noticed (leaving for documenting). 
- @msahn and I have observed some conflict in conda env that prevents installing `cartopy` in the PMP-installed conda env. As a workaround, @msahn has used `basemap` in his [plotting work](https://github.com/msahn/test_pcmdi_metrics), but `basemap` is no longer maintained and supposed to be replaced by `cartopy`.
- I think I found where the conflict was caused: `proj4` and `cartopy`, specifically `proj` that is one of dependencies of `cartopy`.
- I don't see `proj4` explicitly used in PMP. Plus, `proj` is supposed to replace `proj4` according to [this doc](https://en.wikipedia.org/wiki/PROJ). 
- So I think it is okay to remove `proj4` and add `cartopy` in [`dev.yml`](https://github.com/PCMDI/pcmdi_metrics/blob/master/conda-env/dev.yml).

@gleckler1 @acordonez I don't think I've seen any code that use `proj4`, have you seen/used it in any code of PMP?

In @tomvothecoder's [PR](https://github.com/PCMDI/pcmdi_metrics/pull/784) the `proj4` was included because it was listed in meta.yaml.in from here: https://github.com/PCMDI/pcmdi_metrics/blob/8993d51c23cf8dd7abcc418acc5bbc8ef90fe645/recipe/meta.yaml.in. Is that correct?

**Comment by acordonez** [comment]
@lee1043 I haven't seen proj4 explicitly imported. I'm guessing it was a dependency for something else.

**Comment by tomvothecoder** [comment]
> In @tomvothecoder's PR the proj4 was included because it was listed in meta.yaml.in from here: https://github.com/PCMDI/pcmdi_metrics/blob/8993d51c23cf8dd7abcc418acc5bbc8ef90fe645/recipe/meta.yaml.in. Is that correct?

Correct, `proj4` was in the old `meta.yaml.in` so it was copied over.

> In my attempt to replace `vcs` by `cartopy`, followings were noticed (leaving for documenting). 
> - @msahn and I have observed some conflict in conda env that prevents installing `cartopy` in the PMP-installed conda env. As a workaround, @msahn has used `basemap` in his [plotting work](https://github.com/msahn/test_pcmdi_metrics), but `basemap` is no longer maintained and supposed to be replaced by `cartopy`.
> - I think I found where the conflict was caused: `proj4` and `cartopy`, specifically `proj` that is one of dependencies of `cartopy`.
> - I don't see `proj4` explicitly used in PMP. Plus, `proj` is supposed to replace `proj4` according to [this doc](https://en.wikipedia.org/wiki/PROJ). 
> - So I think it is okay to remove `proj4` and add `cartopy` in [`dev.yml`](https://github.com/PCMDI/pcmdi_metrics/blob/master/conda-env/dev.yml).
> 
Based on your findings, I will 
- [ ] Add `cartopy` to the `dev.yml` and resolve package conflicts (remove `proj4`)
