### ISSUE TITLE
Instruction doc for PMP developers

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#806]
Need to have doc for developers regarding the updated workflow.

**Comment by lee1043** [comment]
The current wiki page (https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers) need to be updated.

**Comment by lee1043** [comment]
CI process instruction added: https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers#note-for-ci-process

**Comment by acordonez** [comment]
Conda forge release documentation in progress. Awaiting creation of PMP feedstock.

**Comment by acordonez** [comment]
Text has been added to the wiki for the conda-forge release process: https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers#conda-forge-releases

**Comment by lee1043** [comment]
@acordonez many thanks! I closed the issue.
