### ISSUE TITLE
Maintain one `main` branch for any latest

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#807]
# Maintain one `main` branch for any latest

- [x] Rename `master` to `main`: Github has renamed its default branch name for any new repository to `main` from `master`. To be consistent I am planning to rename here as well. Procedure is easy with one clicking, following instruction [here](https://github.com/github/renaming). I don't think there to be any problem except you will need to update your local or forked repo.

- [ ] Merge `gh-pages` to `main`: The purpose of having `gh-pages` branch was for preventing any small update for the [document website](http://pcmdi.github.io/pcmdi_metrics/) triggers nightly build through circle CI. As we are moving away from the circle CI and the nightly build process, I think it is okay to maintain one `main` branch for any latest update. 
  - [ ] Contents of [`README.md`](https://github.com/PCMDI/pcmdi_metrics/blob/gh-pages/README.md) of the branch need to be relocated. Maybe to [Wiki](https://github.com/PCMDI/pcmdi_metrics/wiki)?

@acordonez @gleckler1 Would you agree with the above?

**Comment by acordonez** [comment]
Re: gh-pages, one argument to keep it as a separate branch is that there is already a "doc" folder in main, while the folder that gh-pages uses is called "docs". I believe the "docs" name is required for github pages, and it might be confusing to have both folders in the same branch. We could also consider renaming "doc" in main to something else.

**Comment by acordonez** [comment]
Re: main branch, that sounds good to me. I think we'll need to update some links in the Jupyter Notebook README. Do we also need to update this config with the new name? https://github.com/PCMDI/pcmdi_metrics/blob/master/.github/workflows/build_workflow.yml

**Comment by lee1043** [comment]
> Re: main branch, that sounds good to me. I think we'll need to update some links in the Jupyter Notebook README. Do we also need to update this config with the new name? https://github.com/PCMDI/pcmdi_metrics/blob/master/.github/workflows/build_workflow.yml

Yes, I think so. Any chance this renaming would affect conda forge setup?

**Comment by lee1043** [comment]
> Re: gh-pages, one argument to keep it as a separate branch is that there is already a "doc" folder in main, while the folder that gh-pages uses is called "docs". I believe the "docs" name is required for github pages, and it might be confusing to have both folders in the same branch. We could also consider renaming "doc" in main to something else.

@acordonez Great point! I agree we can consider rename "doc" as something else, but I have no good candidate name yet. I will work on renaming first, then revisit the task for merging `gh-pages`

**Comment by lee1043** [comment]
Note: PR https://github.com/PCMDI/pcmdi_metrics/pull/812 for renaming.

**Comment by lee1043** [comment]
Branch name `master` now renamed to `main`.
