### ISSUE TITLE
Domain definition for Monsoon Wang's NAFM

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#820]
Found by @pochedls at https://github.com/XCDAT/xcdat/issues/166#issuecomment-974313387. 

---

The `NAFM` region in monsoon_wang driver is for `North African Monsoon`, 310E to 60E (as in below figure).

![a-Map-showing-the-positions-and-aerial-extent-of-monsoons-as-defined-by-the](https://user-images.githubusercontent.com/17091564/142713893-be5ee47f-7d0c-402f-aa5a-fc335cb2549f.png)(image from [here](https://www.researchgate.net/publication/319867588_Tibet_the_Himalaya_Asian_Monsoons_and_Biodiversity_-_In_what_ways_are_they_related))

---

However, with [region defined as `longitude=(310, 60)`](https://github.com/PCMDI/pcmdi_metrics/blob/d0090c21b92ecc6c3be819846478538b5ab04321/share/default_regions.py#L51), the area considered is from 60E to 310E (mirrored, as in below figure).

![NAFM](https://user-images.githubusercontent.com/17091564/142713965-f42f1ec6-e024-43ba-99b1-6b21f2670a66.png)

```python
import cdms2
import vcs
f = cdms2.open('CanCM4_NAFM_wang-monsoon.nc')
d = f('variable_993')
x = vcs.init()
x.png('NAFM.png')
```

---

In the PMP's driver for the Monsoon Wang metric, it opens model file with regular cdms2 open, as [`f = cdms2.open(modelFile)`](https://github.com/PCMDI/pcmdi_metrics/blob/9d036a6b48296e27e08636cb918799f6fbe0cf06/pcmdi_metrics/monsoon_wang/monsoon_wang_driver.py#L189). 

@gleckler1 Could you point the reference paper for the Monsoon Wang index? And any idea for quick fix?

**Comment by gleckler1** [comment]
@lee1043  https://doi.org/10.1016/j.dynatmoce.2007.05.002

**Comment by lee1043** [comment]
Note: This issue should be resolved by using the new [`regions_subset`](https://github.com/PCMDI/pcmdi_metrics/blob/cff4e616907aba0944937c2c71aca5ba1f962132/pcmdi_metrics/io/regions.py#L82) function. 

@bosup is working on xcdat migration of monsoon Wang code and will test this function in the monsoon Wang.

**Comment by lee1043** [comment]
![Screenshot 2024-11-26 at 1 03 18 PM](https://github.com/user-attachments/assets/16d699c4-408e-46cf-b36d-688299f0e8a1)
The above screenshot from `ncview CanCM4_NAFM_wang-monsoon.nc` where the file is from Demo 2a notebook from PR #1200 confirms that the issue will be resolved by merging the PR.
