### ISSUE TITLE
update installation/user guide wiki pages

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#840]
Hi folks, I received a query today about installing the latest PMP version, and in order to reply, took a peek at https://github.com/PCMDI/pcmdi_metrics/wiki/Using-the-package which includes the text:
```
As part of running this demo a tar file with model and observational data for the demo will be
downloaded from http://oceanonly.llnl.gov/gleckler1/pmp-demo-data/pmpv1.1_demodata.tar
```

As oceanonly was disabled as a webserver, probably a good idea to edit this page for the latest info. Probably also a good idea to update https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers as it seems like my contributions are still persisting, and likely outdated by now

@lee1043 @acordonez ping!

**Comment by lee1043** [comment]
Thanks @durack1 for pointing it out. I've just added "(deprecated)" in the title of the page, but better organization of sidebar and clean up of pages are still required. We will work on this.

**Comment by lee1043** [comment]
I am closing this issue because now [README.md](https://github.com/PCMDI/pcmdi_metrics) has been updated to point to documentations for [install](http://pcmdi.github.io/pcmdi_metrics/install.html) and [demo](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/README.md).
