### ISSUE TITLE
Produce templates for portrait plots

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#85]
Following the 24th Sept 2014 email to GFDL the following improvements were listed:
1. Produce templates for portrait plots.

test_portrait.py already plots CMIP5 results for a large suite of variables, improvements include?

**Comment by durack1** [comment]
Thanks to @doutriaux1 we now have two templates 3obs and 4seasons for portrait plots. Was there anything else that we needed to provide here @gleckler1 or can this issue be closed?

**Comment by doutriaux1** [comment]
let's close
