### ISSUE TITLE
convert pcmdi_compute_climatologies.py to pcmdi_compute_climatologies-xcdat.py

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#859]

**Comment by gleckler1** [comment]
@lee1043 some progress with seasonal clims but have not got annual cycle clim working yet (d.temporal.climatology(var, freq="month", weighted=True) 

 python -i ./pcmdi_compute_climatologies-xcdat.py --var prw --infile /p/user_pub/PCMDIobs/obs4MIPs/RSS/REMSS-PRW-v07r01/mon/prw/gn/v20220201/prw_mon_REMSS-PRW-v07r01_PCMDI_gn_198801-201812.nc --outfile ./crap.nc

**Comment by lee1043** [comment]
@gleckler1 The annual cycle issue seems to be related to a [xCDAT bug](https://github.com/xCDAT/xcdat/issues/327), I think. I will check with @tomvothecoder about it.

**Comment by lee1043** [comment]
@gleckler1 Thanks to quick fix from @tomvothecoder, I was able to run below command without any error with latest xCDAT in its main branch. 

```python -i ./pcmdi_compute_climatologies-xcdat.py --var prw --infile /p/user_pub/PCMDIobs/obs4MIPs/RSS/REMSS-PRW-v07r01/mon/prw/gn/v20220201/prw_mon_REMSS-PRW-v07r01_PCMDI_gn_198801-201812.nc --outfile ./crap.nc```

During the mean time waiting for the fix included new version releasing

1. `conda env create -f conda-env/dev.yml -n [YOUR ENV NAME]`



, I think you can proceed developing by installing the latest main branch of xcdat in your PMP testing env. 

Once you activate your PMP testing env, please consider followings. 

2. activate your PMP testing env (e.g., conda activate [env name])
3.

**Comment by lee1043** [comment]
@gleckler1 Thanks to quick fix from @tomvothecoder, I was able to run below command without any error with latest xCDAT in its main branch.

```python -i ./pcmdi_compute_climatologies-xcdat.py --var prw --infile /p/user_pub/PCMDIobs/obs4MIPs/RSS/REMSS-PRW-v07r01/mon/prw/gn/v20220201/prw_mon_REMSS-PRW-v07r01_PCMDI_gn_198801-201812.nc --outfile ./crap.nc```

To apply the change until the fix-included new xcdat version released:
1. git clone xcdat repo
2. `conda env create -f conda-env/dev.yml -n [YOUR ENV NAME]`
3. `conda activate [YOUR ENV NAME]`
4. Go to xcdat directory and install: `python setup.py install`
5. `conda install -c conda-forge pcmdi_metrics`
6. go to PMP directory and continue working on branch

Please note that I made some update to the `pcmdi_compute_climatologies-xcdat.py` file to simplify the climatology calculation process. Just a friendly reminder for doing `git pull` first.

**Comment by tomvothecoder** [comment]
@lee1043 Great, thanks for reviewing https://github.com/xCDAT/xcdat/pull/329 and validating the fix here.
