### ISSUE TITLE
Include statistics across multiple obs

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#86]
Following the 24th Sept 2014 email to GFDL the following improvements were listed:

Include statistics across different observational references (e.g., CERES vs ERBE).

**Comment by durack1** [comment]
@gleckler1 this is achieved by setting:
```
# Observations to use 'default', 'alternate', 'all' or specific enumerated climatology e.g. 'ref3'
ref = ['all']; #'default','all','alternate','ref3'
```
Is anything else needed here or can we close?

**Comment by durack1** [comment]
I will note however that all the CMIP5/3/2 etc JSONs will need to be rerun so that they are tested against all available obs.. @gleckler1 I think this will be your task?

**Comment by jservonnat** [comment]
It doesn't work for me...

**Comment by durack1** [comment]
@jservonnat I think we need to get you all version 1.0'd up.. The ```ref = ['all']``` seems to be working fine with the GFDL/CSIRO test cases I've been working through..

**Comment by durack1** [comment]
@gleckler1 when you re-run the CMIP5 jsons against all the obs, can you add the ```wfo``` variable please?

**Comment by durack1** [comment]
@gleckler1 also ```sos``` which depends on #162

**Comment by gleckler1** [comment]
@doutriaux1 .... for at least two reasons,  running the metrics to compare different obs should not be handled as a kludge to how the model metrics is handled.   First, all distinct permutations should be considered, e.g., with 3 datasets [obs1, obs2, obs3] should include results for obs1 vs obs2, obs1 vs obs3, and obs2 vs obs3.  The bias in obs1-obs2 will be == but opposite in sign to obs2-obs1, so we should not have to run both, but the json info should clearly indicate if its obs1-obs2 or obs2-obs1.   Second...  It would be cleanest if we produced a single json file which includes the comparison of ALL variables.    These two objectives imply we don't want to handle the obs vs obs as a special case of obs vs mods.   Maybe we should have a separate (but very similar) parameter file to handle the 'all obs vs obs" case?

**Comment by doutriaux1** [comment]
@gleckler1 this is simply a matter of setting up a parameter file for each variable that take obs2/3/4/etc... and run it against obs1. Not sure I'm the right person for this. I'll chat with @durack1 about this.

**Comment by doutriaux1** [comment]
@durack1 the biggest issue is probably going to be to figure out what the correct "template" is so it can be used across obs/vars

**Comment by gleckler1** [comment]
At a minimum it will take a separate parameter file, but my hunch is tweaking will be needed for cases where there are more than 2 obs... plus I don't see how we can get all vars in one json which is how the model metrics outputs.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 This is REALLY important and will be used for various analysis including later testing model dependence.   But we should discuss how best to do this and we are not going to make it for v1.1 so for now downgrading label

**Comment by durack1** [comment]
@gleckler1 @zshaheen this was in for [1.1.2](https://github.com/PCMDI/pcmdi_metrics/milestone/8) right? If yes, then closing is a good idea
