### ISSUE TITLE
Simplify PMP JSON contents

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#869]
Current PMP output json files have heavy contents (e.g., [Mean clim](https://raw.githubusercontent.com/PCMDI/pcmdi_metrics_results_archive/main/metrics_results/mean_climate/cmip6/historical/v20210811/pr.cmip6.historical.regrid2.2p5x2p5.v20210811.json), [MoV](https://raw.githubusercontent.com/PCMDI/pcmdi_metrics_results_archive/main/metrics_results/variability_modes/cmip6/historical/v20220825/NAM/NOAA-CIRES_20CR/var_mode_NAM_EOF1_stat_cmip6_historical_mo_atm_allModels_allRuns_1900-2005.json)). In effort to reduce the file size for regular [online archive](https://github.com/PCMDI/pcmdi_metrics_results_archive), one possibility is to not include "YAML" and "script" as default. 

I think this could be handled by revising [`base.py`](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/io/base.py) in [`pcmdi_metrics/io`](https://github.com/PCMDI/pcmdi_metrics/tree/main/pcmdi_metrics/io) directory, maybe by adding `if` statement for [this line](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/io/base.py#L200) of the code, so storing YAML info can be optional.

**Comment by lee1043** [comment]
@acordonez would you mind helping on this when you have time?

**Comment by acordonez** [comment]
@lee1043 Yes I'll start taking a look at this

**Comment by lee1043** [comment]
@acordonez, I got this handled in [this commit](https://github.com/PCMDI/pcmdi_metrics/pull/851/commits/b3937e598fcd69211e46ca6839bde999c1121090), as a part of [PR](https://github.com/PCMDI/pcmdi_metrics/pull/851) for cloud metric, so no worries. 

I am yet to test its influence to the cmec flag, presume there should be no impact. @acordonez any thoughts?

**Comment by acordonez** [comment]
@lee1043 It shouldn't have any effect on the cmec flag operation, but I'll give it a test

**Comment by acordonez** [comment]
I tried out the monsoon_wang and enso drivers with the new changes. They don't include the YAML or scripts by default. The enso flag worked fine with monsoon_wang.

**Comment by lee1043** [comment]
@acordonez thank you for checking this. I believe you meant "cmec" flag worked fine with monsoon_wang and enso driver, is that right?

**Comment by acordonez** [comment]
@lee1043 I don't think we've implemented the "cmec" flag with enso driver - I get an "unrecognized argument" error when I add it in, and I don't see it in the driver code.

**Comment by lee1043** [comment]
@acordonez right, thanks for clarifying. I just got confused because you mentioned enso in your comment

> I tried out the monsoon_wang and enso drivers with the new changes. They don't include the YAML or scripts by default. The enso flag worked fine with monsoon_wang.

**Comment by acordonez** [comment]
@lee1043 Oh I see, my brain kept skipping over my own typo! Yes, the cmec flag.
