### ISSUE TITLE
Update README to reflect 3.0 release

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#902]
Congrats on the new release, 3.0 a big jump.

The README is still listing 2.5.1, so might be nice to give that a tweak.

@mzelinka, next time we should make sure your PRs are reflected in the [contributors page](https://github.com/PCMDI/pcmdi_metrics/graphs/contributors) welcome to the PMP contributors

**Comment by lee1043** [comment]
Nice catch! Thanks. I will update it!
