### ISSUE TITLE
Install from conda-forge hangs forever

### ISSUE THREAD

**Issue by ShihengDuan** [PCMDI/pcmdi_metrics#912]
Everything works fine until I got some errors and decided to reinstall PMP. 
I'm trying to install with ```conda install -c conda-forge pcmdi_metrics``` but it hangs forever and have to manually stop it. Here is the output: 
```
(pmp) /home/duan5$ conda install pcmdi_metrics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -\|| - | - / ^Z
[5]+  Stopped                 ( __add_sys_prefix_to_path; "$CONDA_EXE" $_CE_M $_CE_CONDA "$@" )
```

Is it something related to my conda config? Here is the config:
```
(pmp) /home/duan5$ cat ~/.condarc
ssl_verify: false
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
I've reinstalled miniconda but it doesn't help. Any ideas why?

**Comment by lee1043** [comment]
@ShihengDuan thank you for bring this to our attention. @acordonez do you have any idea on this?

**Comment by lee1043** [comment]
@ShihengDuan if you create a new env from `base` env, could you check if that would be the same?
```conda create -n pmp_20230323 -c conda-forge pcmdi_metrics```

**Comment by acordonez** [comment]
@ShihengDuan @lee1043 I can confirm that I am also seeing this  problem. Hanging on the solve for 10+ minutes and counting. I tested on Mac and Unix. I am also seeing this with version 2.5.1 - so it does not seem that new dependencies added for version 3 are at fault.

**Comment by acordonez** [comment]
@ShihengDuan @lee1043 I installed [mamba](https://mamba.readthedocs.io/en/latest/installation.html) in my base and used it to create a new PMP environment, which only took a couple of minutes. Still not sure why it is slower now than in the past, but mamba can be used as a workaround.

**Comment by ShihengDuan** [comment]
> @ShihengDuan if you create a new env from `base` env, could you check if that would be the same?
> `conda create -n pmp_20230323 -c conda-forge pcmdi_metrics`

I'm still seeing it hangs and here is my output:
```
/home/duan5$ conda activate base
(base) /home/duan5$ which conda
~/miniconda3/bin/conda
(base) /home/duan5$ conda create -n pmp_20230323 -c conda-forge pcmdi_metrics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
```

**Comment by lee1043** [comment]
@ShihengDuan I am glad to hear mamba worked for you. I could reproduce your conda issue as well even after activating conda by `conda activate` and updating conda by `conda update conda` 

@acordonez I see conda install for other packages are working (e.g., `conda create -n xcdat_20230327 -c conda-forge xcdat`). With that, I suspect one or few of PMP dependencies are causing this issue, but couldn't specify.

@tomvothecoder we have an issue that conda install for PMP is not working with the process hanging at solving env forever when do `conda create -n pmp_test -c conda-forge pcmdi_metrics`. I am tagging you wondering if you can share your knowledge if you had experienced any similar issue.

**Comment by tomvothecoder** [comment]
> @tomvothecoder we have an issue that conda install for PMP is not working with the process hanging at solving env forever when do `conda create -n pmp_test -c conda-forge pcmdi_metrics`. I am tagging you wondering if you can share your knowledge if you had experienced any similar issue.

From my experience, `conda` usually hangs on `Solving Environment: /` if there are dependency conflicts. `conda` can take ages to print out the console output for dependency conflicts, especially if there are many dependencies to solve in the environment. This log output is more often than not unreadable and unhelpful.

`mamba` is a drop-in replacement of `conda` that is based on C (which is why it is so fast) and I believe it has its own algorithm for solving environments. Usually `mamba` will show a much more helpful output if dependency conflicts occur, but sometimes it is able to solve environments in cases where `conda` cannot.

The first step I would take is to let `conda` work through the `Solving Environment: /` in the background to confirm whether or not dependency conflicts exist. This might take minutes to hours unfortunately.

**Comment by xylar** [comment]
@tomvothecoder, all I can really suggest at this point is to modify all your documentation to recommend using `mamba` instead of `conda`.  The tool I have for solving environment conflicts uses `mamba` to solve the environment so it won't turn up anything that a `mamba` install you all have tried doesn't turn up.  the `conda` solver is so painfully slow that there's simply no good reason to use it.

**Comment by xylar** [comment]
An update on this.  I was able to reproduce a failure that I think is relevant with:
```
$ mamba create -y -n test pcmdi_metrics python=3.11
...
└─ python 3.11**  is uninstallable because there are no viable options
   ├─ python 3.11.0 would require
   │  └─ python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported;
   └─ python [3.11.0|3.11.2] conflicts with any installable versions previously reported.
```

I believe `mamba` without the python constrain is creating an environment with python 3.10 but `conda` defaults to using the same version of python as in the `base` environment so it is either unable or very reluctant to downgrade python.

I'm still investigating what dependencies are preventing python 3.11 installation but at this point I'm seeing indications that `rasterio` and the constraint `numpy <1.23.0` are involved.

**Comment by xylar** [comment]
Many dependencies (`genutil`, `cdms2` and `enso_metrics` among them) are not available for python 3.11 so that's at least part of the story.

There seems to be more to it than that because:
```
conda create -y -n test pcmdi_metrics python=3.10
```
is also hanging.

**Comment by lee1043** [comment]
@tomvothecoder @xylar thank you for investigating this and for the suggestion! I agree updating document to use `mamba` with alternative  `$ conda create -y -n test python=3.10 pcmdi_metrics=3.0.1` should be considered. @acordonez could you please help on this?

Ultimately, I think it would be helpful to reduce some dependencies and/or make them optional, but it will needs more thoughts.

**Comment by tomvothecoder** [comment]
Thanks a lot @xylar!

**Comment by lee1043** [comment]
@acordonez and @lee1043 updated PMP documentation to encourage using mamba

- PMP Readthedoc page: http://pcmdi.github.io/pcmdi_metrics/install.html
- PMP wiki page: https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-conda-forge-(recommended)

Thanks to @ShihengDuan @acordonez @tomvothecoder @xylar for their contributions!
