### ISSUE TITLE
Update documentation for Installation PMP in Mac M1 CPU machines

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#923]
Install cdat or packages depend on cdat (e3sm_diags, PMP) on Mac M1
Install Python environment using either x86_64 (osx-64) instead of arm64 (osx-arm64) would work? 
example:
CONDA_SUBDIR=osx-64 conda create -n myenv_x86 python=3.9
conda activate myenv_x86
conda config --env --set subdir osx-64
Reference: https://towardsdatascience.com/python-conda-environments-for-both-arm64-and-x86-64-on-m1-apple-silicon-147b943ffa55
https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12

add this to your conda command:  CONDA_SUBDIR=osx-64

**Comment by acordonez** [comment]
@lee1043 I've updated the [install wiki page](https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-conda-forge-(recommended)) with the suggested strategy from the TDS page.

**Comment by acordonez** [comment]
@durack1  Have you tested out the "Apple Silicon" instructions from the [install wiki page](https://github.com/PCMDI/pcmdi_metrics/wiki/Install-using-conda-forge-(recommended))?
