### ISSUE TITLE
computing climatolologies spanning multiple files

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#924]
calculate_climatology.py needs to be updated to be able to open multiple files via mfopen.

**Comment by lee1043** [comment]
Hi @gleckler1, thank you for pointing this out.

The current code already allows open multiple netcdf files in some degree, but I think what you are looking for is allowing use of the wildcard (`*`), which the current code does not allow. 

[`calculate_climatology.py`](https://github.com/PCMDI/pcmdi_metrics/blob/3eb110aee11b65493f2be6d283cf2d711c882a22/pcmdi_metrics/mean_climate/lib/calculate_climatology.py#L24) open files using [`xcdat_open`](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/io/xcdat_openxml.py#L9) function, which determine if given input is whether xml, single netcdf or python list of multiple netcdf files. The `xcdat_open` was an interim function temporarily used until xcdat's `open_mfdataset` is updated. 

With the updated`xcdat`'s [`open_mfdataset`](https://xcdat.readthedocs.io/en/latest/generated/xcdat.open_mfdataset.html) that allows opening xml, single nc, multiple nc files given as list or searched by the wildcard, I think I can make an easy fix on this!

**Comment by gleckler1** [comment]
@lee1043 great, thank you.   Ok xcdat's open_mfdataset sounds like a great fix.  When do you think it will be ready to distinguish between a single vs multiple .nc files to read?
