### ISSUE TITLE
cdms2 error when installing pcmdi_metrics with mamba

### ISSUE THREAD

**Issue by kristinchang3** [PCMDI/pcmdi_metrics#995]
I tried installing PMP using mamba on MacOS (`mamba create -n [YOUR_CONDA_ENVIRONMENT] -c conda-forge pcmdi_metrics`) according to the PCMDI guide here: https://pcmdi.github.io/pcmdi_metrics/install.html . 

Initially, I received the following error:
![image](https://github.com/PCMDI/pcmdi_metrics/assets/143142064/fde69b48-731a-48d2-9035-092cb3d522f5)

After trying all of the other methods suggested in the guide, I was still unsuccessful. Through my troubleshooting, I uninstalled and reinstalled mamba: 
```
conda remove -n base --force mamba
conda install -n base -c conda-forge mamba
```
and also installed xcdat. 

Then, when I ran the code chunk for Apple M1 and M2 chips at the bottom of the installation guide, I was able to install the package successfully! I'm not sure exactly which of these actions directly addressed the error above, but I wanted to share my process in case others run into this issue.

**Comment by lee1043** [comment]
Closing this issue because it was posted for documenting purposes. It is another justification for accelerating xCDAT implementation and removing CDAT/cdms dependencies.
